/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.validation;

import com.tibco.cep.designtime.core.model.service.channel.DriverManager;

import com.tibco.cep.studio.core.index.model.ArchiveElement;
import com.tibco.cep.studio.core.index.model.DecisionTableElement;
import com.tibco.cep.studio.core.index.model.DesignerProject;
import com.tibco.cep.studio.core.index.model.EntityElement;
import com.tibco.cep.studio.core.index.model.InstanceElement;
import com.tibco.cep.studio.core.index.model.RuleElement;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.DesignerProject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DesignerProjectValidator {
	boolean validate();

	boolean validateEntityElements(EList<EntityElement> value);
	boolean validateDecisionTableElements(EList<DecisionTableElement> value);
	boolean validateArchiveElements(EList<ArchiveElement> value);
	boolean validateRuleElements(EList<RuleElement> value);
	boolean validateRootPath(String value);
	boolean validateLastPersisted(Date value);
	boolean validateReferencedProjects(EList<DesignerProject> value);
	boolean validateDriverManager(DriverManager value);
	boolean validateDomainInstanceElements(EList<InstanceElement<?>> value);
	boolean validateArchivePath(String value);
	boolean validateVersion(int value);
}
