/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.validation;

import com.tibco.cep.studio.core.index.model.ElementReference;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.ElementReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementReferenceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAttRef(boolean value);
	boolean validateTypeRef(boolean value);
	boolean validateOffset(int value);
	boolean validateLength(int value);
	boolean validateQualifier(ElementReference value);
	boolean validateArray(boolean value);
	boolean validateMethod(boolean value);
	boolean validateBinding(Object value);
}
