/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.validation;

import com.tibco.cep.designtime.core.model.rule.Compilable;

import com.tibco.cep.studio.core.index.model.GlobalVariableDef;

import com.tibco.cep.studio.core.index.model.scope.RootScopeBlock;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.RuleElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleElementValidator {
	boolean validate();

	boolean validateRule(Compilable value);
	boolean validateVirtual(boolean value);
	boolean validateScope(RootScopeBlock value);
	boolean validateGlobalVariables(EList<GlobalVariableDef> value);
	boolean validateIndexName(String value);
}
