/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.validation;

import com.tibco.cep.studio.core.index.model.scope.CompilableScopeEntry;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.StateMachineElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateMachineElementValidator {
	boolean validate();

	boolean validateCompilableScopes(EList<CompilableScopeEntry> value);
	boolean validateIndexName(String value);
}
