<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decisionprojectmodel" nsURI="http:///com/tibco/cep/decisionproject/model/decisionproject.ecore"
    nsPrefix="dp">
  <eClassifiers xsi:type="ecore:EClass" name="DecisionProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontology" eType="ecore:EClass ontology.ecore#//Ontology"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" eType="#//DomainModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authToken" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="md" eType="ecore:EClass DecisionTable.ecore#//MetaData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel" eSuperTypes="ontology.ecore#//AccessControlCandidate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" upperBound="-1"
        eType="ecore:EClass DomainModel.ecore#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModifiedBy" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
