package com.tibco.cep.mapper.xml.xdata.bind;

import com.tibco.cep.mapper.xml.xdata.xpath.FunctionResolver;
import com.tibco.xml.schema.SmComponentProviderEx;

/**
 * Replacement for BindingReport.
 * Generated by a Binding (template), this contains the computed types & error messages
 * for a Binding's formula.  A report applies to a single Binding & describes what is going to do, any errors that apply
 * to it, etc.
 */
public final class StylesheetContext
{
    private final SmComponentProviderEx mComponentProvider;
    private final FunctionResolver mEntryFunctions;
    private final StylesheetResolver mStylesheets;

    public StylesheetContext(SmComponentProviderEx cp, FunctionResolver functions, StylesheetResolver sr) {
        mComponentProvider = cp;
        mEntryFunctions = functions;
        mStylesheets = sr;
    }

    public FunctionResolver getFunctionResolver() {
        return mEntryFunctions;
    }

    public SmComponentProviderEx getComponentProvider() {
        return mComponentProvider;
    }

    public StylesheetResolver getStylesheetResolver() {
        return mStylesheets;
    }
}

