//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.15 at 12:35:44 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.tibco.com/be/studio/tester", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.cep.studio.tester.core.model;
