/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.event.validation;


/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.event.NamespaceEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamespaceEntryValidator {
	boolean validate();

	boolean validatePrefix(String value);
	boolean validateNamespace(String value);
}
