/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.event.validation;

import com.tibco.cep.designtime.core.model.TIMEOUT_UNITS;

import com.tibco.cep.designtime.core.model.event.EVENT_SCHEDULE_TYPE;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.event.TimeEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeEventValidator {
	boolean validate();

	boolean validateScheduleType(EVENT_SCHEDULE_TYPE value);
	boolean validateTimeEventCount(long value);
	boolean validateInterval(int value);
	boolean validateIntervalUnit(TIMEOUT_UNITS value);
}
