/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.event.validation;

import com.tibco.cep.designtime.core.model.PROPERTY_TYPES;
import com.tibco.cep.designtime.core.model.PropertyMap;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.event.UserProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserPropertyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(PROPERTY_TYPES value);
	boolean validateExtendedProperties(PropertyMap value);
}
