//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 08:08:54 PM PDT 
//


package com.tibco.cep.bemm.persistence.topology.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}master-files"/>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}run-version"/>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}deployment-units" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}deployment-mappings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="project-cdd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "masterFiles",
    "runVersion",
    "deploymentUnits",
    "deploymentMappings"
})
@XmlRootElement(name = "cluster")
public class Cluster {

    @XmlElement(name = "master-files", required = true)
    protected MasterFiles masterFiles;
    @XmlElement(name = "run-version", required = true)
    protected RunVersion runVersion;
    @XmlElement(name = "deployment-units")
    protected DeploymentUnits deploymentUnits;
    @XmlElement(name = "deployment-mappings")
    protected DeploymentMappings deploymentMappings;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "project-cdd")
    protected String projectCdd;

    /**
     * Gets the value of the masterFiles property.
     * 
     * @return
     *     possible object is
     *     {@link MasterFiles }
     *     
     */
    public MasterFiles getMasterFiles() {
        return masterFiles;
    }

    /**
     * Sets the value of the masterFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterFiles }
     *     
     */
    public void setMasterFiles(MasterFiles value) {
        this.masterFiles = value;
    }

    /**
     * Gets the value of the runVersion property.
     * 
     * @return
     *     possible object is
     *     {@link RunVersion }
     *     
     */
    public RunVersion getRunVersion() {
        return runVersion;
    }

    /**
     * Sets the value of the runVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunVersion }
     *     
     */
    public void setRunVersion(RunVersion value) {
        this.runVersion = value;
    }

    /**
     * Gets the value of the deploymentUnits property.
     * 
     * @return
     *     possible object is
     *     {@link DeploymentUnits }
     *     
     */
    public DeploymentUnits getDeploymentUnits() {
        return deploymentUnits;
    }

    /**
     * Sets the value of the deploymentUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentUnits }
     *     
     */
    public void setDeploymentUnits(DeploymentUnits value) {
        this.deploymentUnits = value;
    }

    /**
     * Gets the value of the deploymentMappings property.
     * 
     * @return
     *     possible object is
     *     {@link DeploymentMappings }
     *     
     */
    public DeploymentMappings getDeploymentMappings() {
        return deploymentMappings;
    }

    /**
     * Sets the value of the deploymentMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentMappings }
     *     
     */
    public void setDeploymentMappings(DeploymentMappings value) {
        this.deploymentMappings = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the projectCdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCdd() {
        return projectCdd;
    }

    /**
     * Sets the value of the projectCdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCdd(String value) {
        this.projectCdd = value;
    }

}
