//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.12 at 02:08:33 AM PDT 
//


package com.tibco.cep.bemm.persistence.topology.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}deployed-files"/>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}processing-units-config"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deployedFiles",
    "processingUnitsConfig"
})
@XmlRootElement(name = "deployment-unit")
public class DeploymentUnit {

    @XmlElement(name = "deployed-files", required = true)
    protected DeployedFiles deployedFiles;
    @XmlElement(name = "processing-units-config", required = true)
    protected ProcessingUnitsConfig processingUnitsConfig;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;


	/**
     * Gets the value of the deployedFiles property.
     * 
     * @return
     *     possible object is
     *     {@link DeployedFiles }
     *     
     */
    public DeployedFiles getDeployedFiles() {
        return deployedFiles;
    }

    /**
     * Sets the value of the deployedFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeployedFiles }
     *     
     */
    public void setDeployedFiles(DeployedFiles value) {
        this.deployedFiles = value;
    }

    /**
     * Gets the value of the processingUnitsConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingUnitsConfig }
     *     
     */
    public ProcessingUnitsConfig getProcessingUnitsConfig() {
        return processingUnitsConfig;
    }

    /**
     * Sets the value of the processingUnitsConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingUnitsConfig }
     *     
     */
    public void setProcessingUnitsConfig(ProcessingUnitsConfig value) {
        this.processingUnitsConfig = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
