//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 12:25:19 AM IST 
//


package com.tibco.cep.bemm.persistence.topology.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="use-as-engine-name" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="puid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jmxport" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jmxUserName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jmxPassword" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "processing-unit-config")
public class ProcessingUnitConfig {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "use-as-engine-name")
    protected Boolean useAsEngineName;
    @XmlAttribute(name = "puid")
    protected String puid;
    @XmlAttribute(name = "jmxport")
    protected String jmxport;
    @XmlAttribute(name = "jmxUserName")
    protected String jmxUserName;
    @XmlAttribute(name = "jmxPassword")
    protected String jmxPassword;
    @XmlAttribute(name = "beId")
    protected String beId;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the useAsEngineName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseAsEngineName() {
        if (useAsEngineName == null) {
            return false;
        } else {
            return useAsEngineName;
        }
    }

    /**
     * Sets the value of the useAsEngineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAsEngineName(Boolean value) {
        this.useAsEngineName = value;
    }

    /**
     * Gets the value of the puid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuid() {
        return puid;
    }

    /**
     * Sets the value of the puid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuid(String value) {
        this.puid = value;
    }

    /**
     * Gets the value of the jmxport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxport() {
        return jmxport;
    }

    /**
     * Sets the value of the jmxport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxport(String value) {
        this.jmxport = value;
    }

    /**
     * Gets the value of the jmxUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxUserName() {
        return jmxUserName;
    }

    /**
     * Sets the value of the jmxUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxUserName(String value) {
        this.jmxUserName = value;
    }

    /**
     * Gets the value of the jmxPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxPassword() {
        return jmxPassword;
    }

    /**
     * Sets the value of the jmxPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxPassword(String value) {
        this.jmxPassword = value;
    }

	/**
	 * @return the beId
	 */
	public String getBeId() {
		return beId;
	}

	/**
	 * @param beId the beId to set
	 */
	public void setBeId(String beId) {
		this.beId = beId;
	}

}
