//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.06 at 02:03:38 AM PDT 
//


package com.tibco.cep.bemm.persistence.topology.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tibco.com/businessevents/BEMM/2009/09/BEMMTopology.xsd}be-runtime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beRuntime"
})
@XmlRootElement(name = "run-version")
public class RunVersion {

    @XmlElement(name = "be-runtime", required = true)
    protected BeRuntime beRuntime;

    /**
     * Gets the value of the beRuntime property.
     * 
     * @return
     *     possible object is
     *     {@link BeRuntime }
     *     
     */
    public BeRuntime getBeRuntime() {
        return beRuntime;
    }

    /**
     * Sets the value of the beRuntime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeRuntime }
     *     
     */
    public void setBeRuntime(BeRuntime value) {
        this.beRuntime = value;
    }

}
