/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.domain.validation;

import com.tibco.cep.designtime.core.model.DOMAIN_DATA_TYPES;

import com.tibco.cep.designtime.core.model.domain.Domain;
import com.tibco.cep.designtime.core.model.domain.DomainEntry;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.domain.Domain}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainValidator {
	boolean validate();

	boolean validateId(long value);
	boolean validateEntries(EList<DomainEntry> value);
	boolean validateDataType(DOMAIN_DATA_TYPES value);
	boolean validateSuperDomainPath(String value);
	boolean validateSuperDomain(Domain value);
}
