/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.domain.validation;


/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.domain.Range}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RangeValidator {
	boolean validate();

	boolean validateLower(String value);
	boolean validateUpper(String value);
	boolean validateLowerInclusive(boolean value);
	boolean validateUpperInclusive(boolean value);
}
