//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.06 at 07:44:53 PM IST 
//


package com.tibco.cep.bemm.monitoring.metric.view.config;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AndFilterDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AndFilterDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqFilter" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}EqFilterDef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="gtFilter" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}GtFilterDef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ltFilter" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}LtFilterDef" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AndFilterDef", propOrder = {
    "eqFilter",
    "gtFilter",
    "ltFilter"
})
public class AndFilterDef
    implements Serializable
{

    private final static long serialVersionUID = 33333L;
    protected List<EqFilterDef> eqFilter;
    protected List<GtFilterDef> gtFilter;
    protected List<LtFilterDef> ltFilter;

    /**
     * Gets the value of the eqFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eqFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEqFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EqFilterDef }
     * 
     * 
     */
    public List<EqFilterDef> getEqFilter() {
        if (eqFilter == null) {
            eqFilter = new ArrayList<EqFilterDef>();
        }
        return this.eqFilter;
    }

    public boolean isSetEqFilter() {
        return ((this.eqFilter!= null)&&(!this.eqFilter.isEmpty()));
    }

    public void unsetEqFilter() {
        this.eqFilter = null;
    }

    /**
     * Gets the value of the gtFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gtFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGtFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GtFilterDef }
     * 
     * 
     */
    public List<GtFilterDef> getGtFilter() {
        if (gtFilter == null) {
            gtFilter = new ArrayList<GtFilterDef>();
        }
        return this.gtFilter;
    }

    public boolean isSetGtFilter() {
        return ((this.gtFilter!= null)&&(!this.gtFilter.isEmpty()));
    }

    public void unsetGtFilter() {
        this.gtFilter = null;
    }

    /**
     * Gets the value of the ltFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ltFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLtFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LtFilterDef }
     * 
     * 
     */
    public List<LtFilterDef> getLtFilter() {
        if (ltFilter == null) {
            ltFilter = new ArrayList<LtFilterDef>();
        }
        return this.ltFilter;
    }

    public boolean isSetLtFilter() {
        return ((this.ltFilter!= null)&&(!this.ltFilter.isEmpty()));
    }

    public void unsetLtFilter() {
        this.ltFilter = null;
    }

}
