//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.06 at 07:44:53 PM IST 
//


package com.tibco.cep.bemm.monitoring.metric.view.config;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Chart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Chart">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}MetricsView">
 *       &lt;sequence>
 *         &lt;element name="xConfig" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}attributeConfig"/>
 *         &lt;element name="yConfig" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}attributeConfig"/>
 *         &lt;element name="series" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}ChartSeries" maxOccurs="unbounded"/>
 *         &lt;element name="poller" type="{http://www.tibco.com/cep/bemm/monitoring/metric/view/config}RefreshPoller" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Chart", propOrder = {
    "xConfig",
    "yConfig",
    "series",
    "poller"
})
public class Chart
    extends MetricsView
    implements Serializable
{

    private final static long serialVersionUID = 33333L;
    @XmlElement(required = true)
    protected AttributeConfig xConfig;
    @XmlElement(required = true)
    protected AttributeConfig yConfig;
    @XmlElement(required = true)
    protected List<ChartSeries> series;
    @XmlElement(required = true)
    protected List<RefreshPoller> poller;

    /**
     * Gets the value of the xConfig property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeConfig }
     *     
     */
    public AttributeConfig getXConfig() {
        return xConfig;
    }

    /**
     * Sets the value of the xConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeConfig }
     *     
     */
    public void setXConfig(AttributeConfig value) {
        this.xConfig = value;
    }

    public boolean isSetXConfig() {
        return (this.xConfig!= null);
    }

    /**
     * Gets the value of the yConfig property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeConfig }
     *     
     */
    public AttributeConfig getYConfig() {
        return yConfig;
    }

    /**
     * Sets the value of the yConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeConfig }
     *     
     */
    public void setYConfig(AttributeConfig value) {
        this.yConfig = value;
    }

    public boolean isSetYConfig() {
        return (this.yConfig!= null);
    }

    /**
     * Gets the value of the series property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the series property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChartSeries }
     * 
     * 
     */
    public List<ChartSeries> getSeries() {
        if (series == null) {
            series = new ArrayList<ChartSeries>();
        }
        return this.series;
    }

    public boolean isSetSeries() {
        return ((this.series!= null)&&(!this.series.isEmpty()));
    }

    public void unsetSeries() {
        this.series = null;
    }

    /**
     * Gets the value of the poller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefreshPoller }
     * 
     * 
     */
    public List<RefreshPoller> getPoller() {
        if (poller == null) {
            poller = new ArrayList<RefreshPoller>();
        }
        return this.poller;
    }

    public boolean isSetPoller() {
        return ((this.poller!= null)&&(!this.poller.isEmpty()));
    }

    public void unsetPoller() {
        this.poller = null;
    }

}
