/**
 *
 * $Id$
 */
package com.tibco.be.util.config.sharedresources.id.validation;

import com.tibco.be.util.config.sharedresources.id.ResourceDescriptions;

/**
 * A sample validator interface for {@link com.tibco.be.util.config.sharedresources.id.Designer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DesignerValidator {
	boolean validate();

	boolean validateLockedProperties(String value);
	boolean validateFixedChildren(String value);
	boolean validateResourceDescriptions(ResourceDescriptions value);
}
