/**
 *
 * $Id$
 */
package com.tibco.be.util.config.sharedresources.id.validation;

import com.tibco.be.util.config.sharedresources.id.Designer;

/**
 * A sample validator interface for {@link com.tibco.be.util.config.sharedresources.id.Identity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IdentityValidator {
	boolean validate();

	boolean validateDesigner(Designer value);
	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateObjectType(Object value);
	boolean validateUsername(String value);
	boolean validatePassword(String value);
	boolean validateFileType(Object value);
	boolean validateUrl(String value);
	boolean validatePassPhrase(String value);
	boolean validateCertUrl(String value);
	boolean validatePrivateKeyUrl(String value);
}
