kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gcp-webstud
  annotations:
    volume.beta.kubernetes.io/storage-class: "pksrmsgcp"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
