/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.element.validation;

import com.tibco.cep.designtime.core.model.element.Concept;
import com.tibco.cep.designtime.core.model.element.PropertyDefinition;

import com.tibco.cep.designtime.core.model.rule.RuleSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.element.Concept}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConceptValidator {
	boolean validate();

	boolean validateSubConcepts(EList<Concept> value);
	boolean validateProperties(EList<PropertyDefinition> value);
	boolean validateRuleSet(RuleSet value);
	boolean validateStateMachinePaths(EList<String> value);
	boolean validateRootStateMachinePath(String value);
	boolean validateParentConcept(Concept value);
	boolean validateParentConceptPath(String value);
	boolean validateSuperConcept(Concept value);
	boolean validateSuperConceptPath(String value);
	boolean validateScorecard(boolean value);
	boolean validateMetric(boolean value);
	boolean validateContained(boolean value);
	boolean validatePOJO(boolean value);
	boolean validateTransient(boolean value);
	boolean validateImplClass(String value);
	boolean validateSubConceptsPath(EList<String> value);
	boolean validateAutoStartStateMachine(boolean value);
}
