/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.element.validation;

import com.tibco.cep.designtime.core.model.METRIC_TYPE;
import com.tibco.cep.designtime.core.model.TIME_UNITS;

import com.tibco.cep.designtime.core.model.element.PropertyDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.element.Metric}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetricValidator {
	boolean validate();

	boolean validateType(METRIC_TYPE value);
	boolean validateWindowType(TIME_UNITS value);
	boolean validateWindowSize(long value);
	boolean validateRecurringTimeType(TIME_UNITS value);
	boolean validateRecurringFrequency(long value);
	boolean validateStartTime(long value);
	boolean validateShortName(String value);
	boolean validatePersistent(boolean value);
	boolean validateTransactionalRolling(boolean value);
	boolean validateEnabled(boolean value);
	boolean validateRetentionTimeType(TIME_UNITS value);
	boolean validateRetentionTimeSize(long value);
	boolean validateUserDefinedFields(EList<PropertyDefinition> value);
}
