/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.element.validation;

import com.tibco.cep.designtime.core.model.METRIC_AGGR_TYPE;
import com.tibco.cep.designtime.core.model.PROPERTY_TYPES;

import com.tibco.cep.designtime.core.model.domain.DomainInstance;

import com.tibco.cep.designtime.core.model.element.PropertyDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.element.PropertyDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyDefinitionValidator {
	boolean validate();

	boolean validateType(PROPERTY_TYPES value);
	boolean validateConceptTypePath(String value);
	boolean validateArray(boolean value);
	boolean validateOwnerPath(String value);
	boolean validateHistoryPolicy(int value);
	boolean validateHistorySize(int value);
	boolean validateOrder(int value);
	boolean validateDefaultValue(String value);
	boolean validateDisjointSet(EList<String> value);
	boolean validateSuper(String value);
	boolean validateParent(PropertyDefinition value);
	boolean validateTransitive(boolean value);
	boolean validateEquivalentProperties(EList<PropertyDefinition> value);
	boolean validateAttributeDefinitions(EList<PropertyDefinition> value);
	boolean validateAggregationType(METRIC_AGGR_TYPE value);
	boolean validateGroupByField(boolean value);
	boolean validateGroupByPosition(long value);
	boolean validateTimeWindowField(boolean value);
	boolean validateDomainInstances(EList<DomainInstance> value);
}
