apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bediscovery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        dep_name: "bediscovery-label"
    spec:
      containers:
      - name: bediscovery-container
        image:  "com.tibco.be.cca:v01"
        env:
        - name: PU
          value: "cache"
        resources:
          requests:
            memory: 700Mi
        volumeMounts:
        - mountPath: "/opt/tibco/be/5.6/rms/shared/"
          name: shared
        - mountPath: "/opt/tibco/be/5.6/rms/config/security/"
          name: security
        - mountPath: "/opt/tibco/be/5.6/examples/standard/WebStudio/"
          name: webstudio
        - mountPath: "/opt/tibco/be/5.6/rms/config/notify/"
          name: notify
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: security
          persistentVolumeClaim:
            claimName: security-pvc
        - name: webstudio
          persistentVolumeClaim:
            claimName: webstudio-pvc
        - name: notify
          persistentVolumeClaim:
            claimName: notify-pvc
