<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registry"
    nsURI="http:///www.tibco.com/be/addon_registry.xsd" nsPrefix="reg">
  <eClassifiers xsi:type="ecore:EClass" name="AddOn">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="addon"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//AddOnType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexResourceProviderClass"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="indexResourceProviderClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexCacheClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="indexCacheClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ontologyAdapterClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ontologyAdapterClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapterFactoryClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="adapterFactoryClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tnsEntityHandlerClass"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="tnsEntityHandlerClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cddAgentClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="cddAgentClass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedEntityTypes" lowerBound="1"
        eType="#//SupportedElementTypes" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="supportedTypes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedExtensions" lowerBound="1"
        eType="#//SupportedExtensions" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="supportedExtensions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileExtensionMap" lowerBound="1"
        upperBound="-1" eType="#//FileExtensionMapType" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="fileExtensionMap"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tnsEntityExtensions" lowerBound="1"
        eType="#//TnsEntityExtensions" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="tnsEntityExtensions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionCatalogProvider"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="functionCatalogProvider"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AddOnType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AddOnType"/>
    </eAnnotations>
    <eLiterals name="CORE"/>
    <eLiterals name="DATAMODELLING" value="1" literal="DATA_MODELLING"/>
    <eLiterals name="EVENTSTREAMPROCESSING" value="2" literal="EVENTSTREAM_PROCESSING"/>
    <eLiterals name="DECISIONMANAGER" value="3" literal="DECISION_MANAGER"/>
    <eLiterals name="VIEWS" value="4"/>
    <eLiterals name="PROCESS" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AddOnTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AddOnType:Object"/>
      <details key="baseType" value="AddOnType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementTypes">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ElementTypes"/>
    </eAnnotations>
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="CONCEPT" value="1"/>
    <eLiterals name="SCORECARD" value="2"/>
    <eLiterals name="INSTANCE" value="3"/>
    <eLiterals name="SIMPLEEVENT" value="4" literal="SIMPLE_EVENT"/>
    <eLiterals name="METRIC" value="5"/>
    <eLiterals name="CHANNEL" value="6"/>
    <eLiterals name="DESTINATION" value="7"/>
    <eLiterals name="RULE" value="8"/>
    <eLiterals name="RULEFUNCTION" value="9"/>
    <eLiterals name="XSLT_FUNCTION" value="10"/>
    <eLiterals name="RULESET" value="11"/>
    <eLiterals name="STATEMACHINE" value="12" literal="STATE_MACHINE"/>
    <eLiterals name="TIMEEVENT" value="13" literal="TIME_EVENT"/>
    <eLiterals name="ENTERPRISEARCHIVE" value="14"/>
    <eLiterals name="BEARCHIVERESOURCE" value="15"/>
    <eLiterals name="DOMAIN" value="16"/>
    <eLiterals name="DECISIONTABLE" value="17" literal="DECISION_TABLE"/>
    <eLiterals name="FOLDER" value="18"/>
    <eLiterals name="RULETEMPLATE" value="19" literal="RULE_TEMPLATE"/>
    <eLiterals name="QUERY" value="20"/>
    <eLiterals name="VIEW" value="21"/>
    <eLiterals name="PROCESS" value="22"/>
    <eLiterals name="JAVA_SOURCE" value="23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ElementTypesObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ElementTypes:Object"/>
      <details key="baseType" value="ElementTypes"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileExtensionMapItemType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FileExtensionMapItemType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" lowerBound="1"
        eType="#//FileExtensionTypes" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="key"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="#//SupportedElementTypes" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="value"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileExtensionMapType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="fileExtensionMapType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//FileExtensionMapItemType"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="item"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FileExtensionTypes">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FileExtensionTypes"/>
    </eAnnotations>
    <eLiterals name="RULE_EXTENSION" literal="rule"/>
    <eLiterals name="RULEFUNCTION_EXTENSION" value="1" literal="rulefunction"/>
    <eLiterals name="XSLT_FUNCTION_EXTENSION" value="2" literal="xsltfunction"/>
    <eLiterals name="RULE_FN_IMPL_EXTENSION" value="3" literal="rulefunctionimpl"/>
    <eLiterals name="RULE_TEMPLATE_EXTENSION" value="4" literal="ruletemplate"/>
    <eLiterals name="RULE_TEMPLATE_VIEW_EXTENSION" value="5" literal="ruletemplateview"/>
    <eLiterals name="EAR_EXTENSION" value="6" literal="archive"/>
    <eLiterals name="TIME_EXTENSION" value="7" literal="time"/>
    <eLiterals name="STATEMACHINE_EXTENSION" value="8" literal="statemachine"/>
    <eLiterals name="JAVA_SOURCE_EXTENSION" value="9" literal="java"/>
    <eLiterals name="CONCEPT_EXTENSION" value="10" literal="concept"/>
    <eLiterals name="EVENT_EXTENSION" value="11" literal="event"/>
    <eLiterals name="SCORECARD_EXTENSION" value="12" literal="scorecard"/>
    <eLiterals name="AESCHEMA_EXTENSION" value="13" literal="aeschema"/>
    <eLiterals name="XSD_EXTENSION" value="14" literal="xsd"/>
    <eLiterals name="DTD_EXTENSION" value="15" literal="dtd"/>
    <eLiterals name="WSDL_EXTENSION" value="16" literal="wsdl"/>
    <eLiterals name="DOMAIN_EXTENSION" value="17" literal="domain"/>
    <eLiterals name="CHANNEL_EXTENSION" value="18" literal="channel"/>
    <eLiterals name="GLOBAL_VAR_EXTENSION" value="19" literal="substvar"/>
    <eLiterals name="QUERY_EXTENSION" value="20" literal="query"/>
    <eLiterals name="BE_QUERY_EXTENSION" value="21" literal="bequery"/>
    <eLiterals name="METRIC_EXTENSION" value="22" literal="metric"/>
    <eLiterals name="PROCESS_EXTENSION" value="23" literal="beprocess"/>
    <eLiterals name="SITE_TOPOLOGY_EXTENSION" value="24" literal="st"/>
    <eLiterals name="CHART" value="25" literal="chart"/>
    <eLiterals name="SMCOMPONENT" value="26" literal="smcomponent"/>
    <eLiterals name="PAGE_SELECTOR" value="27" literal="pageselector"/>
    <eLiterals name="ALERT" value="28" literal="alert"/>
    <eLiterals name="CONTEXT_ACTION_RULESET" value="29" literal="contextactionruleset"/>
    <eLiterals name="BLUEPRINT" value="30" literal="blueprint"/>
    <eLiterals name="QUERY_MANAGER" value="31" literal="querymanager"/>
    <eLiterals name="SEARCH_VIEW" value="32" literal="searchview"/>
    <eLiterals name="RELATED_ASSETS" value="33" literal="relatedassets"/>
    <eLiterals name="DRILLDOWN" value="34" literal="drilldown"/>
    <eLiterals name="VIEW" value="36" literal="view"/>
    <eLiterals name="DASHBOARDPAGE" value="37" literal="dashboardpage"/>
    <eLiterals name="ASSETPAGE" value="38" literal="assetpage"/>
    <eLiterals name="SEARCHPAGE" value="39" literal="searchpage"/>
    <eLiterals name="PAGESET" value="40" literal="pageset"/>
    <eLiterals name="SERIES_COLOR" value="41" literal="seriescolor"/>
    <eLiterals name="TEXT_COLORSET" value="42" literal="textcolorset"/>
    <eLiterals name="CHART_COLORSET" value="43" literal="chartcolorset"/>
    <eLiterals name="HEADER" value="44" literal="header"/>
    <eLiterals name="LOGIN" value="45" literal="login"/>
    <eLiterals name="SKIN" value="46" literal="skin"/>
    <eLiterals name="ROLEPREFERENCE" value="47" literal="rolepreference"/>
    <eLiterals name="DATASOURCE" value="48" literal="datasource"/>
    <eLiterals name="SYSTEM" value="49" literal="system"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FileExtensionTypesObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FileExtensionTypes:Object"/>
      <details key="baseType" value="FileExtensionTypes"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Registry">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xmlns:prefix"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xsi:schemaLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addOn" upperBound="-2"
        eType="#//AddOn" volatile="true" transient="true" derived="true" containment="true"
        resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="addon"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedElementTypes">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="supportedElementTypes"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" unique="false"
        lowerBound="1" upperBound="-1" eType="#//ElementTypes">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="elementType"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedExtensions">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="supportedExtensions"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" unique="false"
        lowerBound="1" upperBound="-1" eType="#//FileExtensionTypes">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="extension"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TnsEntityExtensions">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="tnsEntityExtensions"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" unique="false"
        upperBound="-1" eType="#//FileExtensionTypes">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="extension"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
