<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basetypes" nsURI="http://tibco.com/be/basetypes" nsPrefix="basetypes">
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="booleanOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#boolean gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DateTimeOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="dateTimeOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#dateTime gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DecimalOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="decimalOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#decimal gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoubleOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="doubleOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#double gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FloatOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="floatOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#float gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Gv" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="gv-type"/>
      <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
      <details key="pattern" value="([^%25]*%25%25[^%25]*%25%25)+[^%25]*"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="HexBinaryOrGVs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="hexBinaryOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#hexBinary gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IntOrGVs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="intOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#int gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JndiPropertyTypeOrGvs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="jndiPropertyTypeOrGvs-type"/>
      <details key="memberTypes" value="gv-type jndiPropertyTypeOrGvs-type_._member_._1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JndiPropertyTypeOrGvsEnum">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="jndiPropertyTypeOrGvs-type_._member_._1"/>
    </eAnnotations>
    <eLiterals name="boolean"/>
    <eLiterals name="byte" value="1"/>
    <eLiterals name="char" value="2"/>
    <eLiterals name="double" value="3"/>
    <eLiterals name="float" value="4"/>
    <eLiterals name="int" value="5"/>
    <eLiterals name="long" value="6"/>
    <eLiterals name="short" value="7"/>
    <eLiterals name="string" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JndiPropertyTypeOrGvsEnumObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="jndiPropertyTypeOrGvs-type_._member_._1:Object"/>
      <details key="baseType" value="jndiPropertyTypeOrGvs-type_._member_._1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LongOrGVs" instanceClassName="java.lang.Object">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="longOrGVs-type"/>
      <details key="memberTypes" value="http://www.eclipse.org/emf/2003/XMLType#long gv-type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StringOrGVs" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="stringOrGVs-type"/>
      <details key="memberTypes" value="gv-type http://www.eclipse.org/emf/2003/XMLType#string"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
