/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.validation;

import com.tibco.cep.designtime.core.model.PropertyMap;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.Entity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityValidator {
	boolean validate();

	boolean validateNamespace(String value);
	boolean validateFolder(String value);
	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateLastModified(String value);
	boolean validateGUID(String value);
	boolean validateOntology(EObject value);
	boolean validateExtendedProperties(PropertyMap value);
	boolean validateHiddenProperties(PropertyMap value);
	boolean validateTransientProperties(PropertyMap value);
	boolean validateOwnerProjectName(String value);
}
