CREATE TABLE ENTITY_DATASOURCE
(
  DATASOURCE_NAME                VARCHAR2(100)              NOT NULL,
  JDBC_DRIVER  VARCHAR2(2048)              NOT NULL,
  JDBC_URL         VARCHAR2(2048)              NOT NULL,
  USERNAME       VARCHAR2(100)              NOT NULL,
  PASSWORD       VARCHAR2(100)              NOT NULL,
  SCHEMA_OWNER VARCHAR2(100)           NOT NULL,
  PROJECT_NAME                VARCHAR2(100)              NOT NULL,
  DESCRIPTION  VARCHAR2(2048)                       NULL
);

ALTER TABLE ENTITY_DATASOURCE ADD (CONSTRAINT PK_DATASOURCE PRIMARY KEY (NAME));

CREATE TABLE ENTITY
(
  ENTITY_NAME             VARCHAR2(100)   NOT NULL,
  DATASOURCE              VARCHAR2(100)   DEFAULT 'EXTENDED',
  SUPERENTITY_NAME        VARCHAR2(100),
  SUPERENTITY_DATASOURCE  VARCHAR2(100),
  DESCRIPTION               VARCHAR2(2048)
);

ALTER TABLE ENTITY ADD (
  CONSTRAINT PK_ENTITY PRIMARY KEY (ENTITY_NAME, DATASOURCE));


CREATE TABLE ENTITY_PROPERTY
(
  ENTITY_NAME                        VARCHAR2(100),
  DATASOURCE                         VARCHAR2(100) DEFAULT 'EXTENDED',
  PROPERTY_NAME                  VARCHAR2(100),
  PROPERTY_TYPE                   VARCHAR2(100),
  SPECIFIC_TYPE                       VARCHAR2(100),
  SPECIFIC_TYPE_DATASOURCE  VARCHAR2(100),
  DESCRIPTION                          VARCHAR2(2048),
  RESTRICTIONS                        VARCHAR2(2048),
  MINOCCURS                            VARCHAR2(10),
  MAXOCCURS                           VARCHAR2(10)
);

ALTER TABLE ENTITY_PROPERTY ADD (
  CONSTRAINT PK_ENTITY_PROPERTY PRIMARY KEY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME));
ALTER TABLE ENTITY_PROPERTY ADD (
  CONSTRAINT FK_ENTITY_PROPERTY FOREIGN KEY (ENTITY_NAME, DATASOURCE) REFERENCES ENTITY(ENTITY_NAME, DATASOURCE));
ALTER TABLE ENTITY_PROPERTY ADD 
  CONSTRAINT CHK_ENTITY_PROPERTY_PROP_TYPE CHECK ( PROPERTY_TYPE IN ('STRING', 'INT', 'LONG', 'DOUBLE', 'BOOLEAN', 'DATETIME', 'CONTAINED', 'REFERENCE'));


CREATE TABLE ENTITY_UNIQUE_IDENTIFIERS
(
  TABLE_NAME     VARCHAR2(100),
  DATASOURCE     VARCHAR2(100),
  COLUMN_NAME    VARCHAR2(100),
  IDENTIFIER_NAME  VARCHAR2(100)
);

ALTER TABLE ENTITY_UNIQUE_IDENTIFIERS ADD (
  CONSTRAINT PK_SEQUENCE PRIMARY KEY (TABLE_NAME, DATASOURCE, COLUMN_NAME));
ALTER TABLE ENTITY_UNIQUE_IDENTIFIERS ADD (
  CONSTRAINT FK_SEQUENCE FOREIGN KEY (DATASOURCE) REFERENCES ENTITY_DATASOURCE(NAME)); 


CREATE TABLE WSDL
(
  WSDL_NAME         VARCHAR2(100)  NOT NULL,
  TARGET_NAMESPACE  VARCHAR2(2048)  NOT NULL,
  DESCRIPTION     VARCHAR2(2048)
);

ALTER TABLE WSDL ADD (
  CONSTRAINT PK_WSDL PRIMARY KEY (WSDL_NAME));
ALTER TABLE WSDL ADD (
  CONSTRAINT UNIQUE_WSDL_TNS UNIQUE (TARGET_NAMESPACE));


CREATE TABLE WSDL_MESSAGE
(
  WSDL_NAME             VARCHAR2(100),
  MESSAGE_NAME          VARCHAR2(100),
  DESCRIPTION           VARCHAR2(2048)
);

ALTER TABLE WSDL_MESSAGE ADD (
  CONSTRAINT PK_MESSAGE PRIMARY KEY (WSDL_NAME, MESSAGE_NAME));
ALTER TABLE WSDL_MESSAGE ADD (
  CONSTRAINT FK_MESSAGE FOREIGN KEY (WSDL_NAME) REFERENCES WSDL(WSDL_NAME));  


CREATE TABLE WSDL_MESSAGE_PART
(
  WSDL_NAME             VARCHAR2(100),
  MESSAGE_NAME          VARCHAR2(100),
  PART_TYPE             VARCHAR2(100),
  PART_TYPE_DATASOURCE  VARCHAR2(100),
  DESCRIPTION  VARCHAR2(2048)                       NULL
);

ALTER TABLE WSDL_MESSAGE_PART ADD (
  CONSTRAINT PK_MESSAGE_PART PRIMARY KEY (WSDL_NAME, MESSAGE_NAME , PART_TYPE));
ALTER TABLE WSDL_MESSAGE_PART ADD (
  CONSTRAINT FK_MESSAGE_PART FOREIGN KEY (WSDL_NAME, MESSAGE_NAME) REFERENCES WSDL_MESSAGE(WSDL_NAME, MESSAGE_NAME));


CREATE TABLE WSDL_PORT_TYPE
(
  WSDL_NAME       VARCHAR2(100),
  PORT_TYPE       VARCHAR2(100),
  DESCRIPTION     VARCHAR2(2048)
);

ALTER TABLE WSDL_PORT_TYPE ADD (
  CONSTRAINT PK_PORT_TYPE PRIMARY KEY (WSDL_NAME, PORT_TYPE));
ALTER TABLE WSDL_PORT_TYPE ADD (
  CONSTRAINT FK_PORT_TYPE FOREIGN KEY (WSDL_NAME) REFERENCES WSDL(WSDL_NAME));  


CREATE TABLE WSDL_OPERATION
(
  WSDL_NAME       VARCHAR2(100),
  PORT_TYPE       VARCHAR2(100),
  OPERATION       VARCHAR2(100),
  OPERATION_TYPE  VARCHAR2(100),
  DESCRIPTION     VARCHAR2(2048)
);

ALTER TABLE WSDL_OPERATION ADD (
  CONSTRAINT PK_OPERATION PRIMARY KEY (WSDL_NAME, PORT_TYPE, OPERATION));
ALTER TABLE WSDL_OPERATION ADD (
  CONSTRAINT FK_OPERATION FOREIGN KEY (WSDL_NAME, PORT_TYPE) REFERENCES WSDL_PORT_TYPE(WSDL_NAME, PORT_TYPE));
ALTER TABLE WSDL_OPERATION ADD 
  CONSTRAINT CHK_OPERATION_OP_TYPE CHECK ( OPERATION_TYPE IN ('INSERT', 'UPDATE', 'DELETE', 'QUERY', 'COMPOSITE'));

  
CREATE TABLE WSDL_OPERATION_MESSAGE
(
  WSDL_NAME       VARCHAR2(100),
  PORT_TYPE       VARCHAR2(100),
  OPERATION       VARCHAR2(100),
  MESSAGE_NAME    VARCHAR2(100),
  MESSAGE_TYPE    VARCHAR2(100),
  DESCRIPTION     VARCHAR2(2048)
);

ALTER TABLE WSDL_OPERATION_MESSAGE ADD (
  CONSTRAINT PK_OPERATION_MESSAGE PRIMARY KEY (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME));
ALTER TABLE WSDL_OPERATION_MESSAGE ADD 
  CONSTRAINT FK_WSDL_MESSAGE FOREIGN KEY (WSDL_NAME,MESSAGE_NAME) REFERENCES WSDL_MESSAGE(WSDL_NAME,MESSAGE_NAME); 
ALTER TABLE WSDL_OPERATION_MESSAGE ADD (
  CONSTRAINT FK_OPERATION_MESSAGE FOREIGN KEY (WSDL_NAME, PORT_TYPE, OPERATION) REFERENCES WSDL_OPERATION(WSDL_NAME, PORT_TYPE, OPERATION));
ALTER TABLE WSDL_OPERATION_MESSAGE ADD 
  CONSTRAINT CHK_OPERATION_MESSAGE_MSG_TYPE CHECK ( MESSAGE_TYPE IN ('IN', 'OUT', 'FAULT'));

CREATE TABLE WSDL_SERVICE_PORT
(
  WSDL_NAME       VARCHAR2(100),
  SERVICE_NAME    VARCHAR2(100),
  PORT_TYPE       VARCHAR2(100),
  ADDRESS_URL     VARCHAR2(2048),
  DESCRIPTION     VARCHAR2(2048)
);

ALTER TABLE WSDL_SERVICE_PORT ADD (
  CONSTRAINT PK_SERVICE_PORT PRIMARY KEY (WSDL_NAME, SERVICE_NAME, PORT_TYPE));
ALTER TABLE WSDL_SERVICE_PORT ADD (
  CONSTRAINT FK_SERVICE_PORT FOREIGN KEY (WSDL_NAME, PORT_TYPE) REFERENCES WSDL_PORT_TYPE(WSDL_NAME, PORT_TYPE));  

CREATE TABLE ENTITY_RELATIONS 
(
  ENTITY_NAME VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  DATASOURCE VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  PROPERTY_NAME VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  ENTITY_KEY_NAME VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  PROPERTY_KEY_NAME VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  PARTIAL_KEYS_FLAG VARCHAR2(1),
  CONSTRAINT PK_ENTITY_RELATIONS PRIMARY KEY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME, ENTITY_KEY_NAME) ENABLE, 
  CONSTRAINT FK_ENTITY_RELATIONS FOREIGN KEY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME) REFERENCES ENTITY_PROPERTY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME)
) ;


CREATE TABLE ENTITY_OPERATIONS
(
  WSDL_NAME VARCHAR2(100) NOT NULL,
  PORT_TYPE VARCHAR2(100) NOT NULL,
  OPERATION VARCHAR2(100) NOT NULL,
  MESSAGE_NAME VARCHAR2(100) NOT NULL,
  ENTITY_NAME VARCHAR2(100) NOT NULL,
  DATASOURCE VARCHAR2(100) NOT NULL,
  PROPERTY_NAME VARCHAR2(100) NOT NULL,
  END_OPERATION_FLAG VARCHAR2(1),
  QUERY_TEXT CLOB,
  PROCEDURE_FLAG VARCHAR2(1 BYTE),
  CONSTRAINT ENTITY_OPERATIONS_PK PRIMARY KEY (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME, ENTITY_NAME, DATASOURCE, PROPERTY_NAME)
);
 
ALTER TABLE ENTITY_OPERATIONS ADD 
  CONSTRAINT FK_WSDL_OPERATIONS FOREIGN KEY (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME) REFERENCES WSDL_OPERATION_MESSAGE(WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME);
ALTER TABLE ENTITY_OPERATIONS ADD 
  CONSTRAINT FK_ENTITY_OPERATIONS FOREIGN KEY(  ENTITY_NAME,  DATASOURCE,  PROPERTY_NAME) REFERENCES ENTITY_PROPERTY (ENTITY_NAME,DATASOURCE,PROPERTY_NAME);
  

CREATE TABLE ENTITY_MANUAL_RELATIONS 
( 
  WSDL_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  PORT_TYPE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  OPERATION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  MESSAGE_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  ENTITY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  DATASOURCE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  PROPERTY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  ENTITY_KEY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  PROPERTY_KEY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  CONSTRAINT PK_ENTITY_MANUAL_RELATIONS PRIMARY KEY (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME, ENTITY_NAME, DATASOURCE, PROPERTY_NAME, ENTITY_KEY_NAME) ENABLE, 
  CONSTRAINT FK_ENTITY_MANUAL_RELATIONS FOREIGN KEY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME, ENTITY_KEY_NAME)
    REFERENCES ENTITY_RELATIONS (ENTITY_NAME, DATASOURCE, PROPERTY_NAME, ENTITY_KEY_NAME) ENABLE, 
  CONSTRAINT FK_ENTITY_OPERATION_RELATIONS FOREIGN KEY (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME, ENTITY_NAME, DATASOURCE, PROPERTY_NAME)
    REFERENCES ENTITY_OPERATIONS (WSDL_NAME, PORT_TYPE, OPERATION, MESSAGE_NAME, ENTITY_NAME, DATASOURCE, PROPERTY_NAME) ENABLE
 ) ;
 
 CREATE TABLE ENTITY_COMPOSITE_OPERATIONS
 (
  WSDL_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  PORT_TYPE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  OPERATION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  ENTITY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  DATASOURCE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  PROPERTY_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  OPERATION_TYPE VARCHAR2(50 BYTE), 
  DESCRIPTION VARCHAR2(1000 BYTE), 
   CONSTRAINT ENTITY_COMPOSITE_OPERATIONS_PK PRIMARY KEY (WSDL_NAME, PORT_TYPE, OPERATION, ENTITY_NAME, DATASOURCE, PROPERTY_NAME) ENABLE, 
   CONSTRAINT FK_WSDL_COMPOSITE_OPERATIONS FOREIGN KEY (WSDL_NAME, PORT_TYPE, OPERATION)
    REFERENCES WSDL_OPERATION (WSDL_NAME, PORT_TYPE, OPERATION) ENABLE, 
   CONSTRAINT FK_ENTITY_COMPOSITE_OPERATIONS FOREIGN KEY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME)
    REFERENCES ENTITY_PROPERTY (ENTITY_NAME, DATASOURCE, PROPERTY_NAME) ENABLE,
   CONSTRAINT CHK_ENTITY_COMPOSITE_OP_TYPE CHECK ( OPERATION_TYPE IN ('INSERT', 'UPDATE', 'DELETE', 'QUERY')) ENABLE
 );