<?xml version="1.0" encoding="UTF-8"?><TSX>
  <project xmlMinorVersion="0" xmlVersion="32">
    <extensionsPath value="extensions.xml"/>
    <classPath value="../WEB-INF/classes"/>
    <images>
      <image id="0" type="png" value="images/marqueeZoom.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA00lEQVR42q2SIRKDMBBFuUqPge0RegWOgIytjETGIiMjsciVyFhkZOU2f6fb0ilQoM3Mzu6Q/Lc/WYrin6uLzNPwlCQ2iyneOCZ+i5ABrht5k9g4mo2vkDAk6SaHcw0YAjW+obY+rgDoBZiK1RWNzI3vlwGePh0gqwPd2wSYip8OkNthGeDyK+IaS4+I/aZx65OwIcrMdZT6FiLO9x/8lYMp1yE4CKvS+ZHRuXcVJ/JMbc2+Lnn3HxrMWSAxWMmuOu2HoHNnL79BIFInhwAKOSyeW3ejYV19bWpvrAAAAABJRU5ErkJggg==]]></image>
      <image id="1" type="png" value="images/interactivezoom.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA1UlEQVR42q2SrxKDMAzG9yp7DCyPsFfgEZC1k5XIWmRkJBYZiaxFVk5mTXbZsQ0YsPUuV/rn++VLyun0z9FF5mkAJY3NYoo3jolfAjMgdCPvEpeu17C9rxAc0od4CpHwEFcA9ADYZReIXTs81zQyN9AvA2ACEDcGkG9zJ3ubAO8lCEBdZeAiIOQu4gzEsst504T1l/AY9c2t81a/inP9A1wZXbEOkYti1Xogs2TuQ8WJgKmtGeqCd/+h6EqFRPQ6h+q8HyKZO3/5DSIic3IIYJDD4rlxB97uXXAfX7uwAAAAAElFTkSuQmCC]]></image>
      <image id="2" type="png" value="images/zoomIn.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA0ElEQVR42q2SIRKDMBBFe5UeA9sj9AocARlbGYmMRa5ciUWuRMYiIyu32Z3uNHQKFNrM/Ekm4b/92XA6/XP0kbkUUFJ9baZ455h4JsyA0E+8y+wCqWxvE4JjelXMawPIWiAiD3EFQGlW+V00MbcwLANgA2BnmwCLW/bAruG6cRkQchexgJQ9kD05b9uw/hIeo765dd7SqDnff4Qbo6vWIfKhRNUEz1kqD6HmRMDUNQxNxbv/UHQXhUT0Oof6vB8ilXt//Q0iJktyCGCQw+ZP4wHw0l8XtgzUIwAAAABJRU5ErkJggg==]]></image>
      <image id="3" type="png" value="images/zoomOut.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyklEQVR42q2SKw7DMAyGe5Udo3RH2BV6hMLQwcDC0EJDw9BCw8LQwsBBL85mLZP63iL9spXk/+w8quqfwwfmUkAxa7eZwoND5C9hAjg/8SGz5KpdEBzjp2LK1VzmFsIKgF4A42hWNDF3MCwDYAOga5uAsnVtX6Ppx2WAS7eIBaQ0y5ysd51bfwmLIb+53rx2k83p/CPcGU29DpGN0mo++ztK5cE1HAmY+pahrfnwD0VzzZCANkfXXI5DpLK3t98gYtJOTgEUcto8N541NGSMkK8K/AAAAABJRU5ErkJggg==]]></image>
      <image id="4" type="png" value="images/fitInView.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA2ElEQVR42q2SKxLDIBCGc5UeIzZH6BVyhEhsJTISG4lExkYikdhIZOWWfzuboTPNs2VmZ5eB/9sHVNU/1xiJSrM+sR0W+/ikmOjDXAaYcaZD4kZNbIjL/S7EhcTZ+HKOBYBYgNrGDYB/A0Qo4mU/E/V2WgfYAiBCeDGcKeP3AVKuCGUO8GoI6wCTp4g2lqEVYhjO+95sv4R2kd9cnlL6Z3HuP9gHOVVvQ3ARpaJf8cg8mZaSt+SHjmxX0+kf6lTDkOg0e9PezkOQedT33yAQSSWXAAK5LP62XmTiXoOxHE73AAAAAElFTkSuQmCC]]></image>
      <image id="5" type="png" value="images/overview.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABt0lEQVR42mNgIBPo9Wu3qDcrH8apoHvdw//NKy79xCXvOsXhtcN0m/+YMrEM3DNm9i4uX3x+XVDnET+QkH63VrrXCvvd/xuusgW2H20pW3j+6bRZvfcYAhnEwHpClvj+T1oS/WLt6rVLGo5U/HedZfcF2czQNd5HEraG/58+fcIvoKv+g1yHYmnu+vSH2ZsTe/Zs3KMXvzDyf9LqyD8oCvoZJGcvn/0NxGyYdTipa8Lc67hDB80L/0P/M4du8DoUMtvv354N+0OyN8WfBlr4G6teSeun/xWdn/3X9Hr+3yDo+X/LqBf/HZJe/vfIfPU/c3vC/zVr1twHevUvyMs4DYCxO/vmzqqdedgcxPYvePWfoZOBl2DcKjo9QwlMtzn2x0HhElb+GjPgsAEtn+f/kQMzdW30e5Bh8fVv/mfOW38DFDagMMJpgGHw8/8wZ89ZMec8zNlp7W//w6I7dmH4f2QXohgACjS7+Jf/3dJf/vfNe/U/tOz1/5jaN//z+yEGZKxJ+hm+1P8/sgtxRp3nCrtqnV4NK5A0SAwkh9MLoDQNTNs7cHkNlCfwBqJ6k3KzXq+2H8NAAADGqgg+rcdQGwAAAABJRU5ErkJggg==]]></image>
      <image id="6" type="png" value="images/circulardeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAw0lEQVR42mNgwAGmHPv+v2Xr+//Fa5//ZyAV9PT0gDUfO/f+f9SUa/9BfJI0g2iQRhB2qj72H1kcr3Ozl+J3rmaP5n/FasX/IBpFAt25uLDTHMv/QWu9wIagGACyGdm52LwFwoZAm0GGYBiAy48wjYTUYUhg04jXgOy9Uf9hGF9o4wxEkMat99b+7zlWjTcWcAciyOZzLUAXJOM1AG8govsxaKvXf6+lTmANBBMSNkNATp1yDhL3JGlG9i/IaxgBNugAAHtqyW6XUk8wAAAAAElFTkSuQmCC]]></image>
      <image id="7" type="png" value="images/hierarchicaldeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVR42qWSIQ/DIBCF+1cqKydrkUgkdrJyElt5ElmLRCJnkZWTs5WVk29A0qRNSGjpSy4h5O7LuwdNk5H2P4xuxcsuaGoUh/28QupPHWAwSxpmyl8HEBFy58vDm4TjEJaDmx51gDCsZwKbbgCkFXhQh9sZnM5keEtstb/vgotYrWpRBLivBc3joTHmEFfqSutEAHkVHDwPjTGHPkCKDm5nsJd0Itk+9Yw5XfoHOXHD0j/oawEl/QHST4gGXc7OgwAAAABJRU5ErkJggg==]]></image>
      <image id="8" type="png" value="images/orthogonaldeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA8klEQVR42r1SoRKDMAzdryCRSCwSicQikUjsZGXlLLISia1ETs5OTk5mvBwpYbDtbrtb7t5Bk5fX9qUH6+8EHPsbo3FXOswheZ3bBAh+XFDaMxljGFLTOQ0WqLsrEwRZ68NuezmJIKAXq+Qe8a8C9VBS4XJG3qWU2DjUYhNT1EaE70uB3GVkRxOAtZiXnVIqXcEiGwEBdpZmMx65SYujvjmBDjRIc+sbSibyxxPoSCcSiOmMxCwe4B+5twJfTeErgcZXhJEBzyTcE2ZpA/UY+Qpo7C+OzXp+6zIJCOj8agoQQHM9VJsTgIh6MEuZmGkTf4kHC99SaPEoFQ0AAAAASUVORK5CYII=]]></image>
      <image id="9" type="png" value="images/symmetricdeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvUlEQVR42r1QLQ+DMBDlryCRyNpKZGUtshKJRVYiZysrK7GVlZOzSOTkrXfJCGPL2lXsJefufVZVARrdAF491lDCr/iFgbAdiRQJtJHIokhRAq31d9Ls7zC5DQa77o/SCYrcGZZ2RLIPG8j5CuiGh+Q5aIqdFFBmJTIf/f7cGQ5qkdDmjvapZ7L7E8PSkxveeQOeVSES3c2C9uPbBtkCSFYxyXEDaUV6g+yeL519T27Hzj9h7xymcoFz57/iAdEQmsrhh+E9AAAAAElFTkSuQmCC]]></image>
      <image id="10" type="png" value="images/globalLayout.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVR42mNggIK9Tgz/GYgEGGpBAqQaAFcP45BjAFY9U459/9+y9f3/4rXP4ZJRW4P+B631+u+11JKwJSDNx869/x815dr/np4eMAZpnnKu57/lHCIMAGkEYafqY3DFXkud/mfvjfpv2KNJnDdBthIjRhsDio8lg50LwjAxTaDTFasV/2sS4wWQxq331v7vOdcCD0QnYOCBAhJkCFEGgDRn702GKwaFPghjNYAqCYmipEyVzDSgAAC1Z54JsS6ChwAAAABJRU5ErkJggg==]]></image>
      <image id="11" type="png" value="images/incrementalLayout.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyElEQVR42tWSKxODMBCE81eQyEpsJBIZWxmJxFaejKxFRkbGRiIra5HIyi1HJ0zLo+1ATW/mTOb2u80mQmwoLwXE3toNYcAixIQbTq5DaVtscsHi0HRQ5gIiGlq5AoXNkdcZZoBoJdJ03Q5iWYVxmMWmIWTnByDOjg6m9+Gtz5vyWkJ7hQOlmM3PaAuA6dmL62kQpT8O27jXAG+TZKG7WlCoxvO0t86dVAk+vicDWKx7J/EVZB8eB7kI+OZXcXgMWQX87H//Z90BLpKh7vcb0uIAAAAASUVORK5CYII=]]></image>
      <image id="12" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAeElEQVR42mNgQANTjn3/z0AJABnQs5cCQ0AGnLtGgSEgjSADQLh47fP/FBkAwlFzrpFmCMhWZANINgSbASQZgssAEA7qOfefbC/AMEFDQIqQNZIcBsiakA1zqj72n2gDkG0EOZlkA5D5MANIMgQdgDRSbADZmgkBAJUX6jjE5pZGAAAAAElFTkSuQmCC]]></image>
      <image id="13" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAApklEQVR42p2SMQ6AIAxFOZujo6NXYXXkCK6OjI5egdGR1dEjVAspKUSb6k9+bMA+flFjBLkNAG20mgMAmup4ZFt/gl2zxWZqIFAB3I1Uj3OE17gqwJIB9KyEUTmEj8AToFPt9hrCT5ISlJoAuEiR+MtPptPLffCFdNteBnB3U6gB7bxiEj5/C1EB2s+JxC+AwYX/gN6G559JO8orAIWbv5s1EBXgiy70e1lUpvzebAAAAABJRU5ErkJggg==]]></image>
      <image id="14" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVR42rWPIQ7DMAxFe50eobQwMLB0MHCwVzAsDC0MHCwNDCwMLSws9PS9eZo0bZM1zdJT1Dr/2WmmfDAtB5/TJpxi5cZSCJf1Ri47h3mzCTBVBUve7RtAgKDiqdgEWBkMcZVwP+YXARF9l366ZBbUWjmlJGgP4L/2Qwj8VoCgSrSHb72DsMr+s4Gphotjn3rBzR231LJR4Hkq9AASkwCTnwVdNArcXUB5FMxPwESsjRNhs+DXugLdO+Yx6tjD4QAAAABJRU5ErkJggg==]]></image>
      <image id="15" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuklEQVR42qWRoQ7DIBCGeZ0+Qm0lElk7OVlZO3mysraychKLRFbOVlYib/ubwNjCRkkv+QIk/T/uqCAiFlF9n7P1S4D1CH8FpzsoFgzGMSDtuJvXncv44CKBXRwbu4W1HZe8IKDfYaDNtneRfLxU4eM4DFlqhA9BbIUAwRhFNi/we9x2ndYdzI5w05vjgtxvbO+SgZobli/qseZCgeLBUkBOhQIEfJjsrbwDtO3DvenKBRVVYXbsgThbT/MgOPzyS8xRAAAAAElFTkSuQmCC]]></image>
      <image id="16" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACUklEQVR42q2T7U9ScRTH/VugtZYvbNVctVZbD2uKCHoVIkBSiMkNG62RJuMy02wrZ0OaL5paao9S8caMmLFSyzbNmpqW18ogbsGK0HtBIN03oqWxwFee7fvu9/n8ds7Oycpa7/JUVfHnSNL8nqykZzVqdkZTzr5TK+kpjcI8oZLy14S9ej3xkSSZ77ZmRAfdiE2MIjYyBK63Bx6DFuNlBDOmEBMZ4TkdyS3c68Hy7FvEXfcR77Yi3n4RP++0YWnYBb/JgFF5ATciO5Qq+aTT8RKwj73VjWV6EvEr5xGyWjDfXIvoZQtiLRSiTacR7bsN7wk1hqUHfYPEAd6/AipQb8bS5Mvkj4s2CsELRkQa9Clhz6gRdVzHa9EeDJTupVYEH0gtHXbcQNzejlBTNb6pStJmoVoNrrkOfksNnhC76BUBrdNEYo8ciNssCJ0zIFP5ZUIEyTLMt7fCLcqNrAhmNKrIor0T0UYDImcr1xQEtArMt7WiX7x1VTBdoaCDTXVYtFJgTymTD9NGLkKo3gSPyQiXIGe1hTcqKUVLBIjYuxDSSBDUFv8HM4cLwBwpRrj7KobE2+EUZK8OcbyC4L0qL/F5j5cjfLczObCAQvwHlBWCkSRgiRhcVwemjpbAmbfZ1yvYyEvZhTGZkBiR5XFzxxQI3+zEj0YKfrUcX5QyBBvM4K51YFpZhIf52dyD/E3pt/FFYsOel+5nRot342utEcGWS8l8rjmJp8Jtv2EmI/y3nkn38QfEO81uYgf9uCiX7RdsYZ2FOXSiZ3Nf3gb+ul/vL30s06FxPF6DAAAAAElFTkSuQmCC]]></image>
      <image id="17" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACJklEQVR42s2R20+SARyG2fo7vNKZ4bSVpSPMYWw6D4FlCGiEEYpC4GeBJ0DkGKGMQ7iyIYShEaDCrDA1nIjmrFZzHczuvOR/aG/gVezrorzqvf89+73PS6H8Fk6Yc4KmrRiiHDe1Vpr3oqFq71jHDa5LTlGwHTcCPNQYq3Bh9BwqR86gQlWO0/2lmTJ5SeJUbxFRKC0sIB1f8TaYpFER7DtmjL81w7ptgCWtgyGlwdjGMIZe96MrJATL1QCqtDhWIimi5QG4AZZNEeuGe9cG5+79LMgC27YR97bGYNochT6lhnJVDk1yAIInfFBlxTHSJ9xA84O+uASyeTGaPEzUOxhg2qrBMNPQPn0NIytK6LLfaNcHwXY1olR2kiBV4QbZ/lZfE0kiw0J3VOsrD9WrKgy+IdAbuYXyPmqCBMjNmIWo/ySZYaU7JKGbWS9qaNYGcFZVlvmnlersNQ5ZRHwkV58czi309wDWozpHo7v20LqphzmthWpJAbrufH4F6YoQklfXIV7io3OhDYJwK/hzLWgLXAYR74Fzx4rJ93a4341DPCsAw0TLlyhPirBwMIvo/gzC+wE8++rD7BcvZj5Pwb/3EJMfJjD10QX18t3cQrFspfwZiQ0xYj/msHgwh/nvTxHJgkLf/EeQ6U8eTGwZoXxxGy2P62PNHiaN1PNOuhtESgzFugiytU70LAvQ9bIDojjvpzDKyXQ8v5rgB1sIno9dQPmv8gswHyvgpr1YNgAAAABJRU5ErkJggg==]]></image>
      <image id="18" type="png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACKUlEQVR42q2T3U/ScRjF3fo7aJWl0+ksZwGLsEnD8o2YEiYzgSUFpP18AXlTnEEqxnhHUQSC0nJtYeWQgTlc1mYMAq3uveR/aKfvvGN4UdZz++x89pxz9pSV/c9hm9i0a1N0ijneELuivVioV9X+qqOqUfOoElXyC6joP4dy6Rmc7TuNEvFNG4fJtbKj4kgPqHUFDEkVxrc1MHxUQ7s1irHkEEYTFEbiAzhPIEViXoBL65jnRtUbg5j7YoYxpcHTT0ZM7RgwmdJiYnsMOgLRbA1DRSCVsvJigDDcTlHvHsL1dQ72vVmYUxMQh++i0czA1cnLYOjr0TBWh0sjNagdrEK1sqIYIFrhx6Z3jEQ8jWefzWhxcw6bbddtfxzevTddhYWMHb6sA7r4MG77mm1/lb50vbvgz7kRyHlgTKrRFWw9FsB6wtALBIJTJQvZhijmSluwnHNhMeNA9wve4Z1QewmkaYaVbzTRgyUA+WYvZdrVYfVHAC+/+7GYdUK9OQBBqA18/y2QhtDibML9lV5ISM1sE8NVBFDEJTRFXBx1pmfw+mcIoX0vIgdLeL7vI7a8WMq64CMZedJWOPYskEZEpCG6pQiiTEqZioQ4at7Vw5uxEvHC0TXhAx+C+Xksf3MfhewmkAev+nBjlmUqsaJISWjKhJgilmL9H3oK0qgQpCGIVvkQRjow9F6Ox29laPNw7Cf6FWGEl+8MtvpP/GyitU6NYO2YGv9lfgO9Li3+2CE2YgAAAABJRU5ErkJggg==]]></image>
    </images>
    <module tags="Flow, SubProcess, Sequence">
      <schema name="Process">
        <attributeTypes>
          <attributeType identifier="true" name="Name">
            <type name="StringValue"/>
          </attributeType>
          <attributeType identifier="true" name="Id">
            <type name="StringValue"/>
          </attributeType>
        </attributeTypes>
        <modelElementTypes>
          <modelElementType name="Flow">
            <attributeTypes>
              <attributeType identifier="true" name="Id">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Type">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Name">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Label">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Parent">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Loop">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="ExtendedType">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="TextValue">
                <type name="StringValue"/>
              </attributeType>
            </attributeTypes>
          </modelElementType>
          <modelElementType name="Sequence">
            <attributeTypes>
              <attributeType identifier="true" name="Id">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="From">
                <type name="ReferenceValue">
                  <elementTypeName value="Flow"/>
                  <attributeTypeName value="Id"/>
                </type>
              </attributeType>
              <attributeType identifier="false" name="To">
                <type name="ReferenceValue">
                  <elementTypeName value="Flow"/>
                  <attributeTypeName value="Id"/>
                </type>
              </attributeType>
              <attributeType identifier="false" name="Label">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Type">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="IsDefault">
                <type name="BooleanValue"/>
              </attributeType>
            </attributeTypes>
          </modelElementType>
        </modelElementTypes>
      </schema>
      <drawingTemplates>
        <drawingTemplate name="Process">
          <template name="Task" parentTemplate="" type="Node">
            <uiProperties uiType="Tasks.Task">
              <property name="Resizability" value="16777216"/>
              <property name="Width"/>
              <property name="Height"/>
              <property name="Expanded Resizability" value="16777216"/>
              <property name="Tooltip" value="Name:&lt;Id&gt;&#10;Label:&lt;Label&gt;&#10;Type:&lt;Type&gt;"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Sequence" parentTemplate="" type="Edge">
            <uiProperties uiType="Edges.Sequence"/>
            <uiAttributes>
              <attribute name="Target_Head" value="2"/>
              <attribute name="Target_Arrow_Width" value="3"/>
              <attribute name="Target_Arrow_Height" value="2"/>
              <attribute name="Thickness" value="0"/>
              <attribute name="Show_Bend_Points" value="false"/>
            </uiAttributes>
          </template>
          <template name="FlowNodeLabel" parentTemplate="" type="Node Label">
            <uiProperties uiType="Node Label.Custom Node Label">
              <property name="Width" value="35"/>
              <property name="Constant Y Offset" value="0"/>
              <property name="Proportional Y Offset" value="-1.5"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Start Event" parentTemplate="" type="Node">
            <uiProperties uiType="Start Events.Start"/>
            <uiAttributes/>
          </template>
          <template name="End Event" parentTemplate="" type="Node">
            <uiProperties uiType="End Events.End">
              <property name="Precise Shape Clipping" value="true"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Note" parentTemplate="" type="Node">
            <uiProperties uiType="General.Note">
              <property name="Width" value="60"/>
              <property name="Height" value="25"/>
              <property name="Name" value="&lt;TextValue&gt;"/>
              <property name="Editable" value="true"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Association" parentTemplate="" type="Edge">
            <uiProperties uiType="Edges.Association"/>
            <uiAttributes>
              <attribute name="Color" value="0 0 0"/>
            </uiAttributes>
          </template>
          <template name="Exclusive Gateway" parentTemplate="" type="Node">
            <uiProperties uiType="Gateways.Exclusive">
              <property name="Resizability" value="16777216"/>
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Color Enabled" value="true"/>
              <attribute name="Background Color" value="255 204 102"/>
              <attribute name="Border Color" value="255 204 102"/>
            </uiAttributes>
          </template>
          <template name="Message Start" parentTemplate="" type="Node">
            <uiProperties uiType="Start Events.Message Start">
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
              <property name="Resizability" value="16777216"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Finish Color" value="255 255 255"/>
              <attribute name="Gradient Start Color" value="255 255 255"/>
              <attribute name="Gradient Color Enabled" value="true"/>
            </uiAttributes>
          </template>
          <template name="Message End" parentTemplate="" type="Node">
            <uiProperties uiType="End Events.Message End">
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
              <property name="Resizability" value="16777216"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Signal End" parentTemplate="" type="Node">
            <uiProperties uiType="End Events.Signal End">
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
              <property name="Resizability" value="16777216"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Border Color" value="255 153 0"/>
            </uiAttributes>
          </template>
          <template name="Signal Start" parentTemplate="" type="Node">
            <uiProperties uiType="Start Events.Signal Start">
              <property name="Resizability" value="16777216"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Start Color" value="255 255 255"/>
              <attribute name="Gradient Finish Color" value="255 255 255"/>
            </uiAttributes>
          </template>
          <template name="Parallel Gateway" parentTemplate="" type="Node">
            <uiProperties uiType="Gateways.Parallel">
              <property name="Resizability" value="16777216"/>
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Border Color" value="255 204 102"/>
            </uiAttributes>
          </template>
          <template name="Error End" parentTemplate="" type="Node">
            <uiProperties uiType="End Events.Error End">
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
              <property name="Shape" value="Ellipse"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Border Width" value="5"/>
              <attribute name="Gradient Color Enabled" value="false"/>
            </uiAttributes>
          </template>
          <template name="Call Activity" parentTemplate="" type="Node">
            <uiProperties uiType="Tasks.Call Activity">
              <property name="Width"/>
              <property name="Height"/>
              <property name="Resizability" value="16777216"/>
              <property name="Expanded Resizability" value="16777216"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Start Color" value="255 255 255"/>
              <attribute name="Gradient Finish Color" value="255 255 255"/>
              <attribute name="Border Width" value="1"/>
            </uiAttributes>
          </template>
          <template name="Timer Start" parentTemplate="" type="Node">
            <uiProperties uiType="Start Events.Timer Start">
              <property name="Width" value="20"/>
              <property name="Height" value="20"/>
              <property name="Resizability" value="16777216"/>
              <property name="Precise Shape Clipping" value="false"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Color Enabled" value="false"/>
              <attribute name="Gradient Finish Color" value="255 153 0"/>
              <attribute name="Gradient Start Color" value="255 153 0"/>
            </uiAttributes>
          </template>
          <template name="Standard Loop" parentTemplate="" type="Node">
            <uiProperties uiType="Loops.Standard">
              <property name="Resizability" value="16777216"/>
              <property name="Width"/>
              <property name="Height"/>
            </uiProperties>
            <uiAttributes>
              <attribute name="Gradient Color Enabled" value="false"/>
            </uiAttributes>
          </template>
          <template name="MultiInstance Loop" parentTemplate="" type="Node">
            <uiProperties uiType="Loops.MultiInstance">
              <property name="Resizability" value="16777216"/>
              <property name="Width"/>
              <property name="Height"/>
              <property name="Expanded Resizability" value="16777216"/>
              <property name="Tooltip" value="Name:&lt;Id&gt;&#10;Label:&lt;Label&gt;&#10;Type:&lt;Type&gt;"/>
            </uiProperties>
            <uiAttributes/>
          </template>
          <template name="Default Edge" parentTemplate="" type="Edge">
            <uiProperties uiType="Edges.Default Sequence"/>
            <uiAttributes>
              <attribute name="Target_Head" value="2"/>
              <attribute name="Target_Arrow_Width" value="3"/>
              <attribute name="Target_Arrow_Height" value="2"/>
              <attribute name="Thickness" value="0"/>
            </uiAttributes>
          </template>
        </drawingTemplate>
      </drawingTemplates>
      <views>
        <drawingView name="View">
          <mapping>
            <modelRules>
              <rule>
                <actions>
                  <setDrawingLayoutPropertiesAction description="Set Drawing Layout Properties" id="$rootDrawing()">
                    <actionList>
                      <setOptionAction optionName="layout:hierarchical:graph:constantVerticalSpacingBetweenNodes" value="14"/>
                      <setOptionAction optionName="layout:hierarchical:graph:constantHorizontalSpacingBetweenNodes" value="14"/>
                      <setOptionAction optionName="layout:hierarchical:graph:levelDirection" value="DIRECTION_LEFT_TO_RIGHT"/>
                      <setOptionAction optionName="layout:all:graph:componentConstantSpacing" value="15"/>
                      <setOptionAction optionName="layout:all:graph:disconnectedNodesConstantSpacing" value="15"/>
                    </actionList>
                  </setDrawingLayoutPropertiesAction>
                </actions>
              </rule>
            </modelRules>
            <modelElementRules>
              <rule elementTypeName="Graph">
                <actions>
                  <addChildDrawingAction description="Add Child Drawing" id="drawing.Graph.&lt;ID&gt;" parent="node.Node.&lt;ID&gt;" tags="Graph"/>
                  <expandCollapseAction description="Expand Node" expanded="true" id="node.Node.&lt;ID&gt;" synchronize="false"/>
                </actions>
              </rule>
              <rule elementTypeName="Sequence">
                <actions>
                  <ifAction>
                    <equalsCondition comparisonType="String" valueID1="SequenceFlow" valueID2="&lt;Type&gt;"/>
                    <actionList>
                      <ifAction>
                        <unaryCondition valueID1="&lt;IsDefault&gt;" valueID2="true"/>
                        <actionList>
                          <addEdgeAction description="Add Edge" id="edge.Edge.&lt;Id&gt;" source="node.Flow.&lt;From&gt;" tags="" target="node.Flow.&lt;To&gt;" templateName="Default Edge"/>
                        </actionList>
                        <elseActionList>
                          <addEdgeAction description="Add Edge" id="edge.Edge.&lt;Id&gt;" source="node.Flow.&lt;From&gt;" tags="" target="node.Flow.&lt;To&gt;" templateName="Sequence"/>
                        </elseActionList>
                      </ifAction>
                    </actionList>
                    <elseActionList>
                      <addEdgeAction description="Add Edge" id="edge.Edge.&lt;Id&gt;" source="node.Flow.&lt;From&gt;" tags="" target="node.Flow.&lt;To&gt;" templateName="Association"/>
                    </elseActionList>
                  </ifAction>
                </actions>
              </rule>
              <rule elementTypeName="Flow">
                <actions>
                  <ifAction>
                    <notCondition>
                      <equalsCondition comparisonType="String" valueID1="Main_Display_Graph" valueID2="&lt;Parent&gt;"/>
                    </notCondition>
                    <actionList>
                      <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Task"/>
                      <addChildDrawingAction description="Add Child Drawing" id="drawing.Flow.&lt;Id&gt;" parent="node.Flow.&lt;Id&gt;" tags="Flow"/>
                      <setParentDrawingAction description="Transfer Node To Drawing" nodeID="node.Flow.&lt;Id&gt;" parent="drawing.Flow.&lt;Id&gt;"/>
                      <setDrawingLayoutPropertiesAction description="Set Drawing Layout Properties" id="drawing.Flow.&lt;Id&gt;">
                        <actionList>
                          <setOptionAction optionName="layout:all:graph:layoutStyle" value="LAYOUT_STYLE_SYMMETRIC"/>
                        </actionList>
                      </setDrawingLayoutPropertiesAction>
                      <expandCollapseAction description="Expand Node" expanded="false" id="node.Flow.&lt;Id&gt;" synchronize="false"/>
                      <setDrawingPropertiesAction description="Set Drawing Properties" id="drawing.Flow.&lt;Id&gt;"/>
                    </actionList>
                    <elseActionList>
                      <ifAction>
                        <equalsCondition comparisonType="String" valueID1="CallActivity" valueID2="&lt;Type&gt;"/>
                        <actionList>
                          <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Call Activity"/>
                        </actionList>
                        <elseActionList>
                          <ifAction>
                            <equalsCondition comparisonType="String" valueID1="ExclusiveGateway" valueID2="&lt;Type&gt;"/>
                            <actionList>
                              <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Exclusive Gateway"/>
                            </actionList>
                            <elseActionList>
                              <ifAction>
                                <equalsCondition comparisonType="String" valueID1="ParallelGateway" valueID2="&lt;Type&gt;"/>
                                <actionList>
                                  <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Parallel Gateway"/>
                                </actionList>
                                <elseActionList>
                                  <ifAction>
                                    <equalsCondition comparisonType="String" valueID1="ErrorEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                    <actionList>
                                      <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Error End"/>
                                    </actionList>
                                    <elseActionList>
                                      <ifAction>
                                        <equalsCondition comparisonType="String" valueID1="TimerEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                        <actionList>
                                          <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Timer Start"/>
                                        </actionList>
                                        <elseActionList>
                                          <ifAction>
                                            <andCondition>
                                              <equalsCondition comparisonType="String" valueID1="StartEvent" valueID2="&lt;Type&gt;"/>
                                              <equalsCondition comparisonType="String" valueID1="MessageEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                            </andCondition>
                                            <actionList>
                                              <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Message Start"/>
                                            </actionList>
                                            <elseActionList>
                                              <ifAction>
                                                <andCondition>
                                                  <equalsCondition comparisonType="String" valueID1="StartEvent" valueID2="&lt;Type&gt;"/>
                                                  <equalsCondition comparisonType="String" valueID1="SignalEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                                </andCondition>
                                                <actionList>
                                                  <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Signal Start"/>
                                                </actionList>
                                                <elseActionList>
                                                  <ifAction>
                                                    <andCondition>
                                                      <equalsCondition comparisonType="String" valueID1="StartEvent" valueID2="&lt;Type&gt;"/>
                                                      <unaryCondition valueID1="&lt;ExtendedType&gt;"/>
                                                    </andCondition>
                                                    <actionList>
                                                      <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Start Event"/>
                                                    </actionList>
                                                    <elseActionList>
                                                      <ifAction>
                                                        <andCondition>
                                                          <equalsCondition comparisonType="String" valueID1="EndEvent" valueID2="&lt;Type&gt;"/>
                                                          <unaryCondition valueID1="&lt;ExtendedType&gt;"/>
                                                        </andCondition>
                                                        <actionList>
                                                          <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="End Event"/>
                                                        </actionList>
                                                        <elseActionList>
                                                          <ifAction>
                                                            <andCondition>
                                                              <equalsCondition comparisonType="String" valueID1="EndEvent" valueID2="&lt;Type&gt;"/>
                                                              <equalsCondition comparisonType="String" valueID1="MessageEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                                            </andCondition>
                                                            <actionList>
                                                              <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Message End"/>
                                                            </actionList>
                                                            <elseActionList>
                                                              <ifAction>
                                                                <andCondition>
                                                                  <equalsCondition comparisonType="String" valueID1="EndEvent" valueID2="&lt;Type&gt;"/>
                                                                  <equalsCondition comparisonType="String" valueID1="SignalEventDefinition" valueID2="&lt;ExtendedType&gt;"/>
                                                                </andCondition>
                                                                <actionList>
                                                                  <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Signal End"/>
                                                                </actionList>
                                                                <elseActionList>
                                                                  <ifAction>
                                                                    <equalsCondition comparisonType="String" valueID1="TextAnnotation" valueID2="&lt;Type&gt;"/>
                                                                    <actionList>
                                                                      <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Note"/>
                                                                    </actionList>
                                                                    <elseActionList>
                                                                      <ifAction>
                                                                        <equalsCondition comparisonType="String" valueID1="StandardLoopCharacteristics" valueID2="&lt;Loop&gt;"/>
                                                                        <actionList>
                                                                          <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Standard Loop"/>
                                                                        </actionList>
                                                                        <elseActionList>
                                                                          <ifAction>
                                                                            <equalsCondition comparisonType="String" valueID1="MultiInstanceLoopCharacteristics" valueID2="&lt;Loop&gt;"/>
                                                                            <actionList>
                                                                              <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="MultiInstance Loop"/>
                                                                            </actionList>
                                                                            <elseActionList>
                                                                              <addNodeAction description="Add Node" id="node.Flow.&lt;Id&gt;" tags="Flow" templateName="Task"/>
                                                                            </elseActionList>
                                                                          </ifAction>
                                                                        </elseActionList>
                                                                      </ifAction>
                                                                    </elseActionList>
                                                                  </ifAction>
                                                                </elseActionList>
                                                              </ifAction>
                                                            </elseActionList>
                                                          </ifAction>
                                                        </elseActionList>
                                                      </ifAction>
                                                    </elseActionList>
                                                  </ifAction>
                                                </elseActionList>
                                              </ifAction>
                                            </elseActionList>
                                          </ifAction>
                                        </elseActionList>
                                      </ifAction>
                                    </elseActionList>
                                  </ifAction>
                                </elseActionList>
                              </ifAction>
                            </elseActionList>
                          </ifAction>
                        </elseActionList>
                      </ifAction>
                    </elseActionList>
                  </ifAction>
                  <ifAction>
                    <equalsCondition comparisonType="String" valueID1="Main_Display_Graph" valueID2="&lt;Parent&gt;"/>
                    <actionList>
                      <setParentDrawingAction description="Transfer Node To Drawing" nodeID="node.Flow.&lt;Id&gt;" parent="$rootDrawing()"/>
                    </actionList>
                  </ifAction>
                  <setNodePropertiesAction description="Set Node Properties" id="node.Flow.&lt;Id&gt;">
                    <actionList>
                      <setTooltipAction tooltip="Name:&lt;Id&gt;&#10;Label:&lt;Label&gt;&#10;Type:&lt;Type&gt;"/>
                    </actionList>
                  </setNodePropertiesAction>
                  <ifAction>
                    <notCondition>
                      <containsCondition valueID1="TextAnnotation" valueID2="&lt;Type&gt;"/>
                    </notCondition>
                    <actionList>
                      <addNodeLabelAction description="Add Node Label" id="nodeLabel.Flow.&lt;Id&gt;" parent="node.Flow.&lt;Id&gt;" tags="" templateName="FlowNodeLabel" text="&lt;Label&gt;"/>
                      <setNodeLabelLayoutPropertiesAction description="Set Node Label Layout Properties" id="nodeLabel.Flow.&lt;Id&gt;">
                        <actionList>
                          <setOptionAction optionName="labeling:all:nodeLabel:region" value="NODE_LABEL_REGION_BELOW"/>
                        </actionList>
                      </setNodeLabelLayoutPropertiesAction>
                      <applyNodeLabelTemplateAction description="Apply Node Label Template" id="nodeLabel.Flow.&lt;Id&gt;" templateName="FlowNodeLabel"/>
                    </actionList>
                  </ifAction>
                </actions>
              </rule>
            </modelElementRules>
          </mapping>
          <behavior>
            <toolbar embedded="true" floatable="false" location="North" minimumHeight="21" minimumWidth="0" name="Default">
              <actionItem action="Tool.Activate Tool" mnemonic="M" resource="0" tags="GLOBAL_TAG" text="Marquee Zoom">
                <disabledIcon/>
                <customization>
                  <tool name="Marquee Zoom Tool"/>
                </customization>
              </actionItem>
              <actionItem action="Tool.Activate Tool" mnemonic="Z" resource="1" tags="GLOBAL_TAG" text="Interactive Zoom">
                <disabledIcon/>
                <customization>
                  <tool name="Interactive Zoom Tool"/>
                </customization>
              </actionItem>
              <actionItem action="View.Zoom In" mnemonic="n" resource="2" tags="GLOBAL_TAG" text="Zoom In">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="View.Zoom Out" mnemonic="t" resource="3" tags="GLOBAL_TAG" text="Zoom Out">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="View.Zoom Fit" mnemonic="F" resource="4" tags="GLOBAL_TAG" text="Zoom Fit">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="View.Overview" mnemonic="v" resource="5" tags="GLOBAL_TAG" text="Overview">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.Circular Layout" mnemonic="C" resource="6" tags="GLOBAL_TAG" text="Circular Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Hierarchical Layout" mnemonic="H" resource="7" tags="GLOBAL_TAG" text="Hierarchical Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Orthogonal Layout" mnemonic="O" resource="8" tags="GLOBAL_TAG" text="Orthogonal Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Symmetric Layout" mnemonic="S" resource="9" tags="GLOBAL_TAG" text="Symmetric Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.Global Layout" mnemonic="G" resource="10" tags="GLOBAL_TAG" text="Global Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Incremental Layout" mnemonic="I" resource="11" tags="GLOBAL_TAG" text="Incremental Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Tool.Activate Tool" resource="12" tags="GLOBAL_TAG" text="Select">
                <disabledIcon/>
                <customization>
                  <tool name="Select Tool"/>
                </customization>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Tool.Activate Tool" resource="13" tags="GLOBAL_TAG" text="Pan">
                <disabledIcon/>
                <customization>
                  <tool name="Pan Tool"/>
                </customization>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.Labeling" resource="14" tags="GLOBAL_TAG" text="Labeling">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.All Edge Routing" resource="15" tags="GLOBAL_TAG" text="All Edge Routing">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Process Action.Delete" resource="16" tags="GLOBAL_TAG" text="Delete" tooltip="Delete">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Process Action.Undo" resource="17" tags="GLOBAL_TAG" text="Undo" tooltip="Undo">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Process Action.Redo" resource="18" tags="GLOBAL_TAG" text="Redo" tooltip="Redo">
                <disabledIcon/>
                <customization/>
              </actionItem>
            </toolbar>
            <contextMenu/>
            <toolConfiguration>
              <tool name="Select Tool" type="SelectTool">
                <customization>
                  <moveChildTool name="Move Tool"/>
                  <resizeChildTool name="Resize Tool"/>
                  <deleteChildTool name="Delete Tool"/>
                  <editTextChildTool name="Edit Text Tool"/>
                  <reconnectChildTool name="Reconnect Tool"/>
                </customization>
              </tool>
              <tool name="Move Tool" type="MoveTool"/>
              <tool name="Resize Tool" type="ResizeTool"/>
              <tool name="Delete Tool" type="DeleteTool">
                <customization>
                  <toolRules>
                    <rule name="Rule #1">
                      <trueCondition/>
                      <actions/>
                    </rule>
                  </toolRules>
                </customization>
              </tool>
              <tool name="Edit Text Tool" type="EditTextTool"/>
              <tool name="Reconnect Tool" type="ReconnectTool"/>
              <tool name="Pan Tool" type="PanTool"/>
              <tool name="Marquee Zoom Tool" type="MarqueeZoomTool"/>
              <tool name="Interactive Zoom Tool" type="InteractiveZoomTool"/>
              <tool name="Link Navigation Tool" type="LinkNavigationTool"/>
              <tool name="Create New Flow Node" type="AtTool">
                <customization>
                  <toolRules>
                    <rule name="Rule #1">
                      <trueCondition/>
                      <actions>
                        <customAction name="Create New Flow Element"/>
                      </actions>
                    </rule>
                  </toolRules>
                </customization>
              </tool>
              <tool name="Create New Flow Edge" type="BetweenTool">
                <customization>
                  <toolRules>
                    <rule name="Rule #1">
                      <trueCondition/>
                      <actions>
                        <customAction name="Create New Connection Element"/>
                      </actions>
                    </rule>
                  </toolRules>
                </customization>
              </tool>
            </toolConfiguration>
          </behavior>
          <preferences>
            <preference name="layoutOnModelChanges" value="None"/>
            <preference name="layoutOnIntegratorUpdates" value="Global"/>
            <preference name="interactive:showLayoutProgress" value="true"/>
            <preference name="interactive:layoutPreserveFocus" value="false"/>
            <preference name="interactive:layoutDrawingFitting" value="Fit To Canvas"/>
            <preference name="animation:layoutInterpolationAnimation" value="true"/>
            <preference name="animation:layoutFadeAnimation" value="true"/>
            <preference name="animation:layoutAnimationDuration" value="Low"/>
            <preference name="animation:focusToHighlightedAnimation" value="false"/>
            <preference name="animation:focusToHighlightedAnimationDuration" value="Medium"/>
            <preference name="rendering:selectColor" value="255 255 255 64"/>
            <preference name="interactive:tooltipInitialDelay" value="800"/>
            <preference name="interactive:tooltipDuration" value="4000"/>
            <preference name="interactive:tooltipDynamicRetrieval" value="true"/>
            <preference name="webGraphics" value="Image Map"/>
            <preference name="rendering:refreshInterval" value="0.0"/>
            <preference name="rendering:blinkInterval" value="0.0"/>
            <preference name="rendering:simplifiedLowResolutionDrawing" value="true"/>
            <preference name="rendering:drawNodesBeforeEdges" value="true"/>
            <preference name="initiallySelectedTool" value="Select Tool"/>
            <preference name="interactive:expandedNodeInteraction" value="Entire Node"/>
            <preference name="interactive:mouseWheelBehavior" value="Zoom"/>
            <preference name="overviewWidth" value="185"/>
            <preference name="overviewHeight" value="165"/>
            <preference name="overviewEmbedded" value="true"/>
            <preference name="overviewShowOnStart" value="false"/>
            <preference name="overviewTightFitDrawing" value="true"/>
            <preference name="overviewPlacement" value="Bottom Right"/>
            <preference name="overviewClosable" value="true"/>
            <preference name="interactive:layoutCancelDelay" value="1500"/>
            <preference name="animation:viewportChangeAnimation" value="true"/>
            <preference name="animation:viewportChangeAnimationDuration" value="Low"/>
            <preference name="showScrollControl" value="true"/>
            <preference name="showZoomControl" value="true"/>
            <preference name="navigatePlacement" value="Top Right"/>
            <preference name="animation:navigate" value="true"/>
            <preference name="animation:navigateDuration" value="Medium"/>
            <preference name="viewingTool:hoverEffects" value="false"/>
            <preference name="interactive:hoverInitialDelay" value="250"/>
            <preference name="rendering:hoverColor" value="255 255 255 64"/>
            <preference name="editingCommand:ignoreEdgeDirection" value="false"/>
            <preference name="editingCommand:compressMetaEdges" value="true"/>
            <preference name="editingCommand:enableMetaEdges" value="true"/>
            <preference name="editingCommand:applyGeometricAdjustment" value="true"/>
            <preference name="minimumZoomPercent" value="0.1"/>
            <preference name="maximumZoomPercent" value="5000.0"/>
            <preference name="viewingTool:interactiveZoomReversedDirection" value="false"/>
            <preference name="uiZoomLevelThresholds" value="100%"/>
            <preference name="highlightedTags" value=""/>
            <preference name="rendering:highlightColor" value="255 255 255 64"/>
            <preference name="focusToHighlightedObjects" value="false"/>
          </preferences>
          <drawingTemplate name="Process"/>
        </drawingView>
      </views>
    </module>
  </project>
</TSX>
