//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 12:17:12 PM IST 
//


package com.tibco.cep.bemm.common.audit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.cep.bemm.common.audit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PeformedBy_QNAME = new QName("", "peformedBy");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Entity_QNAME = new QName("", "entity");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _PerformedOn_QNAME = new QName("", "performedOn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.cep.bemm.common.audit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuditRecord }
     * 
     */
    public AuditRecord createAuditRecord() {
        return new AuditRecord();
    }

    /**
     * Create an instance of {@link AuditRecords }
     * 
     */
    public AuditRecords createAuditRecords() {
        return new AuditRecords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "peformedBy")
    public JAXBElement<String> createPeformedBy(String value) {
        return new JAXBElement<String>(_PeformedBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entity")
    public JAXBElement<String> createEntity(String value) {
        return new JAXBElement<String>(_Entity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "performedOn")
    public JAXBElement<XMLGregorianCalendar> createPerformedOn(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PerformedOn_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
