/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.service.channel.validation;

import com.tibco.cep.designtime.core.model.service.channel.Choice;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.service.channel.ChoiceConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChoiceConfigurationValidator {
	boolean validate();

	boolean validatePropertyName(String value);
	boolean validatePropertyParent(String value);
	boolean validateConfigType(String value);
	boolean validateChoices(EList<Choice> value);
	boolean validateDefaultValue(Object value);
	boolean validateDisplayName(String value);
}
