/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.service.channel.validation;

import com.tibco.cep.designtime.core.model.PropertyMap;

import com.tibco.cep.designtime.core.model.service.channel.DriverConfig;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.service.channel.Destination}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DestinationValidator {
	boolean validate();

	boolean validateEventURI(String value);
	boolean validateSerializerDeserializerClass(String value);
	boolean validateProperties(PropertyMap value);
	boolean validateDriverConfig(DriverConfig value);
	boolean validateInputEnabled(boolean value);
	boolean validateOutputEnabled(boolean value);
}
