/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.service.channel.validation;


/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.service.channel.PropertyDescriptor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyDescriptorValidator {
	boolean validate();

	boolean validateDefaultValue(String value);
	boolean validateName(String value);
	boolean validatePattern(String value);
	boolean validateType(String value);
	boolean validateMandatory(boolean value);
	boolean validateDisplayName(String value);
}
