//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 03:19:48 PM IST 
//


package com.tibco.cep.bemm.monitoring.metric.config.attrmapconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mappings" type="{http://www.tibco.com/cep/bemm/monitoring/metric/config/attrmapconfig}AttrMappings"/>
 *         &lt;element name="actions" type="{http://www.tibco.com/cep/bemm/monitoring/metric/config/attrmapconfig}Actions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schema" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cube" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hierarchy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dimLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="healthParam" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="healthEntity" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entity", propOrder = {
    "mappings",
    "actions"
})
public class Entity {

    @XmlElement(required = true)
    protected AttrMappings mappings;
    @XmlElement(required = true)
    protected Actions actions;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String agentType;
    @XmlAttribute(name = "index")
    protected Integer index;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "schema", required = true)
    protected String schema;
    @XmlAttribute(name = "cube", required = true)
    protected String cube;
    @XmlAttribute(name = "hierarchy", required = true)
    protected String hierarchy;
    @XmlAttribute(name = "dimLevel", required = true)
    protected String dimLevel;
    @XmlAttribute(name = "healthParam")
    protected String healthParam;
    @XmlAttribute(name = "healthEntity", required = true)
    protected String healthEntity;

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link AttrMappings }
     *     
     */
    public AttrMappings getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrMappings }
     *     
     */
    public void setMappings(AttrMappings value) {
        this.mappings = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link Actions }
     *     
     */
    public Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actions }
     *     
     */
    public void setActions(Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the cube property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCube() {
        return cube;
    }

    /**
     * Sets the value of the cube property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCube(String value) {
        this.cube = value;
    }

    /**
     * Gets the value of the hierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHierarchy() {
        return hierarchy;
    }

    /**
     * Sets the value of the hierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHierarchy(String value) {
        this.hierarchy = value;
    }

    /**
     * Gets the value of the dimLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimLevel() {
        return dimLevel;
    }

    /**
     * Sets the value of the dimLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimLevel(String value) {
        this.dimLevel = value;
    }

    /**
     * Gets the value of the healthParam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthParam() {
        return healthParam;
    }

    /**
     * Sets the value of the healthParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthParam(String value) {
        this.healthParam = value;
    }

    /**
     * Gets the value of the healthEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthEntity() {
        return healthEntity;
    }

    /**
     * Sets the value of the healthEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthEntity(String value) {
        this.healthEntity = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	public String getAgentType() {
		return agentType;
	}

    /**
     * Sets the value of the Agent Type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */	
	public void setAgentType(String value) {
        this.agentType = value;
    }

}
