apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bediscovery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        dep_name: "bediscovery-label"
    spec:
      containers:
      - name: bediscovery-container
        image: "<aws-registry>/<be-appimage:tag>"
        env:
        - name: PU
          value: "cache"
        - name: DOCKER_HOST
          value: "bejmx-service.default.svc.cluster.local"
        volumeMounts:
        - mountPath: "/opt/tibco/be/5.6/rms/shared/"
          name: shared
        - mountPath: "/opt/tibco/be/5.6/rms/config/security/"
          name: security
        - mountPath: "/opt/tibco/be/5.6/examples/standard/WebStudio/"
          name: webstudio
        - mountPath: "/opt/tibco/be/5.6/rms/config/notify/"
          name: notify
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: efs-shared
        - name: security
          persistentVolumeClaim:
            claimName: efs-security
        - name: webstudio
          persistentVolumeClaim:
            claimName: efs-webstudio
        - name: notify
          persistentVolumeClaim:
            claimName: efs-notify		  
