package com.tibco.cep.bpmn.model.designtime.metamodel;

import com.tibco.xml.data.primitive.ExpandedName;

/**
**	Generated on 2014.09.09 AD at 02:48:50 IST
**	by BpmnMetaModelInterfaceGenerator
**
**/

public interface BpmnMetaModelExtensionConstants { 

	public static final String EXTENSION_ATTRIBUTE_NAME = "data"; //$NON-NLS-1$
	public static ExpandedName EXTN_PROCESS_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process","ExtnProcessData");	//$NON-NLS-1$
	public static ExpandedName EXTN_LANE_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process","ExtnLaneData");	//$NON-NLS-1$
	public static ExpandedName EXTN_ACTIVITY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnActivityData");	//$NON-NLS-1$
	public static ExpandedName EXTN_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SERVICE_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnServiceTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_RULE_FUNCTION_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnRuleFunctionTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_BUSINESS_RULE_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnBusinessRuleTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_INFERENCE_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnInferenceTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_CALL_ACTIVITY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnCallActivityData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SUB_PROCESS_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnSubProcessData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SEND_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnSendTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_RECEIVE_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnReceiveTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_VRFIMPL_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnVRFImplData");	//$NON-NLS-1$
	public static ExpandedName EXTN_MANUAL_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnManualTaskData");	//$NON-NLS-1$
	public static ExpandedName ENUM_WS_BINDING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","WS_BINDING");	//$NON-NLS-1$
	public static ExpandedName ENUM_WS_BINDING_HTTP = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities/WS_BINDING","HTTP");	//$NON-NLS-1$
	public static ExpandedName ENUM_WS_BINDING_JMS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities/WS_BINDING","JMS");	//$NON-NLS-1$
	public static ExpandedName EXTN_JMS_CONFIG_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnJmsConfigData");	//$NON-NLS-1$
	public static ExpandedName ENUM_MESSAGE_FORMAT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","MESSAGE_FORMAT");	//$NON-NLS-1$
	public static ExpandedName ENUM_MESSAGE_FORMAT_BYTES = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities/MESSAGE_FORMAT","BYTES");	//$NON-NLS-1$
	public static ExpandedName ENUM_MESSAGE_FORMAT_TEXT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities/MESSAGE_FORMAT","TEXT");	//$NON-NLS-1$
	public static ExpandedName EXTN_JMS_CONTEXT_PARAMETER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnJmsContextParameter");	//$NON-NLS-1$
	public static ExpandedName EXTN_TIMER_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnTimerTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_HTTP_SSL_CONFIG = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnHttpSslConfig");	//$NON-NLS-1$
	public static ExpandedName EXTN_JMS_SSL_CONFIG = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnJmsSslConfig");	//$NON-NLS-1$
	public static ExpandedName EXTN_JAVA_TASK_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/activities","ExtnJavaTaskData");	//$NON-NLS-1$
	public static ExpandedName EXTN_PROPERTY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/process/data","ExtnPropertyData");	//$NON-NLS-1$
	public static ExpandedName EXTN_END_POINT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/service","ExtnEndPointData");	//$NON-NLS-1$
	public static ExpandedName EXTN_OPERATION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/service","ExtnOperationData");	//$NON-NLS-1$
	public static ExpandedName EXTN_INTERFACE_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/service","ExtnInterfaceData");	//$NON-NLS-1$
	public static ExpandedName EXTN_FLOW_ELEMENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnFlowElementData");	//$NON-NLS-1$
	public static ExpandedName EXTN_FLOW_NODE_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnFlowNodeData");	//$NON-NLS-1$
	public static ExpandedName EXTN_FLOW_ELEMENTS_CONTAINER_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnFlowElementsContainerData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SEQUENCE_FLOW_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnSequenceFlowData");	//$NON-NLS-1$
	public static ExpandedName EXTN_CALLABLE_ELEMENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnCallableElementData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SCOPE_CONTAINER_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnScopeContainerData");	//$NON-NLS-1$
	public static ExpandedName EXTN_SYMBOL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnSymbol");	//$NON-NLS-1$
	public static ExpandedName EXTN_PROPERTY_DEFINITION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnPropertyDefinitionData");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","PROPERTY_TYPES");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_String = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","String");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Integer = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Integer");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Long = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Long");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Double = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Double");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Boolean = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Boolean");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_DateTime = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","DateTime");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Concept = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Concept");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_ConceptReference = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","ConceptReference");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Event = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Event");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Process = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Process");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROPERTY_TYPES_Void = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/PROPERTY_TYPES","Void");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","TIME_UNITS");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Milliseconds = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Milliseconds");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Seconds = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Seconds");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Minutes = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Minutes");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Hours = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Hours");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Days = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Days");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_WeekDays = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","WeekDays");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Weeks = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Weeks");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Months = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Months");	//$NON-NLS-1$
	public static ExpandedName ENUM_TIME_UNITS_Years = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/TIME_UNITS","Years");	//$NON-NLS-1$
	public static ExpandedName ENUM_VARIABLE_SCOPE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","VARIABLE_SCOPE");	//$NON-NLS-1$
	public static ExpandedName ENUM_VARIABLE_SCOPE_NODE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/VARIABLE_SCOPE","NODE");	//$NON-NLS-1$
	public static ExpandedName ENUM_VARIABLE_SCOPE_CONTAINER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/VARIABLE_SCOPE","CONTAINER");	//$NON-NLS-1$
	public static ExpandedName EXTN_VARIABLE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnVariable");	//$NON-NLS-1$
	public static ExpandedName EXTN_POINT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnPoint");	//$NON-NLS-1$
	public static ExpandedName EXTN_EVENT_REPLY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnEventReplyData");	//$NON-NLS-1$
	public static ExpandedName EXTN_DESTINATION_CONFIG_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnDestinationConfigData");	//$NON-NLS-1$
	public static ExpandedName EXTN_MESSAGE_STARTER_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common","ExtnMessageStarterData");	//$NON-NLS-1$
	public static ExpandedName EXTN_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_CATCH_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnCatchEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_THROW_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnThrowEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_START_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnStartEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_END_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnEndEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_BOUNDARY_EVENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/events","ExtnBoundaryEventData");	//$NON-NLS-1$
	public static ExpandedName EXTN_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_INCLUSIVE_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnInclusiveGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_EXCLUSIVE_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnExclusiveGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_PARALLEL_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnParallelGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_COMPLEX_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnComplexGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_EVENT_BASED_GATEWAY_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnEventBasedGatewayData");	//$NON-NLS-1$
	public static ExpandedName EXTN_EXPRESSION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnExpressionData");	//$NON-NLS-1$
	public static ExpandedName EXTN_GATEWAY_EXPRESSION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","ExtnGatewayExpressionData");	//$NON-NLS-1$
	public static ExpandedName ENUM_MAPPING_OPTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways","MAPPING_OPTION");	//$NON-NLS-1$
	public static ExpandedName ENUM_MAPPING_OPTION_MAPPER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways/MAPPING_OPTION","MAPPER");	//$NON-NLS-1$
	public static ExpandedName ENUM_MAPPING_OPTION_COPY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/gateways/MAPPING_OPTION","COPY");	//$NON-NLS-1$
	public static ExpandedName EXTN_ARTIFACT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/artifacts","ExtnArtifactData");	//$NON-NLS-1$
	public static ExpandedName EXTN_ASSOCIATION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/artifacts","ExtnAssociationData");	//$NON-NLS-1$
	public static ExpandedName EXTN_TEXT_ANNOTATION_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/common/artifacts","ExtnTextAnnotationData");	//$NON-NLS-1$
	public static ExpandedName EXTN_BASE_ELEMENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/foundation","ExtnBaseElementData");	//$NON-NLS-1$
	public static ExpandedName EXTN_ROOT_ELEMENT_DATA = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/extension/semantic/core/foundation","ExtnRootElementData");	//$NON-NLS-1$
	public static final String E_ATTR_ACK_MODE = "ackMode"; 	//$NON-NLS-1$
	public static final String E_ATTR_ANY_EVENT = "anyEvent"; 	//$NON-NLS-1$
	public static final String E_ATTR_ANY_RECEIVE_TASK = "anyReceiveTask"; 	//$NON-NLS-1$
	public static final String E_ATTR_ARRAY = "array"; 	//$NON-NLS-1$
	public static final String E_ATTR_ASYNC = "async"; 	//$NON-NLS-1$
	public static final String E_ATTR_AUTHOR = "author"; 	//$NON-NLS-1$
	public static final String E_ATTR_BEND_POINTS = "bendPoints"; 	//$NON-NLS-1$
	public static final String E_ATTR_BINDING_TYPE = "bindingType"; 	//$NON-NLS-1$
	public static final String E_ATTR_BREADTH = "breadth"; 	//$NON-NLS-1$
	public static final String E_ATTR_CATCH_NODE_ID = "catchNodeId"; 	//$NON-NLS-1$
	public static final String E_ATTR_CERTIFICATE_FOLDER = "certificateFolder"; 	//$NON-NLS-1$
	public static final String E_ATTR_CHECK_POINT = "checkPoint"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONCEPT_TYPE_PATH = "conceptTypePath"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONNECTION_PASSWORD = "connectionPassword"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONNECTION_USER_NAME = "connectionUserName"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONSUME = "consume"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONSUME_EVENT = "consumeEvent"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONTENT_ENCODING = "contentEncoding"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONTENT_TYPE = "contentType"; 	//$NON-NLS-1$
	public static final String E_ATTR_DEBUG_TRACE = "debugTrace"; 	//$NON-NLS-1$
	public static final String E_ATTR_DECISIONTABLE = "decisiontable"; 	//$NON-NLS-1$
	public static final String E_ATTR_DELIVERY_MODE = "deliveryMode"; 	//$NON-NLS-1$
	public static final String E_ATTR_DEPLOYED = "deployed"; 	//$NON-NLS-1$
	public static final String E_ATTR_DESTINATION = "destination"; 	//$NON-NLS-1$
	public static final String E_ATTR_DESTINATION_CONFIG = "destinationConfig"; 	//$NON-NLS-1$
	public static final String E_ATTR_DESTINATION_NAME = "destinationName"; 	//$NON-NLS-1$
	public static final String E_ATTR_END_POINT = "endPoint"; 	//$NON-NLS-1$
	public static final String E_ATTR_END_POINT_URL = "endPointUrl"; 	//$NON-NLS-1$
	public static final String E_ATTR_ENTITY_PATH = "entityPath"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVENT = "event"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPANDED = "expanded"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPECTED_HOSTNAME = "expectedHostname"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPIRATION = "expiration"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPRESSION = "expression"; 	//$NON-NLS-1$
	public static final String E_ATTR_FORK_EXPRESSIONS = "forkExpressions"; 	//$NON-NLS-1$
	public static final String E_ATTR_FORK_MAPPING_OPTION = "forkMappingOption"; 	//$NON-NLS-1$
	public static final String E_ATTR_FORK_RULEFUNCTION = "forkRulefunction"; 	//$NON-NLS-1$
	public static final String E_ATTR_HTTP_SSL_CONFIG = "httpSslConfig"; 	//$NON-NLS-1$
	public static final String E_ATTR_ID_NAME = "idName"; 	//$NON-NLS-1$
	public static final String E_ATTR_IDENTITY = "identity"; 	//$NON-NLS-1$
	public static final String E_ATTR_IMPLEMENTATIONS = "implementations"; 	//$NON-NLS-1$
	public static final String E_ATTR_INLINE = "inline"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_MAP_XSLT = "inputMapXslt"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_PAYLOAD_SCHEMA = "inputPayloadSchema"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_ARRAY = "isArray"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_PRIMITIVE = "isPrimitive"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_VERSION_CHANGED = "isVersionChanged"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_W3C_STANDARD = "isW3cStandard"; 	//$NON-NLS-1$
	public static final String E_ATTR_JAVA_FILE_PATH = "javaFilePath"; 	//$NON-NLS-1$
	public static final String E_ATTR_JAVA_PACKAGE = "javaPackage"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMS_CONFIG = "jmsConfig"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMS_SSL_CONFIG = "jmsSslConfig"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMSCORRELATIONID = "jmscorrelationid"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMSDELIVERYMODE = "jmsdeliverymode"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMSEXPIRATION = "jmsexpiration"; 	//$NON-NLS-1$
	public static final String E_ATTR_JMSPRIORITY = "jmspriority"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_CONNECTION_FACTORY_NAME = "jndiConnectionFactoryName"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_PASSWORD = "jndiPassword"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_PROPS = "jndiProps"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_PROVIDER_CONTEXT_FACTORY = "jndiProviderContextFactory"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_PROVIDER_URL = "jndiProviderURL"; 	//$NON-NLS-1$
	public static final String E_ATTR_JNDI_USER_NAME = "jndiUserName"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOB_DATA_CONCEPT = "jobDataConcept"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOB_KEY = "jobKey"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOIN_EXPRESSION = "joinExpression"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOIN_EXPRESSIONS = "joinExpressions"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOIN_MAPPING_OPTION = "joinMappingOption"; 	//$NON-NLS-1$
	public static final String E_ATTR_JOIN_RULEFUNCTION = "joinRulefunction"; 	//$NON-NLS-1$
	public static final String E_ATTR_LABEL = "label"; 	//$NON-NLS-1$
	public static final String E_ATTR_LABEL_POINT = "labelPoint"; 	//$NON-NLS-1$
	public static final String E_ATTR_LAST_AUTHOR = "lastAuthor"; 	//$NON-NLS-1$
	public static final String E_ATTR_LAST_DEPLOYED = "lastDeployed"; 	//$NON-NLS-1$
	public static final String E_ATTR_LENGTH = "length"; 	//$NON-NLS-1$
	public static final String E_ATTR_MERGE_EXPRESSION = "mergeExpression"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_FORMAT = "messageFormat"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_STARTER = "messageStarter"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_STARTERS = "messageStarters"; 	//$NON-NLS-1$
	public static final String E_ATTR_METHOD_ARGUMENTS = "methodArguments"; 	//$NON-NLS-1$
	public static final String E_ATTR_METHOD_NAME = "methodName"; 	//$NON-NLS-1$
	public static final String E_ATTR_METHOD_RETURN_TYPE = "methodReturnType"; 	//$NON-NLS-1$
	public static final String E_ATTR_NAME = "name"; 	//$NON-NLS-1$
	public static final String E_ATTR_NODE_POINT = "nodePoint"; 	//$NON-NLS-1$
	public static final String E_ATTR_OPERATION = "operation"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_MAP_XSLT = "outputMapXslt"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_PAYLOAD_SCHEMA = "outputPayloadSchema"; 	//$NON-NLS-1$
	public static final String E_ATTR_PORT = "port"; 	//$NON-NLS-1$
	public static final String E_ATTR_PRIORITY = "priority"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROP_TYPE = "propType"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROPERTIES = "properties"; 	//$NON-NLS-1$
	public static final String E_ATTR_QUEUE = "queue"; 	//$NON-NLS-1$
	public static final String E_ATTR_RECEIVE_TASKS = "receiveTasks"; 	//$NON-NLS-1$
	public static final String E_ATTR_REPLY_DESTINATION_NAME = "replyDestinationName"; 	//$NON-NLS-1$
	public static final String E_ATTR_REPLY_EVENT = "replyEvent"; 	//$NON-NLS-1$
	public static final String E_ATTR_REPLY_TO = "replyTo"; 	//$NON-NLS-1$
	public static final String E_ATTR_REQUEST_URI = "requestUri"; 	//$NON-NLS-1$
	public static final String E_ATTR_RULEFUNCTION = "rulefunction"; 	//$NON-NLS-1$
	public static final String E_ATTR_RULES = "rules"; 	//$NON-NLS-1$
	public static final String E_ATTR_SCOPE = "scope"; 	//$NON-NLS-1$
	public static final String E_ATTR_SEQUENCE_FLOW_ID = "sequenceFlowId"; 	//$NON-NLS-1$
	public static final String E_ATTR_SERVICE = "service"; 	//$NON-NLS-1$
	public static final String E_ATTR_SOAP_ACTION = "soapAction"; 	//$NON-NLS-1$
	public static final String E_ATTR_SSL_PASSWORD = "sslPassword"; 	//$NON-NLS-1$
	public static final String E_ATTR_START_POINT = "startPoint"; 	//$NON-NLS-1$
	public static final String E_ATTR_STRONG_CIPHER_SUITE_ONLY = "strongCipherSuiteOnly"; 	//$NON-NLS-1$
	public static final String E_ATTR_SUBJECT = "subject"; 	//$NON-NLS-1$
	public static final String E_ATTR_TARGET_SERVICE = "targetService"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIME_TO_LIVE = "timeToLive"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIMEOUT = "timeout"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIMER_DATA = "timerData"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIMER_ENABLED = "timerEnabled"; 	//$NON-NLS-1$
	public static final String E_ATTR_TOOL_ID = "toolId"; 	//$NON-NLS-1$
	public static final String E_ATTR_TRACE = "trace"; 	//$NON-NLS-1$
	public static final String E_ATTR_TRANSFORMATION = "transformation"; 	//$NON-NLS-1$
	public static final String E_ATTR_TRIGGER_EVENTS = "triggerEvents"; 	//$NON-NLS-1$
	public static final String E_ATTR_TYPE = "type"; 	//$NON-NLS-1$
	public static final String E_ATTR_UNIT = "unit"; 	//$NON-NLS-1$
	public static final String E_ATTR_URI = "uri"; 	//$NON-NLS-1$
	public static final String E_ATTR_USE_HTTP_SSL = "useHttpSsl"; 	//$NON-NLS-1$
	public static final String E_ATTR_USE_JMS_SSL = "useJmsSsl"; 	//$NON-NLS-1$
	public static final String E_ATTR_VALUE = "value"; 	//$NON-NLS-1$
	public static final String E_ATTR_VARIABLES = "variables"; 	//$NON-NLS-1$
	public static final String E_ATTR_VERIFY_HOST_NAME = "verifyHostName"; 	//$NON-NLS-1$
	public static final String E_ATTR_VERSION = "version"; 	//$NON-NLS-1$
	public static final String E_ATTR_VIRTUALRULEFUNCTION = "virtualrulefunction"; 	//$NON-NLS-1$
	public static final String E_ATTR_WSDL = "wsdl"; 	//$NON-NLS-1$
	public static final String E_ATTR_X = "x"; 	//$NON-NLS-1$
	public static final String E_ATTR_Y = "y"; 	//$NON-NLS-1$
	public static final String E_ATTR_ZOOM_LEVEL = "zoomLevel"; 	//$NON-NLS-1$

}
