package com.tibco.cep.bpmn.model.designtime.metamodel;

import com.tibco.xml.data.primitive.ExpandedName;

/**
**	Generated on 2014.09.09 AD at 02:48:50 IST
**	by BpmnMetaModelInterfaceGenerator
**
**/

public interface BpmnMetaModelConstants extends BpmnMetaModelExtensionConstants { 

	public static ExpandedName DEFINITIONS = ExpandedName.makeName("http://com/tibco/cep/bpmn/core/mode/index/cep-bpmn-index.ecore","Definitions");	//$NON-NLS-1$
	public static ExpandedName IMPORT = ExpandedName.makeName("http://com/tibco/cep/bpmn/core/mode/index/cep-bpmn-index.ecore","Import");	//$NON-NLS-1$
	public static ExpandedName PROCESS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","Process");	//$NON-NLS-1$
	public static ExpandedName AUDITING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","Auditing");	//$NON-NLS-1$
	public static ExpandedName MONITORING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","Monitoring");	//$NON-NLS-1$
	public static ExpandedName LANE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","Lane");	//$NON-NLS-1$
	public static ExpandedName LANE_SET = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","LaneSet");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","GlobalTask");	//$NON-NLS-1$
	public static ExpandedName PERFORMER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","Performer");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROCESS_TYPE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore","ProcessType");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROCESS_TYPE_NONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore/ProcessType","NONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROCESS_TYPE_PUBLIC = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore/ProcessType","PUBLIC");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROCESS_TYPE_NON_EXECUTABLE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore/ProcessType","NON_EXECUTABLE");	//$NON-NLS-1$
	public static ExpandedName ENUM_PROCESS_TYPE_EXECUTABLE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore/ProcessType","EXECUTABLE");	//$NON-NLS-1$
	public static ExpandedName DATA_STATE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataState");	//$NON-NLS-1$
	public static ExpandedName INPUT_OUTPUT_SPECIFICATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","InputOutputSpecification");	//$NON-NLS-1$
	public static ExpandedName INPUT_SET = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","InputSet");	//$NON-NLS-1$
	public static ExpandedName DATA_INPUT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataInput");	//$NON-NLS-1$
	public static ExpandedName ITEM_AWARE_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","ItemAwareElement");	//$NON-NLS-1$
	public static ExpandedName DATA_OUTPUT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataOutput");	//$NON-NLS-1$
	public static ExpandedName INPUT_OUTPUT_BINDING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","InputOutputBinding");	//$NON-NLS-1$
	public static ExpandedName PROPERTY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","Property");	//$NON-NLS-1$
	public static ExpandedName DATA_OUTPUT_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataOutputAssociation");	//$NON-NLS-1$
	public static ExpandedName DATA_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataAssociation");	//$NON-NLS-1$
	public static ExpandedName ASSIGNMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","Assignment");	//$NON-NLS-1$
	public static ExpandedName DATA_INPUT_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataInputAssociation");	//$NON-NLS-1$
	public static ExpandedName DATA_OBJECT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataObject");	//$NON-NLS-1$
	public static ExpandedName DATA_STORE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataStore");	//$NON-NLS-1$
	public static ExpandedName DATA_STORE_REFERENCE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","DataStoreReference");	//$NON-NLS-1$
	public static ExpandedName OUTPUT_SET = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/data/cep-bpmn.ecore","OutputSet");	//$NON-NLS-1$
	public static ExpandedName SERVICE_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ServiceTask");	//$NON-NLS-1$
	public static ExpandedName TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","Task");	//$NON-NLS-1$
	public static ExpandedName ENUM_IMPLEMENTATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","Implementation");	//$NON-NLS-1$
	public static ExpandedName ENUM_IMPLEMENTATION_WEB_SERVICE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/Implementation","WEB_SERVICE");	//$NON-NLS-1$
	public static ExpandedName ENUM_IMPLEMENTATION_OTHER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/Implementation","OTHER");	//$NON-NLS-1$
	public static ExpandedName ENUM_IMPLEMENTATION_UNSPECIFIED = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/Implementation","UNSPECIFIED");	//$NON-NLS-1$
	public static ExpandedName SUB_PROCESS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","SubProcess");	//$NON-NLS-1$
	public static ExpandedName LOOP_CHARACTERISTICS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","LoopCharacteristics");	//$NON-NLS-1$
	public static ExpandedName ENUM_MULTI_INSTANCE_BEHAVIOR = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","MultiInstanceBehavior");	//$NON-NLS-1$
	public static ExpandedName ENUM_MULTI_INSTANCE_BEHAVIOR_NONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/MultiInstanceBehavior","NONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_MULTI_INSTANCE_BEHAVIOR_ONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/MultiInstanceBehavior","ONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_MULTI_INSTANCE_BEHAVIOR_ALL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/MultiInstanceBehavior","ALL");	//$NON-NLS-1$
	public static ExpandedName ENUM_MULTI_INSTANCE_BEHAVIOR_COMPLEX = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/MultiInstanceBehavior","COMPLEX");	//$NON-NLS-1$
	public static ExpandedName MULTI_INSTANCE_LOOP_CHARACTERISTICS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","MultiInstanceLoopCharacteristics");	//$NON-NLS-1$
	public static ExpandedName COMPLEX_BEHAVIOR_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ComplexBehaviorDefinition");	//$NON-NLS-1$
	public static ExpandedName STANDARD_LOOP_CHARACTERISTICS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","StandardLoopCharacteristics");	//$NON-NLS-1$
	public static ExpandedName CALL_ACTIVITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","CallActivity");	//$NON-NLS-1$
	public static ExpandedName SEND_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","SendTask");	//$NON-NLS-1$
	public static ExpandedName RECEIVE_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ReceiveTask");	//$NON-NLS-1$
	public static ExpandedName SCRIPT_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ScriptTask");	//$NON-NLS-1$
	public static ExpandedName BUSINESS_RULE_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","BusinessRuleTask");	//$NON-NLS-1$
	public static ExpandedName AD_HOC_SUB_PROCESS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","AdHocSubProcess");	//$NON-NLS-1$
	public static ExpandedName ENUM_AD_HOC_ORDERING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","AdHocOrdering");	//$NON-NLS-1$
	public static ExpandedName ENUM_AD_HOC_ORDERING_PARALLEL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/AdHocOrdering","PARALLEL");	//$NON-NLS-1$
	public static ExpandedName ENUM_AD_HOC_ORDERING_SEQUENTIAL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/AdHocOrdering","SEQUENTIAL");	//$NON-NLS-1$
	public static ExpandedName TRANSACTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","Transaction");	//$NON-NLS-1$
	public static ExpandedName ENUM_TRANSACTION_METHOD = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","TransactionMethod");	//$NON-NLS-1$
	public static ExpandedName ENUM_TRANSACTION_METHOD_COMPENSATE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/TransactionMethod","COMPENSATE");	//$NON-NLS-1$
	public static ExpandedName ENUM_TRANSACTION_METHOD_STORE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/TransactionMethod","STORE");	//$NON-NLS-1$
	public static ExpandedName ENUM_TRANSACTION_METHOD_IMAGE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/TransactionMethod","IMAGE");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_SCRIPT_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","GlobalScriptTask");	//$NON-NLS-1$
	public static ExpandedName ACTIVITY_RESOURCE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ActivityResource");	//$NON-NLS-1$
	public static ExpandedName RESOURCE_PARAMETER_BINDING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ResourceParameterBinding");	//$NON-NLS-1$
	public static ExpandedName RESOURCE_ASSIGNMENT_EXPRESSION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","ResourceAssignmentExpression");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_BUSINESS_RULE_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","GlobalBusinessRuleTask");	//$NON-NLS-1$
	public static ExpandedName ACTIVITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","Activity");	//$NON-NLS-1$
	public static ExpandedName RULE_FUNCTION_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","RuleFunctionTask");	//$NON-NLS-1$
	public static ExpandedName INFERENCE_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","InferenceTask");	//$NON-NLS-1$
	public static ExpandedName JAVA_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","JavaTask");	//$NON-NLS-1$
	public static ExpandedName ENUM_LOOP_TYPE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","LoopType");	//$NON-NLS-1$
	public static ExpandedName ENUM_LOOP_TYPE_NONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/LoopType","NONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_LOOP_TYPE_ITERATOR = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/LoopType","ITERATOR");	//$NON-NLS-1$
	public static ExpandedName ENUM_LOOP_TYPE_COUNT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore/LoopType","COUNT");	//$NON-NLS-1$
	public static ExpandedName ITERARTOR_DATATYPE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","IterartorDatatype");	//$NON-NLS-1$
	public static ExpandedName MOVE_TO_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/activities/cep-bpmn.ecore","MoveToTask");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_MANUAL_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","GlobalManualTask");	//$NON-NLS-1$
	public static ExpandedName MANUAL_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","ManualTask");	//$NON-NLS-1$
	public static ExpandedName USER_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","UserTask");	//$NON-NLS-1$
	public static ExpandedName RENDERING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","Rendering");	//$NON-NLS-1$
	public static ExpandedName ENUM_USER_TASK_IMPLEMENTATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","UserTaskImplementation");	//$NON-NLS-1$
	public static ExpandedName ENUM_USER_TASK_IMPLEMENTATION_UNSPECIFIED = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore/UserTaskImplementation","UNSPECIFIED");	//$NON-NLS-1$
	public static ExpandedName ENUM_USER_TASK_IMPLEMENTATION_OTHER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore/UserTaskImplementation","OTHER");	//$NON-NLS-1$
	public static ExpandedName ENUM_USER_TASK_IMPLEMENTATION_WEB_SERVICE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore/UserTaskImplementation","WEB_SERVICE");	//$NON-NLS-1$
	public static ExpandedName ENUM_USER_TASK_IMPLEMENTATION_HUMAN_TASK_WEBSERVICE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore/UserTaskImplementation","HUMAN_TASK_WEBSERVICE");	//$NON-NLS-1$
	public static ExpandedName HUMAN_PERFORMER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","HumanPerformer");	//$NON-NLS-1$
	public static ExpandedName POTENTIAL_OWNER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","PotentialOwner");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_USER_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/process/humaninteraction/cep-bpmn.ecore","GlobalUserTask");	//$NON-NLS-1$
	public static ExpandedName OPERATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/service/cep-bpmn.ecore","Operation");	//$NON-NLS-1$
	public static ExpandedName END_POINT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/service/cep-bpmn.ecore","EndPoint");	//$NON-NLS-1$
	public static ExpandedName INTERFACE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/service/cep-bpmn.ecore","Interface");	//$NON-NLS-1$
	public static ExpandedName ROOT_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","RootElement");	//$NON-NLS-1$
	public static ExpandedName RELATIONSHIP = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","Relationship");	//$NON-NLS-1$
	public static ExpandedName EXTENSION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","Extension");	//$NON-NLS-1$
	public static ExpandedName EXTENSION_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","ExtensionDefinition");	//$NON-NLS-1$
	public static ExpandedName EXTENSION_ATTRIBUTE_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","ExtensionAttributeDefinition");	//$NON-NLS-1$
	public static ExpandedName EXTENSION_ATTRIBUTE_VALUE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","ExtensionAttributeValue");	//$NON-NLS-1$
	public static ExpandedName ENUM_RELATIONSHIP_DIRECTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","RelationshipDirection");	//$NON-NLS-1$
	public static ExpandedName ENUM_RELATIONSHIP_DIRECTION_NONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore/RelationshipDirection","NONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_RELATIONSHIP_DIRECTION_FORWARD = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore/RelationshipDirection","FORWARD");	//$NON-NLS-1$
	public static ExpandedName ENUM_RELATIONSHIP_DIRECTION_BACKWARD = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore/RelationshipDirection","BACKWARD");	//$NON-NLS-1$
	public static ExpandedName ENUM_RELATIONSHIP_DIRECTION_BOTH = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore/RelationshipDirection","BOTH");	//$NON-NLS-1$
	public static ExpandedName DOCUMENTATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","Documentation");	//$NON-NLS-1$
	public static ExpandedName EXTERNAL_DOMAIN_OBJECT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","ExternalDomainObject");	//$NON-NLS-1$
	public static ExpandedName BASE_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","BaseElement");	//$NON-NLS-1$
	public static ExpandedName SERIALIZABLE_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/foundation/cep-bpmn.ecore","SerializableElement");	//$NON-NLS-1$
	public static ExpandedName MESSAGE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","Message");	//$NON-NLS-1$
	public static ExpandedName ITEM_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ItemDefinition");	//$NON-NLS-1$
	public static ExpandedName ENUM_ITEM_KIND = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ItemKind");	//$NON-NLS-1$
	public static ExpandedName ENUM_ITEM_KIND_PHYSICAL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore/ItemKind","PHYSICAL");	//$NON-NLS-1$
	public static ExpandedName ENUM_ITEM_KIND_INFORMATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore/ItemKind","INFORMATION");	//$NON-NLS-1$
	public static ExpandedName ERROR = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","Error");	//$NON-NLS-1$
	public static ExpandedName CORRELATION_PROPERTY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CorrelationProperty");	//$NON-NLS-1$
	public static ExpandedName CORRELATION_PROPERTY_RETRIEVAL_EXPRESSION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CorrelationPropertyRetrievalExpression");	//$NON-NLS-1$
	public static ExpandedName FORMAL_EXPRESSION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","FormalExpression");	//$NON-NLS-1$
	public static ExpandedName EXPRESSION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","Expression");	//$NON-NLS-1$
	public static ExpandedName INTERACTION_SPECIFICATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","InteractionSpecification");	//$NON-NLS-1$
	public static ExpandedName PARTICIPANT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","Participant");	//$NON-NLS-1$
	public static ExpandedName MESSAGE_FLOW_NODE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","MessageFlowNode");	//$NON-NLS-1$
	public static ExpandedName PARTNER_ROLE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","PartnerRole");	//$NON-NLS-1$
	public static ExpandedName PARTNER_ENTITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","PartnerEntity");	//$NON-NLS-1$
	public static ExpandedName PARTICIPANT_MULTIPLICITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ParticipantMultiplicity");	//$NON-NLS-1$
	public static ExpandedName MESSAGE_FLOW = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","MessageFlow");	//$NON-NLS-1$
	public static ExpandedName FLOW_ELEMENTS_CONTAINER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","FlowElementsContainer");	//$NON-NLS-1$
	public static ExpandedName FLOW_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","FlowElement");	//$NON-NLS-1$
	public static ExpandedName FLOW_NODE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","FlowNode");	//$NON-NLS-1$
	public static ExpandedName SEQUENCE_FLOW = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","SequenceFlow");	//$NON-NLS-1$
	public static ExpandedName PARTICIPANT_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ParticipantAssociation");	//$NON-NLS-1$
	public static ExpandedName MESSAGE_FLOW_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","MessageFlowAssociation");	//$NON-NLS-1$
	public static ExpandedName CORRELATION_KEY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CorrelationKey");	//$NON-NLS-1$
	public static ExpandedName CONVERSATION_ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ConversationAssociation");	//$NON-NLS-1$
	public static ExpandedName RESOURCE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","Resource");	//$NON-NLS-1$
	public static ExpandedName RESOURCE_PARAMETER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","ResourceParameter");	//$NON-NLS-1$
	public static ExpandedName CORRELATION_PROPERTY_BINDING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CorrelationPropertyBinding");	//$NON-NLS-1$
	public static ExpandedName CORRELATION_SUBSCRIPTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CorrelationSubscription");	//$NON-NLS-1$
	public static ExpandedName CALLABLE_ELEMENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/cep-bpmn.ecore","CallableElement");	//$NON-NLS-1$
	public static ExpandedName TEXT_ANNOTATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","TextAnnotation");	//$NON-NLS-1$
	public static ExpandedName ARTIFACT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","Artifact");	//$NON-NLS-1$
	public static ExpandedName GROUP = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","Group");	//$NON-NLS-1$
	public static ExpandedName ASSOCIATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","Association");	//$NON-NLS-1$
	public static ExpandedName ENUM_ASSOCIATION_DIRECTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","AssociationDirection");	//$NON-NLS-1$
	public static ExpandedName ENUM_ASSOCIATION_DIRECTION_NONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore/AssociationDirection","NONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_ASSOCIATION_DIRECTION_ONE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore/AssociationDirection","ONE");	//$NON-NLS-1$
	public static ExpandedName ENUM_ASSOCIATION_DIRECTION_BOTH = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore/AssociationDirection","BOTH");	//$NON-NLS-1$
	public static ExpandedName CATEGORY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","Category");	//$NON-NLS-1$
	public static ExpandedName CATEGORY_VALUE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/artifacts/cep-bpmn.ecore","CategoryValue");	//$NON-NLS-1$
	public static ExpandedName EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","Event");	//$NON-NLS-1$
	public static ExpandedName INTERMEDIATE_CATCH_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","IntermediateCatchEvent");	//$NON-NLS-1$
	public static ExpandedName CATCH_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","CatchEvent");	//$NON-NLS-1$
	public static ExpandedName EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","EventDefinition");	//$NON-NLS-1$
	public static ExpandedName INTERMEDIATE_THROW_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","IntermediateThrowEvent");	//$NON-NLS-1$
	public static ExpandedName THROW_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","ThrowEvent");	//$NON-NLS-1$
	public static ExpandedName END_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","EndEvent");	//$NON-NLS-1$
	public static ExpandedName START_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","StartEvent");	//$NON-NLS-1$
	public static ExpandedName BOUNDARY_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","BoundaryEvent");	//$NON-NLS-1$
	public static ExpandedName IMPLICIT_THROW_EVENT = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","ImplicitThrowEvent");	//$NON-NLS-1$
	public static ExpandedName CANCEL_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","CancelEventDefinition");	//$NON-NLS-1$
	public static ExpandedName ERROR_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","ErrorEventDefinition");	//$NON-NLS-1$
	public static ExpandedName TERMINATE_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","TerminateEventDefinition");	//$NON-NLS-1$
	public static ExpandedName ESCALATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","Escalation");	//$NON-NLS-1$
	public static ExpandedName ESCALATION_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","EscalationEventDefinition");	//$NON-NLS-1$
	public static ExpandedName COMPENSATE_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","CompensateEventDefinition");	//$NON-NLS-1$
	public static ExpandedName TIMER_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","TimerEventDefinition");	//$NON-NLS-1$
	public static ExpandedName LINK_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","LinkEventDefinition");	//$NON-NLS-1$
	public static ExpandedName MESSAGE_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","MessageEventDefinition");	//$NON-NLS-1$
	public static ExpandedName CONDITIONAL_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","ConditionalEventDefinition");	//$NON-NLS-1$
	public static ExpandedName SIGNAL_EVENT_DEFINITION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","SignalEventDefinition");	//$NON-NLS-1$
	public static ExpandedName SIGNAL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/events/cep-bpmn.ecore","Signal");	//$NON-NLS-1$
	public static ExpandedName GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","Gateway");	//$NON-NLS-1$
	public static ExpandedName ENUM_GATEWAY_DIRECTION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","GatewayDirection");	//$NON-NLS-1$
	public static ExpandedName ENUM_GATEWAY_DIRECTION_UNSPECIFIED = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/GatewayDirection","UNSPECIFIED");	//$NON-NLS-1$
	public static ExpandedName ENUM_GATEWAY_DIRECTION_CONVERGING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/GatewayDirection","CONVERGING");	//$NON-NLS-1$
	public static ExpandedName ENUM_GATEWAY_DIRECTION_DIVERGING = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/GatewayDirection","DIVERGING");	//$NON-NLS-1$
	public static ExpandedName ENUM_GATEWAY_DIRECTION_MIXED = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/GatewayDirection","MIXED");	//$NON-NLS-1$
	public static ExpandedName EVENT_BASED_GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","EventBasedGateway");	//$NON-NLS-1$
	public static ExpandedName ENUM_EVENT_BASED_GATEWAY_TYPE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","EventBasedGatewayType");	//$NON-NLS-1$
	public static ExpandedName ENUM_EVENT_BASED_GATEWAY_TYPE_PARALLEL = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/EventBasedGatewayType","PARALLEL");	//$NON-NLS-1$
	public static ExpandedName ENUM_EVENT_BASED_GATEWAY_TYPE_EXCLUSIVE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore/EventBasedGatewayType","EXCLUSIVE");	//$NON-NLS-1$
	public static ExpandedName COMPLEX_GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","ComplexGateway");	//$NON-NLS-1$
	public static ExpandedName EXCLUSIVE_GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","ExclusiveGateway");	//$NON-NLS-1$
	public static ExpandedName INCLUSIVE_GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","InclusiveGateway");	//$NON-NLS-1$
	public static ExpandedName PARALLEL_GATEWAY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/core/common/gateways/cep-bpmn.ecore","ParallelGateway");	//$NON-NLS-1$
	public static ExpandedName CALL_CONVERSATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","CallConversation");	//$NON-NLS-1$
	public static ExpandedName CONVERSATION_NODE = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","ConversationNode");	//$NON-NLS-1$
	public static ExpandedName COMMUNICATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","Communication");	//$NON-NLS-1$
	public static ExpandedName SUB_CONVERSATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","SubConversation");	//$NON-NLS-1$
	public static ExpandedName CONVERSATION_CONTAINER = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","ConversationContainer");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_COMMUNICATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","GlobalCommunication");	//$NON-NLS-1$
	public static ExpandedName CONVERSATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/conversation/cep-bpmn.ecore","Conversation");	//$NON-NLS-1$
	public static ExpandedName COLLABORATION = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/collaboration/cep-bpmn.ecore","Collaboration");	//$NON-NLS-1$
	public static ExpandedName GLOBAL_CHOREOGRAPHY_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/cep-bpmn.ecore","GlobalChoreographyTask");	//$NON-NLS-1$
	public static ExpandedName CHOREOGRAPHY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/cep-bpmn.ecore","Choreography");	//$NON-NLS-1$
	public static ExpandedName CHOREOGRAPHY_ACTIVITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/choreographyactivities/cep-bpmn.ecore","ChoreographyActivity");	//$NON-NLS-1$
	public static ExpandedName CALL_CHOREOGRAPHY_ACTIVITY = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/choreographyactivities/cep-bpmn.ecore","CallChoreographyActivity");	//$NON-NLS-1$
	public static ExpandedName CHOREGRAPHY_SUB_PROCESS = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/choreographyactivities/cep-bpmn.ecore","ChoregraphySubProcess");	//$NON-NLS-1$
	public static ExpandedName CHOREOGRAPHY_TASK = ExpandedName.makeName("http:///com/tibco/cep/bpmn/core/model/semantic/choreography/choreographyactivities/cep-bpmn.ecore","ChoreographyTask");	//$NON-NLS-1$
	public static final String E_ATTR_ITERARTOR = "Iterartor"; 	//$NON-NLS-1$
	public static final String E_ATTR_ITERATOR_XSLT = "IteratorXSLT"; 	//$NON-NLS-1$
	public static final String E_ATTR_ACTIVATION_CONDITION = "activationCondition"; 	//$NON-NLS-1$
	public static final String E_ATTR_ACTIVITY_REF = "activityRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_ARTIFACTS = "artifacts"; 	//$NON-NLS-1$
	public static final String E_ATTR_ASSIGNMENTS = "assignments"; 	//$NON-NLS-1$
	public static final String E_ATTR_ASSOCIATION_DIRECTION = "associationDirection"; 	//$NON-NLS-1$
	public static final String E_ATTR_ATTACHED_TO_REF = "attachedToRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_AUDITING = "auditing"; 	//$NON-NLS-1$
	public static final String E_ATTR_BEHAVIOR = "behavior"; 	//$NON-NLS-1$
	public static final String E_ATTR_BODY = "body"; 	//$NON-NLS-1$
	public static final String E_ATTR_BOUNDARY_EVENT_REFS = "boundaryEventRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_CALLED_ELEMENT = "calledElement"; 	//$NON-NLS-1$
	public static final String E_ATTR_CALLED_ELEMENT_REF = "calledElementRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CANCEL_ACTIVITY = "cancelActivity"; 	//$NON-NLS-1$
	public static final String E_ATTR_CANCEL_REMAINING_INSTANCES = "cancelRemainingInstances"; 	//$NON-NLS-1$
	public static final String E_ATTR_CAPACITY = "capacity"; 	//$NON-NLS-1$
	public static final String E_ATTR_CATEGORIZED_FLOW_ELEMENTS = "categorizedFlowElements"; 	//$NON-NLS-1$
	public static final String E_ATTR_CATEGORY_REF = "categoryRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CATEGORY_VALUE = "categoryValue"; 	//$NON-NLS-1$
	public static final String E_ATTR_CATEGORY_VALUE_REF = "categoryValueRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CHILD_LANE_SET = "childLaneSet"; 	//$NON-NLS-1$
	public static final String E_ATTR_CHOREOGRAPHY_REF = "choreographyRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_COMPLETION_CONDITION = "completionCondition"; 	//$NON-NLS-1$
	public static final String E_ATTR_COMPLETION_QUANTITY = "completionQuantity"; 	//$NON-NLS-1$
	public static final String E_ATTR_COMPLEX_BEHAVIOR_DEFINITION = "complexBehaviorDefinition"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONDITION = "condition"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONDITION_EXPRESSION = "conditionExpression"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONVERSATION_ASSOCIATION = "conversationAssociation"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONVERSATION_ASSOCIATIONS = "conversationAssociations"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONVERSATION_NODES = "conversationNodes"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONVERSATION_REF = "conversationRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CONVERSATIONS = "conversations"; 	//$NON-NLS-1$
	public static final String E_ATTR_CORRELATION_KEY_REF = "correlationKeyRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CORRELATION_KEYS = "correlationKeys"; 	//$NON-NLS-1$
	public static final String E_ATTR_CORRELATION_PROPERTY_BINDING = "correlationPropertyBinding"; 	//$NON-NLS-1$
	public static final String E_ATTR_CORRELATION_PROPERTY_REF = "correlationPropertyRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_CORRELATION_PROPERTY_RETRIEVAL_EXPRESSION = "correlationPropertyRetrievalExpression"; 	//$NON-NLS-1$
	public static final String E_ATTR_CREATION_DATE = "creationDate"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_INPUT = "dataInput"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_INPUT_ASSOCIATION = "dataInputAssociation"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_INPUT_ASSOCIATIONS = "dataInputAssociations"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_INPUT_REFS = "dataInputRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_INPUTS = "dataInputs"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_OUTPUT = "dataOutput"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_OUTPUT_ASSOCIATION = "dataOutputAssociation"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_OUTPUT_ASSOCIATIONS = "dataOutputAssociations"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_OUTPUT_REFS = "dataOutputRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_OUTPUTS = "dataOutputs"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_PATH = "dataPath"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_STATE = "dataState"; 	//$NON-NLS-1$
	public static final String E_ATTR_DATA_STORE_REF = "dataStoreRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_DEFAULT = "default"; 	//$NON-NLS-1$
	public static final String E_ATTR_DEFINITION = "definition"; 	//$NON-NLS-1$
	public static final String E_ATTR_DEFINITIONAL_COLLABORATION_REF = "definitionalCollaborationRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_DIRECTION = "direction"; 	//$NON-NLS-1$
	public static final String E_ATTR_DOCUMENTATION = "documentation"; 	//$NON-NLS-1$
	public static final String E_ATTR_DOMAIN_OBJECT = "domainObject"; 	//$NON-NLS-1$
	public static final String E_ATTR_ENDPOINT_REFS = "endpointRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_ERROR_CODE = "errorCode"; 	//$NON-NLS-1$
	public static final String E_ATTR_ERROR_REF = "errorRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_ERROR_REFS = "errorRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_ESCALATION_CODE = "escalationCode"; 	//$NON-NLS-1$
	public static final String E_ATTR_ESCALATION_REF = "escalationRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVALUATES_TO_TYPE_REF = "evaluatesToTypeRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVENT = "event"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVENT_DEFINITION_REFS = "eventDefinitionRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVENT_DEFINITIONS = "eventDefinitions"; 	//$NON-NLS-1$
	public static final String E_ATTR_EVENT_GATEWAY_TYPE = "eventGatewayType"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPRESSION = "expression"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXPRESSION_LANGUAGE = "expressionLanguage"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSION_ATTRIBUTE_DEFINITION = "extensionAttributeDefinition"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSION_ATTRIBUTE_DEFINITIONS = "extensionAttributeDefinitions"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSION_DEFINITION = "extensionDefinition"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSION_DEFINITIONS = "extensionDefinitions"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSION_VALUES = "extensionValues"; 	//$NON-NLS-1$
	public static final String E_ATTR_EXTENSIONS = "extensions"; 	//$NON-NLS-1$
	public static final String E_ATTR_FLOW_ELEMENT_REFS = "flowElementRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_FLOW_ELEMENTS = "flowElements"; 	//$NON-NLS-1$
	public static final String E_ATTR_FOLDER = "folder"; 	//$NON-NLS-1$
	public static final String E_ATTR_FROM = "from"; 	//$NON-NLS-1$
	public static final String E_ATTR_GATEWAY_DIRECTION = "gatewayDirection"; 	//$NON-NLS-1$
	public static final String E_ATTR_ID = "id"; 	//$NON-NLS-1$
	public static final String E_ATTR_IMPLEMENTATION = "implementation"; 	//$NON-NLS-1$
	public static final String E_ATTR_IMPORT = "import"; 	//$NON-NLS-1$
	public static final String E_ATTR_IMPORT_TYPE = "importType"; 	//$NON-NLS-1$
	public static final String E_ATTR_IMPORTS = "imports"; 	//$NON-NLS-1$
	public static final String E_ATTR_IN_MESSAGE_REF = "inMessageRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_INCOMING = "incoming"; 	//$NON-NLS-1$
	public static final String E_ATTR_INITIATING_PARTICIPANT_REF = "initiatingParticipantRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_INNER_MESSAGE_FLOW_REF = "innerMessageFlowRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_INNER_PARTICIPANT = "innerParticipant"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_DATA_ITEM = "inputDataItem"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_DATA_REF = "inputDataRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_SET = "inputSet"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_SET_REFS = "inputSetRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_SET_WITH_OPTIONAL = "inputSetWithOptional"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_SET_WITH_WHILE_EXECUTING = "inputSetWithWhileExecuting"; 	//$NON-NLS-1$
	public static final String E_ATTR_INPUT_SETS = "inputSets"; 	//$NON-NLS-1$
	public static final String E_ATTR_INSTANTIATE = "instantiate"; 	//$NON-NLS-1$
	public static final String E_ATTR_INTERFACE_REFS = "interfaceRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_IO_BINDING = "ioBinding"; 	//$NON-NLS-1$
	public static final String E_ATTR_IO_SPECIFICATION = "ioSpecification"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_CLOSED = "isClosed"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_COLLECTION = "isCollection"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_FOR_COMPENSATION = "isForCompensation"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_IMMEDIATE = "isImmediate"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_INTERRUPTING = "isInterrupting"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_MULTIPLE = "isMultiple"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_REFERENCE = "isReference"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_REQUIRED = "isRequired"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_SEQUENTIAL = "isSequential"; 	//$NON-NLS-1$
	public static final String E_ATTR_IS_UNLIMITED = "isUnlimited"; 	//$NON-NLS-1$
	public static final String E_ATTR_ITEM_KIND = "itemKind"; 	//$NON-NLS-1$
	public static final String E_ATTR_ITEM_SUBJECT_REF = "itemSubjectRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_LANE_SETS = "laneSets"; 	//$NON-NLS-1$
	public static final String E_ATTR_LANES = "lanes"; 	//$NON-NLS-1$
	public static final String E_ATTR_LANGUAGE = "language"; 	//$NON-NLS-1$
	public static final String E_ATTR_LAST_MODIFIED = "lastModified"; 	//$NON-NLS-1$
	public static final String E_ATTR_LAST_PERSISTED = "lastPersisted"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOCATION = "location"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_CARDINALITY = "loopCardinality"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_CHARACTERISTICS = "loopCharacteristics"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_CONDITION = "loopCondition"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_COUNT_XSLT = "loopCountXslt"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_DATA_INPUT = "loopDataInput"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_DATA_OUTPUT = "loopDataOutput"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_DATA_TYPE = "loopDataType"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_MAXIMUM = "loopMaximum"; 	//$NON-NLS-1$
	public static final String E_ATTR_LOOP_TYPE = "loopType"; 	//$NON-NLS-1$
	public static final String E_ATTR_MAXIMUM = "maximum"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE = "message"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_FLOW = "messageFlow"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_FLOW_ASSOCIATIONS = "messageFlowAssociations"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_FLOW_REF = "messageFlowRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_FLOW_REFS = "messageFlowRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_PATH = "messagePath"; 	//$NON-NLS-1$
	public static final String E_ATTR_MESSAGE_REF = "messageRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_METHOD = "method"; 	//$NON-NLS-1$
	public static final String E_ATTR_MINIMUM = "minimum"; 	//$NON-NLS-1$
	public static final String E_ATTR_MONITORING = "monitoring"; 	//$NON-NLS-1$
	public static final String E_ATTR_MUST_UNDERSTAND = "mustUnderstand"; 	//$NON-NLS-1$
	public static final String E_ATTR_NAME = "name"; 	//$NON-NLS-1$
	public static final String E_ATTR_NAMESPACE = "namespace"; 	//$NON-NLS-1$
	public static final String E_ATTR_NEXT_TASK = "nextTask"; 	//$NON-NLS-1$
	public static final String E_ATTR_NONE_BEHAVIOR_EVENT_REF = "noneBehaviorEventRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_ONE_BEHAVIOR_EVENT_REF = "oneBehaviorEventRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_OPERATION_REF = "operationRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_OPERATIONS = "operations"; 	//$NON-NLS-1$
	public static final String E_ATTR_OPTIONAL_INPUT = "optionalInput"; 	//$NON-NLS-1$
	public static final String E_ATTR_OPTIONAL_OUTPUT = "optionalOutput"; 	//$NON-NLS-1$
	public static final String E_ATTR_ORDERING = "ordering"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUT_MESSAGE_REF = "outMessageRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTER_MESSAGE_FLOW_REF = "outerMessageFlowRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTER_PARTICIPANT = "outerParticipant"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTGOING = "outgoing"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_DATA_ITEM = "outputDataItem"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_DATA_REF = "outputDataRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_SET = "outputSet"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_SET_REFS = "outputSetRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_SET_WITH_OPTIONAL = "outputSetWithOptional"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_SET_WITH_WHILE_EXECUTING = "outputSetWithWhileExecuting"; 	//$NON-NLS-1$
	public static final String E_ATTR_OUTPUT_SETS = "outputSets"; 	//$NON-NLS-1$
	public static final String E_ATTR_OWNER_PROJECT = "ownerProject"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARALLEL_MULTIPLE = "parallelMultiple"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARAMTER_REF = "paramterRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARENT_LANE = "parentLane"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTICIPANT_ASSOCIATIONS = "participantAssociations"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTICIPANT_MULTIPLICITY = "participantMultiplicity"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTICIPANT_REFS = "participantRefs"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTICIPANTS = "participants"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTICIPANTS_REF = "participantsRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTITION_ELEMENT = "partitionElement"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTITION_ELEMENT_REF = "partitionElementRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTNER_ENTITY_REF = "partnerEntityRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PARTNER_ROLE_REF = "partnerRoleRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PERFORMERS = "performers"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROCESS_REF = "processRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROCESS_TYPE = "processType"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROPERTIES = "properties"; 	//$NON-NLS-1$
	public static final String E_ATTR_PROTOCOL = "protocol"; 	//$NON-NLS-1$
	public static final String E_ATTR_RELATIONSHIPS = "relationships"; 	//$NON-NLS-1$
	public static final String E_ATTR_RENDERINGS = "renderings"; 	//$NON-NLS-1$
	public static final String E_ATTR_RESOURCE_ASSIGNMENT_EXPRESSION = "resourceAssignmentExpression"; 	//$NON-NLS-1$
	public static final String E_ATTR_RESOURCE_PARAMETER_BINDINGS = "resourceParameterBindings"; 	//$NON-NLS-1$
	public static final String E_ATTR_RESOURCE_PARAMETERS = "resourceParameters"; 	//$NON-NLS-1$
	public static final String E_ATTR_RESOURCE_REF = "resourceRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_RESOURCES = "resources"; 	//$NON-NLS-1$
	public static final String E_ATTR_ROOT_ELEMENTS = "rootElements"; 	//$NON-NLS-1$
	public static final String E_ATTR_SCRIPT = "script"; 	//$NON-NLS-1$
	public static final String E_ATTR_SCRIPT_LANGUAGE = "scriptLanguage"; 	//$NON-NLS-1$
	public static final String E_ATTR_SIGNAL_REF = "signalRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_SOURCE_REF = "sourceRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_SOURCES = "sources"; 	//$NON-NLS-1$
	public static final String E_ATTR_START_QUANTITY = "startQuantity"; 	//$NON-NLS-1$
	public static final String E_ATTR_STRUCTURE = "structure"; 	//$NON-NLS-1$
	public static final String E_ATTR_STRUCTURE_REF = "structureRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_SUPPORTED_INTERFACES_REF = "supportedInterfacesRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_SUPPORTS = "supports"; 	//$NON-NLS-1$
	public static final String E_ATTR_TARGET_NAMESPACE = "targetNamespace"; 	//$NON-NLS-1$
	public static final String E_ATTR_TARGET_REF = "targetRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_TARGETS = "targets"; 	//$NON-NLS-1$
	public static final String E_ATTR_TEST_BEFORE = "testBefore"; 	//$NON-NLS-1$
	public static final String E_ATTR_TEXT = "text"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIME_CYCLE = "timeCycle"; 	//$NON-NLS-1$
	public static final String E_ATTR_TIME_DATE = "timeDate"; 	//$NON-NLS-1$
	public static final String E_ATTR_TO = "to"; 	//$NON-NLS-1$
	public static final String E_ATTR_TRANSFORMATION = "transformation"; 	//$NON-NLS-1$
	public static final String E_ATTR_TRIGGERED_BY_EVENT = "triggeredByEvent"; 	//$NON-NLS-1$
	public static final String E_ATTR_TYPE = "type"; 	//$NON-NLS-1$
	public static final String E_ATTR_TYPE_LANGUAGE = "typeLanguage"; 	//$NON-NLS-1$
	public static final String E_ATTR_UNIQUE_ID = "uniqueId"; 	//$NON-NLS-1$
	public static final String E_ATTR_VALUE = "value"; 	//$NON-NLS-1$
	public static final String E_ATTR_VALUE_REF = "valueRef"; 	//$NON-NLS-1$
	public static final String E_ATTR_VARIABLE_NAME = "variableName"; 	//$NON-NLS-1$
	public static final String E_ATTR_VARIABLE_PATH = "variablePath"; 	//$NON-NLS-1$
	public static final String E_ATTR_VARIABLE_TYPE = "variableType"; 	//$NON-NLS-1$
	public static final String E_ATTR_WAIT_FOR_COMPLETION = "waitForCompletion"; 	//$NON-NLS-1$
	public static final String E_ATTR_WHILE_EXECUTING_INPUT = "whileExecutingInput"; 	//$NON-NLS-1$
	public static final String E_ATTR_WHILE_EXECUTING_OUTPUT = "whileExecutingOutput"; 	//$NON-NLS-1$

}
