/**
 * 
 */
package com.tibco.cep.query.model;

import com.tibco.cep.query.exception.DuplicateAliasException;

/**
 * @author pdhar
 * 
 */

public interface Aliased  {

    
    /**
     * @return the Alias
     */
    String getAlias();


    /**
     * @return if the alias is a pseudo alias
     */
    boolean isPseudoAliased();


    /**
     * sets the alias and if it is generated by the system
     * @param alias
     */
    void setAlias(String alias,boolean isPseudoAliased) throws DuplicateAliasException;
}
