/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.scope.validation;

import com.tibco.cep.studio.core.index.model.ElementReference;
import com.tibco.cep.studio.core.index.model.LocalVariableDef;

import com.tibco.cep.studio.core.index.model.scope.ScopeBlock;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.scope.ScopeBlock}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScopeBlockValidator {
	boolean validate();

	boolean validateType(int value);
	boolean validateParentScopeDef(ScopeBlock value);
	boolean validateChildScopeDefs(EList<ScopeBlock> value);
	boolean validateDefs(EList<LocalVariableDef> value);
	boolean validateRefs(EList<ElementReference> value);
	boolean validateOffset(int value);
	boolean validateLength(int value);
}
