//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.20 at 05:19:13 PM IST 
//


package com.tibco.cep.bemm.persistence.masterhost.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hostId"/>
 *         &lt;element ref="{}hostName"/>
 *         &lt;element ref="{}hostIPAddress"/>
 *         &lt;element ref="{}deploymentPath"/>
 *         &lt;element ref="{}userName"/>
 *         &lt;element ref="{}password"/>
 *         &lt;element ref="{}sshPort"/>
 *         &lt;element ref="{}machineName"/>
 *         &lt;element ref="{}os"/>
 *         &lt;element ref="{}beHome"/>
 *         &lt;element ref="{}beTra"/>
 *         &lt;element ref="{}be" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostId",
    "hostName",
    "hostIPAddress",
    "deploymentPath",
    "userName",
    "password",
    "sshPort",
    "machineName",
    "os",
    "beHome",
    "beTra",
    "be"
})
@XmlRootElement(name = "masterHost")
public class MasterHost {

    @XmlElement(required = true)
    protected String hostId;
    @XmlElement(required = true)
    protected String hostName;
    @XmlElement(required = true)
    protected String hostIPAddress;
    @XmlElement(required = true)
    protected String deploymentPath;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String password;
    protected int sshPort;
    @XmlElement(required = true)
    protected String machineName;
    @XmlElement(required = true)
    protected String os;
    @XmlElement(required = true)
    protected String beHome;
    @XmlElement(required = true)
    protected String beTra;
    @XmlElement(required = true)
    protected List<Be> be;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the hostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * Sets the value of the hostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostId(String value) {
        this.hostId = value;
    }

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

    /**
     * Gets the value of the hostIPAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostIPAddress() {
        return hostIPAddress;
    }

    /**
     * Sets the value of the hostIPAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostIPAddress(String value) {
        this.hostIPAddress = value;
    }

    /**
     * Gets the value of the deploymentPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeploymentPath() {
        return deploymentPath;
    }

    /**
     * Sets the value of the deploymentPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeploymentPath(String value) {
        this.deploymentPath = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the sshPort property.
     * 
     */
    public int getSshPort() {
        return sshPort;
    }

    /**
     * Sets the value of the sshPort property.
     * 
     */
    public void setSshPort(int value) {
        this.sshPort = value;
    }

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the beHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeHome() {
        return beHome;
    }

    /**
     * Sets the value of the beHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeHome(String value) {
        this.beHome = value;
    }

    /**
     * Gets the value of the beTra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeTra() {
        return beTra;
    }

    /**
     * Sets the value of the beTra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeTra(String value) {
        this.beTra = value;
    }

    /**
     * Gets the value of the be property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the be property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Be }
     * 
     * 
     */
    public List<Be> getBe() {
        if (be == null) {
            be = new ArrayList<Be>();
        }
        return this.be;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
