/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tibco.be.monitor.thread.graph.visitor;

import java.io.PrintStream;

/**
 *
 * @author ksubrama
 */
public interface PrintVisitor extends Visitor {
    
    /**
     * Prints the string generated by the visitor.
     * @param stream
     */
    void printString(PrintStream stream) throws Exception;

}
