/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.archive.validation;

import com.tibco.cep.designtime.core.model.archive.CACHE_MODE;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.archive.AdvancedEntitySetting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdvancedEntitySettingValidator {
	boolean validate();

	boolean validateEntity(String value);
	boolean validateDeployed(boolean value);
	boolean validateRecoveryFunction(String value);
	boolean validateCacheMode(CACHE_MODE value);
}
