/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.archive.validation;

import com.tibco.cep.designtime.core.model.archive.AdvancedEntitySetting;
import com.tibco.cep.designtime.core.model.archive.BE_ARCHIVE_TYPE;
import com.tibco.cep.designtime.core.model.archive.CACHE_CONFIG_TYPE;
import com.tibco.cep.designtime.core.model.archive.InputDestination;
import com.tibco.cep.designtime.core.model.archive.OBJECT_MGMT_TYPE;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.archive.BusinessEventsArchiveResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BusinessEventsArchiveResourceValidator {
	boolean validate();

	boolean validateArchiveType(BE_ARCHIVE_TYPE value);
	boolean validateAllRuleSets(boolean value);
	boolean validateAllDestinations(boolean value);
	boolean validateIncludedRuleSets(EList<String> value);
	boolean validateStartupActions(EList<String> value);
	boolean validateShutdownActions(EList<String> value);
	boolean validateInputDestinations(EList<InputDestination> value);
	boolean validateOmCheckPtInterval(int value);
	boolean validateOmCacheSize(int value);
	boolean validateOmCheckPtOpsLimit(int value);
	boolean validateOmDeletePolicy(boolean value);
	boolean validateOmNoRecovery(boolean value);
	boolean validateOmDbEnvironmentDir(String value);
	boolean validateOmtgGlobalCache(String value);
	boolean validateOmtgCacheConfigFile(String value);
	boolean validateAdvancedSettings(EList<AdvancedEntitySetting> value);
	boolean validateObjectMgmtType(OBJECT_MGMT_TYPE value);
	boolean validateAgentGroupName(String value);
	boolean validateCacheConfigType(CACHE_CONFIG_TYPE value);
	boolean validateOmtgCustomRecoveryFactory(String value);
}
