/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.archive.validation;

import com.tibco.cep.designtime.core.model.archive.BusinessEventsArchiveResource;
import com.tibco.cep.designtime.core.model.archive.SharedArchive;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.archive.EnterpriseArchive}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnterpriseArchiveValidator {
	boolean validate();

	boolean validateVersion(String value);
	boolean validateFolder(String value);
	boolean validateOwnerProjectName(String value);
	boolean validateFileLocation(String value);
	boolean validateIncludeGlobalVars(boolean value);
	boolean validateBusinessEventsArchives(EList<BusinessEventsArchiveResource> value);
	boolean validateSharedArchives(EList<SharedArchive> value);
	boolean validateProcessArchives(EList<SharedArchive> value);
}
