/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.archive.validation;

import com.tibco.cep.designtime.core.model.archive.WORKERS;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.archive.InputDestination}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputDestinationValidator {
	boolean validate();

	boolean validateDestinationURI(String value);
	boolean validatePreprocessor(String value);
	boolean validateDefault(boolean value);
	boolean validateEnable(boolean value);
	boolean validateWorkers(WORKERS value);
	boolean validateQueueSize(int value);
}
