<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://com/tibco/cep/bpmn/core/cep-bpmn-index.ecore" nsPrefix="model">
  <eSubpackages name="index" nsURI="http://com/tibco/cep/bpmn/core/mode/index/cep-bpmn-index.ecore"
      nsPrefix="index">
    <eClassifiers xsi:type="ecore:EClass" name="Definitions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionLanguage" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLanguage" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
          eType="#//index/Import" containment="true" eKeys="#//index/Import/importType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" ordered="false"
          upperBound="-1" eType="ecore:EClass cep-bpmn.ecore#//semantic/core/foundation/Extension"
          containment="true" eKeys="cep-bpmn.ecore#//semantic/core/foundation/Extension/name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
          eType="ecore:EClass cep-bpmn.ecore#//semantic/core/foundation/Relationship"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootElements" upperBound="-1"
          eType="ecore:EClass cep-bpmn.ecore#//semantic/core/foundation/RootElement"
          containment="true" eKeys="cep-bpmn.ecore#//semantic/core/foundation/BaseElement/id"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastPersisted" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Import">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="importType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
