//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 11:40:00 AM IST 
//


package com.tibco.cep.bemm.common.service.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.tibco.cep.bemm.model.MasterHost;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.cep.bemm.common.service.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HostIPAddress_QNAME = new QName("", "hostIPAddress");
    private final static QName _BeHome_QNAME = new QName("", "beHome");
    private final static QName _DeploymentPath_QNAME = new QName("", "deploymentPath");
    private final static QName _UserName_QNAME = new QName("", "userName");
    private final static QName _HostName_QNAME = new QName("", "hostName");
    private final static QName _HostId_QNAME = new QName("", "hostId");
    private final static QName _SshPort_QNAME = new QName("", "sshPort");
    private final static QName _BeTra_QNAME = new QName("", "beTra");
    private final static QName _Password_QNAME = new QName("", "password");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.cep.bemm.common.service.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostIPAddress")
    public JAXBElement<String> createHostIPAddress(String value) {
        return new JAXBElement<String>(_HostIPAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beHome")
    public JAXBElement<String> createBeHome(String value) {
        return new JAXBElement<String>(_BeHome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deploymentPath")
    public JAXBElement<String> createDeploymentPath(String value) {
        return new JAXBElement<String>(_DeploymentPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userName")
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostName")
    public JAXBElement<String> createHostName(String value) {
        return new JAXBElement<String>(_HostName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostId")
    public JAXBElement<String> createHostId(String value) {
        return new JAXBElement<String>(_HostId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sshPort")
    public JAXBElement<Integer> createSshPort(Integer value) {
        return new JAXBElement<Integer>(_SshPort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beTra")
    public JAXBElement<String> createBeTra(String value) {
        return new JAXBElement<String>(_BeTra_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

}
