/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.states.validation;

import com.tibco.cep.designtime.core.model.rule.Rule;

import com.tibco.cep.designtime.core.model.states.State;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.states.StateTransition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateTransitionValidator {
	boolean validate();

	boolean validateToState(State value);
	boolean validateFromState(State value);
	boolean validateGuardRule(Rule value);
	boolean validateLambda(boolean value);
	boolean validateFwdCorrelates(boolean value);
	boolean validateLabel(String value);
}
