/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.states.validation;

import com.tibco.cep.designtime.core.model.TIMEOUT_UNITS;

import com.tibco.cep.designtime.core.model.states.StateEntity;
import com.tibco.cep.designtime.core.model.states.StateMachine;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.states.StateEntity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateEntityValidator {
	boolean validate();

	boolean validateOwnerStateMachine(StateMachine value);
	boolean validateOwnerStateMachinePath(String value);
	boolean validateParent(StateEntity value);
	boolean validateTimeout(int value);
	boolean validateTimeoutUnits(TIMEOUT_UNITS value);
}
