/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.states.validation;

import com.tibco.cep.designtime.core.model.states.StateAnnotationLink;
import com.tibco.cep.designtime.core.model.states.StateTransition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.states.StateMachine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateMachineValidator {
	boolean validate();

	boolean validateStateTransitions(EList<StateTransition> value);
	boolean validateAnnotationLinks(EList<StateAnnotationLink> value);
	boolean validateFwdCorrelates(boolean value);
	boolean validateMain(boolean value);
	boolean validateOwnerConceptPath(String value);
}
