/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.states.validation;

import com.tibco.cep.designtime.core.model.rule.Rule;
import com.tibco.cep.designtime.core.model.rule.RuleFunction;

import com.tibco.cep.designtime.core.model.states.State;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.states.State}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
	boolean validate();

	boolean validateInternalTransitionEnabled(boolean value);
	boolean validateEntryAction(Rule value);
	boolean validateExitAction(Rule value);
	boolean validateTimeoutAction(Rule value);
	boolean validateInternalTransitionRule(Rule value);
	boolean validateTimeoutExpression(RuleFunction value);
	boolean validateTimeoutStateGUID(String value);
	boolean validateTimeoutTransitionGUID(String value);
	boolean validateTimeoutPolicy(int value);
	boolean validateTimeoutState(State value);
}
