//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.17 at 03:07:21 PM IST 
//


package com.tibco.tea.agent.be.migration.file.generator.application.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NVPairs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NVPairs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NameValuePair" type="{http://www.tibco.com/xmlns/ApplicationManagement}NameValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NameValuePairPassword" type="{http://www.tibco.com/xmlns/ApplicationManagement}NameValuePairPassword" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NameValuePairBoolean" type="{http://www.tibco.com/xmlns/ApplicationManagement}NameValuePairBoolean" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NameValuePairInteger" type="{http://www.tibco.com/xmlns/ApplicationManagement}NameValuePairInteger" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NVPairs", propOrder = {
    "nameValuePair",
    "nameValuePairPassword",
    "nameValuePairBoolean",
    "nameValuePairInteger"
})
public class NVPairs {

    @XmlElement(name = "NameValuePair")
    protected List<NameValuePair> nameValuePair;
    @XmlElement(name = "NameValuePairPassword")
    protected List<NameValuePairPassword> nameValuePairPassword;
    @XmlElement(name = "NameValuePairBoolean")
    protected List<NameValuePairBoolean> nameValuePairBoolean;
    @XmlElement(name = "NameValuePairInteger")
    protected List<NameValuePairInteger> nameValuePairInteger;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the nameValuePair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameValuePair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameValuePair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePair }
     * 
     * 
     */
    public List<NameValuePair> getNameValuePair() {
        if (nameValuePair == null) {
            nameValuePair = new ArrayList<NameValuePair>();
        }
        return this.nameValuePair;
    }

    /**
     * Gets the value of the nameValuePairPassword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameValuePairPassword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameValuePairPassword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePairPassword }
     * 
     * 
     */
    public List<NameValuePairPassword> getNameValuePairPassword() {
        if (nameValuePairPassword == null) {
            nameValuePairPassword = new ArrayList<NameValuePairPassword>();
        }
        return this.nameValuePairPassword;
    }

    /**
     * Gets the value of the nameValuePairBoolean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameValuePairBoolean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameValuePairBoolean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePairBoolean }
     * 
     * 
     */
    public List<NameValuePairBoolean> getNameValuePairBoolean() {
        if (nameValuePairBoolean == null) {
            nameValuePairBoolean = new ArrayList<NameValuePairBoolean>();
        }
        return this.nameValuePairBoolean;
    }

    /**
     * Gets the value of the nameValuePairInteger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameValuePairInteger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameValuePairInteger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePairInteger }
     * 
     * 
     */
    public List<NameValuePairInteger> getNameValuePairInteger() {
        if (nameValuePairInteger == null) {
            nameValuePairInteger = new ArrayList<NameValuePairInteger>();
        }
        return this.nameValuePairInteger;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
