//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.17 at 03:07:21 PM IST 
//


package com.tibco.tea.agent.be.migration.file.generator.application.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.tea.agent.be.migration.file.generator.application.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.tea.agent.be.migration.file.generator.application.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link NVPairs }
     * 
     */
    public NVPairs createNVPairs() {
        return new NVPairs();
    }

    /**
     * Create an instance of {@link RepoInstances }
     * 
     */
    public RepoInstances createRepoInstances() {
        return new RepoInstances();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link NameValuePairInteger }
     * 
     */
    public NameValuePairInteger createNameValuePairInteger() {
        return new NameValuePairInteger();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link JAVA }
     * 
     */
    public JAVA createJAVA() {
        return new JAVA();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link LocalRepoInstance }
     * 
     */
    public LocalRepoInstance createLocalRepoInstance() {
        return new LocalRepoInstance();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link NameValuePairBoolean }
     * 
     */
    public NameValuePairBoolean createNameValuePairBoolean() {
        return new NameValuePairBoolean();
    }

    /**
     * Create an instance of {@link Bindings }
     * 
     */
    public Bindings createBindings() {
        return new Bindings();
    }

    /**
     * Create an instance of {@link NameValuePairPassword }
     * 
     */
    public NameValuePairPassword createNameValuePairPassword() {
        return new NameValuePairPassword();
    }

}
