package com.tibco.cep.query.client.console.swing.ui;

/**
 *
 * @author ksubrama
 */
public class EditorPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    /** Creates new form EditorPanel */
    public EditorPanel() {
        initComponents();
        initQueryEditor();
    }

    //////////////////////
    // Public methods.
    //////////////////////
    public String getQuery() {
        String selectedText = queryEditor.getSelectedText();
        if(selectedText == null) {
            return queryEditor.getText();
        }
        return selectedText;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        queryEditor = new javax.swing.JEditorPane();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(102, 102, 102)));

        queryEditor.setMaximumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setViewportView(queryEditor);
        queryEditor.getAccessibleContext().setAccessibleDescription(UiConstants.DEFAULT_CONTENT_TYPE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane queryEditor;
    // End of variables declaration//GEN-END:variables

    ///////////////////
    // Private Methods
    ///////////////////
    private void initQueryEditor() {
        queryEditor.setAutoscrolls(true);
        queryEditor.setContentType(UiConstants.DEFAULT_CONTENT_TYPE);
    }

}
