package com.tibco.cep.query.client.console.swing.ui;

import java.awt.Frame;

/**
 *
 * @author ksubrama
 */
public class NewTabDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    /** Creates new form NewTabDialog
     * @param defaultText
     * @param parent
     * @param modal
     */
    public NewTabDialog(String defaultText, Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tabName.setText(defaultText);
        validate();
    }

    public String getTabName() {
        return tabNameString;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        tabName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabNameKeyTyped(evt);
            }
        });

        jLabel1.setText("Tab Name");
        jLabel1.setFocusable(false);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                okButtonKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabName, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tabName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        tabNameString = tabName.getText();
        dispose();
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        char keyChar = evt.getKeyChar();
        if(keyChar == '\n' || keyChar == '\r') {
            okButtonActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyTyped

    private void tabNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabNameKeyTyped
        char keyChar = evt.getKeyChar();
        if(keyChar == '\n' || keyChar == '\r') {
            okButtonActionPerformed(null);
        }
    }//GEN-LAST:event_tabNameKeyTyped

    private void okButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyTyped
        char keyChar = evt.getKeyChar();
        if(keyChar == '\n' || keyChar == '\r') {
            okButtonActionPerformed(null);
        }
    }//GEN-LAST:event_okButtonKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField tabName;
    // End of variables declaration//GEN-END:variables
    private String tabNameString;
}
