package com.tibco.cep.query.client.console.swing.ui;

import com.tibco.cep.query.client.console.swing.control.RunQueryAction;
import com.tibco.cep.query.client.console.swing.control.query.QueryExecutor;
import com.tibco.cep.query.client.console.swing.util.SwingUtil;

/**
 *
 * @author ksubrama
 */
public class RightPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private final RunQueryAction runQueryAction;
    private TabHeader titlePanel;
    private QueryExecutor queryExecutor;

    /** Creates new form RightPanel */
    public RightPanel() {
        initComponents();
        initQueryTypes();        
        this.runQueryAction = new RunQueryAction(this);
    }

    public RightPanel(String title) {
        this();
        this.titlePanel = new TabHeader(this, title);
    }

    public TabHeader getHeader() {
        return titlePanel;
    }

    public ResultPanel getResultPanel() {
        return resultPanel;
    }

    public void setQueryExecutor(QueryExecutor thread) {
        this.queryExecutor = thread;
    }

    private void initQueryTypes() {
        SwingUtil.runInEDT(new SwingUtil.FireAndForgetWork() {

            @Override
            public void doWork() {
                queryType.removeAllItems();
                queryType.setEditable(false);
                queryType.addItem("Continuous");
                queryType.addItem("Snapshot");
                queryType.addItem("Snapshot then Continuous");
                queryType.validate();
            }
        });
    }

    public void enableRunButton() {
        SwingUtil.runInEDT(new SwingUtil.FireAndForgetWork() {

            @Override
            public void doWork() {
                runQueryButton.setEnabled(true);
                stopQueryButton.setEnabled(false);
            }
        });
    }

    public void disableRunButton() {
        SwingUtil.runInEDT(new SwingUtil.FireAndForgetWork() {

            @Override
            public void doWork() {
                runQueryButton.setEnabled(false);
                stopQueryButton.setEnabled(true);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        queryType = new javax.swing.JComboBox();
        runQueryButton = new javax.swing.JButton();
        stopQueryButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        editorPanel = new com.tibco.cep.query.client.console.swing.ui.EditorPanel();
        resultPanel = new com.tibco.cep.query.client.console.swing.ui.ResultPanel();

        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(250, 400));
        setRequestFocusEnabled(false);
        editorPanel.setPreferredSize(new java.awt.Dimension(250, 150));

        queryType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        runQueryButton.setText("Run Query");
        runQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runQueryButtonActionPerformed(evt);
            }
        });

        stopQueryButton.setText("Stop Query");
        stopQueryButton.setEnabled(false);
        stopQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopQueryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(queryType, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runQueryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopQueryButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(queryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(runQueryButton)
                .addComponent(stopQueryButton))
        );

        jSplitPane1.setDividerLocation(0.4f);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(250, 400));
        jSplitPane1.setTopComponent(editorPanel);
        jSplitPane1.setBottomComponent(resultPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runQueryButtonActionPerformed
        runQueryAction.runQuery(editorPanel.getQuery(),
                (String) queryType.getSelectedItem());
    }//GEN-LAST:event_runQueryButtonActionPerformed

    private void stopQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopQueryButtonActionPerformed
        SwingUtil.runInBackground(new SwingUtil.FireAndForgetWork() {

            @Override
            public void doWork() {
                if(queryExecutor != null) {
                    if(queryExecutor.cancel(true) == false) {
                        // Try once more to double check.
                        queryExecutor.cancel(true);
                    }
                    queryExecutor.getQuery().destroyQuery();
                    enableRunButton();
                    // Reset

                    queryExecutor = null;
                    resultPanel.setProgressBarVisible(false);
                }
            }
        });
    }//GEN-LAST:event_stopQueryButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tibco.cep.query.client.console.swing.ui.EditorPanel editorPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox queryType;
    private com.tibco.cep.query.client.console.swing.ui.ResultPanel resultPanel;
    private javax.swing.JButton runQueryButton;
    private javax.swing.JButton stopQueryButton;
    // End of variables declaration//GEN-END:variables

    public void stopQuery() {
        stopQueryButtonActionPerformed(null);
    }
}
