/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.archive.config.validation;

import com.tibco.cep.designtime.core.model.archive.BusinessEventsArchiveResource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.archive.config.Archives}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArchivesValidator {
	boolean validate();

	boolean validateBeArchive(EList<BusinessEventsArchiveResource> value);
}
