#!/bin/bash
#
# Copyright (c) 2016-2019 TIBCO Software Inc.
# All Rights Reserved. Confidential & Proprietary.
# For more information, please contact:
# TIBCO Software Inc., Palo Alto, California, USA
#
#

# TIDDG Home - Path to AS3 Home
TIBDG_ROOT=<AS3x_HOME>
export TIBDG_ROOT

