/**
 *
 * $Id$
 */
package com.tibco.cep.studio.common.configuration.validation;

import com.tibco.cep.studio.common.configuration.LIBRARY_PATH_TYPE;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.common.configuration.BuildPathEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BuildPathEntryValidator {
	boolean validate();

	boolean validateEntryType(LIBRARY_PATH_TYPE value);
	boolean validatePath(String value);
	boolean validateTimestamp(long value);
	boolean validateVar(boolean value);
	boolean validateReadOnly(boolean value);
	boolean validateDeprecated(boolean value);
	boolean validateResolvedPath(String value);
}
