/**
 *
 * $Id$
 */
package com.tibco.cep.studio.common.configuration.validation;

import com.tibco.cep.studio.common.configuration.JAVA_CLASSPATH_ENTRY_TYPE;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.studio.common.configuration.JavaClasspathEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaClasspathEntryValidator {
	boolean validate();

	boolean validateClasspathEntryType(JAVA_CLASSPATH_ENTRY_TYPE value);
	boolean validateSourceFolder(String value);
	boolean validateInclusionPattern(EList<String> value);
	boolean validateExclusionPattern(EList<String> value);
	boolean validateOutputLocation(String value);
	boolean validateSourceAttachmentPath(String value);
	boolean validateSourceAttachmentRootPath(String value);
}
