/**
 *
 * $Id$
 */
package com.tibco.cep.studio.core.index.model.search.validation;


/**
 * A sample validator interface for {@link com.tibco.cep.studio.core.index.model.search.MethodArgumentMatch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodArgumentMatchValidator {
	boolean validate();

	boolean validateFunction(Object value);
	boolean validateArgNode(Object value);
}
