//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 10:44:13 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/cep/bemm/monitoring/metric/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.cep.bemm.monitoring.metric.config;
