//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 10:28:47 AM IST 
//


package com.tibco.cep.bemm.model.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeploymentVariableType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeploymentVariableType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GLOBAL_VARIABLES"/>
 *     &lt;enumeration value="SYSTEM_VARIABLES"/>
 *     &lt;enumeration value="JVM_PROPERTIES"/>
 *     &lt;enumeration value="LOG_CONFIG"/>
 *     &lt;enumeration value="APPLICATION_CONFIG"/>
 *     &lt;enumeration value="INSTANCE_CONFIG"/>
 *     &lt;enumeration value="LOG_PATTERNS"/>
 *     &lt;enumeration value="BE_PROPERTIES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeploymentVariableType")
@XmlEnum
public enum DeploymentVariableType {

    GLOBAL_VARIABLES,
    SYSTEM_VARIABLES,
    JVM_PROPERTIES,
    LOG_CONFIG,
    APPLICATION_CONFIG,
    INSTANCE_CONFIG,
    LOG_PATTERNS,
    BE_PROPERTIES;

    public String value() {
        return name();
    }

    public static DeploymentVariableType fromValue(String v) {
        return valueOf(v);
    }

}
