//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 03:35:08 PM IST 
//


package com.tibco.cep.webstudio.server.model.process;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}isSequential"/>
 *         &lt;element ref="{}loopCount"/>
 *         &lt;element ref="{}completionCondition"/>
 *         &lt;element ref="{}loopCardinality"/>
 *         &lt;element ref="{}testBefore"/>
 *         &lt;element ref="{}loopCondition"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}behavior"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isSequential",
    "loopCount",
    "completionCondition",
    "loopCardinality",
    "testBefore",
    "loopCondition",
    "type",
    "behavior"
})
@XmlRootElement(name = "loopCharacteristics")
public class LoopCharacteristics {

    protected boolean isSequential;
    @XmlElement(required = true)
    protected String loopCount;
    @XmlElement(required = true)
    protected String completionCondition;
    @XmlElement(required = true)
    protected String loopCardinality;
    protected boolean testBefore;
    @XmlElement(required = true)
    protected String loopCondition;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String behavior;
    @XmlAttribute(name = "Id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the isSequential property.
     * 
     */
    public boolean isIsSequential() {
        return isSequential;
    }

    /**
     * Sets the value of the isSequential property.
     * 
     */
    public void setIsSequential(boolean value) {
        this.isSequential = value;
    }

    /**
     * Gets the value of the loopCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopCount() {
        return loopCount;
    }

    /**
     * Sets the value of the loopCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopCount(String value) {
        this.loopCount = value;
    }

    /**
     * Gets the value of the completionCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionCondition() {
        return completionCondition;
    }

    /**
     * Sets the value of the completionCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionCondition(String value) {
        this.completionCondition = value;
    }

    /**
     * Gets the value of the loopCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopCardinality() {
        return loopCardinality;
    }

    /**
     * Sets the value of the loopCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopCardinality(String value) {
        this.loopCardinality = value;
    }

    /**
     * Gets the value of the testBefore property.
     * 
     */
    public boolean isTestBefore() {
        return testBefore;
    }

    /**
     * Sets the value of the testBefore property.
     * 
     */
    public void setTestBefore(boolean value) {
        this.testBefore = value;
    }

    /**
     * Gets the value of the loopCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopCondition() {
        return loopCondition;
    }

    /**
     * Sets the value of the loopCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopCondition(String value) {
        this.loopCondition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the behavior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * Sets the value of the behavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehavior(String value) {
        this.behavior = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
