//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.23 at 09:43:06 PM IST 
//


package com.tibco.cep.webstudio.server.model.process;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.cep.webstudio.server.model.process package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ElementId_QNAME = new QName("", "elementId");
    private final static QName _OpTimeout_QNAME = new QName("", "opTimeout");
    private final static QName _ElementName_QNAME = new QName("", "elementName");
    private final static QName _TargetReference_QNAME = new QName("", "targetReference");
    private final static QName _DefaultSequenceId_QNAME = new QName("", "defaultSequenceId");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Outgoing_QNAME = new QName("", "outgoing");
    private final static QName _CompletionCondition_QNAME = new QName("", "completionCondition");
    private final static QName _Operation_QNAME = new QName("", "operation");
    private final static QName _ElementLabel_QNAME = new QName("", "elementLabel");
    private final static QName _JoinRuleFunction_QNAME = new QName("", "joinRuleFunction");
    private final static QName _SequenceElement_QNAME = new QName("", "sequenceElement");
    private final static QName _FlowNodeElement_QNAME = new QName("", "flowNodeElement");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _BindingType_QNAME = new QName("", "bindingType");
    private final static QName _PriorityValue_QNAME = new QName("", "priorityValue");
    private final static QName _Label_QNAME = new QName("", "label");
    private final static QName _Uri_QNAME = new QName("", "uri");
    private final static QName _ElementType_QNAME = new QName("", "elementType");
    private final static QName _MergeExpression_QNAME = new QName("", "mergeExpression");
    private final static QName _ProcessType_QNAME = new QName("", "processType");
    private final static QName _LoopCardinality_QNAME = new QName("", "loopCardinality");
    private final static QName _ReplyTo_QNAME = new QName("", "replyTo");
    private final static QName _DefinitionType_QNAME = new QName("", "definitionType");
    private final static QName _IsImmediate_QNAME = new QName("", "isImmediate");
    private final static QName _MsgStarterId_QNAME = new QName("", "msgStarterId");
    private final static QName _IsSequential_QNAME = new QName("", "isSequential");
    private final static QName _KeyExpression_QNAME = new QName("", "keyExpression");
    private final static QName _ToolId_QNAME = new QName("", "toolId");
    private final static QName _DocId_QNAME = new QName("", "docId");
    private final static QName _TextValue_QNAME = new QName("", "textValue");
    private final static QName _LaneId_QNAME = new QName("", "laneId");
    private final static QName _Port_QNAME = new QName("", "port");
    private final static QName _Incoming_QNAME = new QName("", "incoming");
    private final static QName _Triggerbyevent_QNAME = new QName("", "triggerbyevent");
    private final static QName _IsMultiple_QNAME = new QName("", "isMultiple");
    private final static QName _SourceReference_QNAME = new QName("", "sourceReference");
    private final static QName _ProcessId_QNAME = new QName("", "processId");
    private final static QName _Behavior_QNAME = new QName("", "behavior");
    private final static QName _Mapping_QNAME = new QName("", "mapping");
    private final static QName _IsDeployed_QNAME = new QName("", "isDeployed");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _Consume_QNAME = new QName("", "consume");
    private final static QName _UniqueId_QNAME = new QName("", "uniqueId");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _ResourcePath_QNAME = new QName("", "resourcePath");
    private final static QName _Transport_QNAME = new QName("", "transport");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Path_QNAME = new QName("", "path");
    private final static QName _DefinitionId_QNAME = new QName("", "definitionId");
    private final static QName _SoapAction_QNAME = new QName("", "soapAction");
    private final static QName _Checkpoint_QNAME = new QName("", "checkpoint");
    private final static QName _Rules_QNAME = new QName("", "rules");
    private final static QName _CreationDate_QNAME = new QName("", "creationDate");
    private final static QName _Service_QNAME = new QName("", "service");
    private final static QName _ForkRuleFunction_QNAME = new QName("", "forkRuleFunction");
    private final static QName _LastModificationDate_QNAME = new QName("", "lastModificationDate");
    private final static QName _Y_QNAME = new QName("", "y");
    private final static QName _X_QNAME = new QName("", "x");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.cep.webstudio.server.model.process
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SequenceFlows }
     * 
     */
    public SequenceFlows createSequenceFlows() {
        return new SequenceFlows();
    }

    /**
     * Create an instance of {@link SequenceElement }
     * 
     */
    public SequenceElement createSequenceElement() {
        return new SequenceElement();
    }

    /**
     * Create an instance of {@link InputMap }
     * 
     */
    public InputMap createInputMap() {
        return new InputMap();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link FlowNodes }
     * 
     */
    public FlowNodes createFlowNodes() {
        return new FlowNodes();
    }

    /**
     * Create an instance of {@link FlowNodeElement }
     * 
     */
    public FlowNodeElement createFlowNodeElement() {
        return new FlowNodeElement();
    }

    /**
     * Create an instance of {@link OutputMap }
     * 
     */
    public OutputMap createOutputMap() {
        return new OutputMap();
    }

    /**
     * Create an instance of {@link NodePoint }
     * 
     */
    public NodePoint createNodePoint() {
        return new NodePoint();
    }

    /**
     * Create an instance of {@link BendPoints }
     * 
     */
    public BendPoints createBendPoints() {
        return new BendPoints();
    }

    /**
     * Create an instance of {@link EventDefinition }
     * 
     */
    public EventDefinition createEventDefinition() {
        return new EventDefinition();
    }

    /**
     * Create an instance of {@link MessageStarterList }
     * 
     */
    public MessageStarterList createMessageStarterList() {
        return new MessageStarterList();
    }

    /**
     * Create an instance of {@link MessageStarter }
     * 
     */
    public MessageStarter createMessageStarter() {
        return new MessageStarter();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link AssociationElement }
     * 
     */
    public AssociationElement createAssociationElement() {
        return new AssociationElement();
    }

    /**
     * Create an instance of {@link Lanes }
     * 
     */
    public Lanes createLanes() {
        return new Lanes();
    }

    /**
     * Create an instance of {@link Superlane }
     * 
     */
    public Superlane createSuperlane() {
        return new Superlane();
    }

    /**
     * Create an instance of {@link Lane }
     * 
     */
    public Lane createLane() {
        return new Lane();
    }

    /**
     * Create an instance of {@link StartPoint }
     * 
     */
    public StartPoint createStartPoint() {
        return new StartPoint();
    }

    /**
     * Create an instance of {@link EndPoint }
     * 
     */
    public EndPoint createEndPoint() {
        return new EndPoint();
    }

    /**
     * Create an instance of {@link BendPointList }
     * 
     */
    public BendPointList createBendPointList() {
        return new BendPointList();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link UriList }
     * 
     */
    public UriList createUriList() {
        return new UriList();
    }

    /**
     * Create an instance of {@link ImplementationURI }
     * 
     */
    public ImplementationURI createImplementationURI() {
        return new ImplementationURI();
    }

    /**
     * Create an instance of {@link LabelPoint }
     * 
     */
    public LabelPoint createLabelPoint() {
        return new LabelPoint();
    }

    /**
     * Create an instance of {@link Laneset }
     * 
     */
    public Laneset createLaneset() {
        return new Laneset();
    }

    /**
     * Create an instance of {@link AnnotationElement }
     * 
     */
    public AnnotationElement createAnnotationElement() {
        return new AnnotationElement();
    }

    /**
     * Create an instance of {@link LoopCharacteristics }
     * 
     */
    public LoopCharacteristics createLoopCharacteristics() {
        return new LoopCharacteristics();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elementId")
    public JAXBElement<String> createElementId(String value) {
        return new JAXBElement<String>(_ElementId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "opTimeout")
    public JAXBElement<BigInteger> createOpTimeout(BigInteger value) {
        return new JAXBElement<BigInteger>(_OpTimeout_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elementName")
    public JAXBElement<String> createElementName(String value) {
        return new JAXBElement<String>(_ElementName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "targetReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTargetReference(String value) {
        return new JAXBElement<String>(_TargetReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaultSequenceId")
    public JAXBElement<String> createDefaultSequenceId(String value) {
        return new JAXBElement<String>(_DefaultSequenceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outgoing")
    public JAXBElement<String> createOutgoing(String value) {
        return new JAXBElement<String>(_Outgoing_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "completionCondition")
    public JAXBElement<String> createCompletionCondition(String value) {
        return new JAXBElement<String>(_CompletionCondition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "operation")
    public JAXBElement<String> createOperation(String value) {
        return new JAXBElement<String>(_Operation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elementLabel")
    public JAXBElement<String> createElementLabel(String value) {
        return new JAXBElement<String>(_ElementLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "joinRuleFunction")
    public JAXBElement<String> createJoinRuleFunction(String value) {
        return new JAXBElement<String>(_JoinRuleFunction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequenceElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sequenceElement")
    public JAXBElement<SequenceElement> createSequenceElement(SequenceElement value) {
        return new JAXBElement<SequenceElement>(_SequenceElement_QNAME, SequenceElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlowNodeElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "flowNodeElement")
    public JAXBElement<FlowNodeElement> createFlowNodeElement(FlowNodeElement value) {
        return new JAXBElement<FlowNodeElement>(_FlowNodeElement_QNAME, FlowNodeElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bindingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBindingType(String value) {
        return new JAXBElement<String>(_BindingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priorityValue")
    public JAXBElement<BigInteger> createPriorityValue(BigInteger value) {
        return new JAXBElement<BigInteger>(_PriorityValue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elementType")
    public JAXBElement<String> createElementType(String value) {
        return new JAXBElement<String>(_ElementType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mergeExpression")
    public JAXBElement<String> createMergeExpression(String value) {
        return new JAXBElement<String>(_MergeExpression_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "processType")
    public JAXBElement<String> createProcessType(String value) {
        return new JAXBElement<String>(_ProcessType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loopCardinality")
    public JAXBElement<String> createLoopCardinality(String value) {
        return new JAXBElement<String>(_LoopCardinality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "replyTo")
    public JAXBElement<Boolean> createReplyTo(Boolean value) {
        return new JAXBElement<Boolean>(_ReplyTo_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "definitionType")
    public JAXBElement<String> createDefinitionType(String value) {
        return new JAXBElement<String>(_DefinitionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isImmediate")
    public JAXBElement<Boolean> createIsImmediate(Boolean value) {
        return new JAXBElement<Boolean>(_IsImmediate_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "msgStarterId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMsgStarterId(String value) {
        return new JAXBElement<String>(_MsgStarterId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isSequential")
    public JAXBElement<Boolean> createIsSequential(Boolean value) {
        return new JAXBElement<Boolean>(_IsSequential_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keyExpression")
    public JAXBElement<String> createKeyExpression(String value) {
        return new JAXBElement<String>(_KeyExpression_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "toolId")
    public JAXBElement<String> createToolId(String value) {
        return new JAXBElement<String>(_ToolId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "docId")
    public JAXBElement<String> createDocId(String value) {
        return new JAXBElement<String>(_DocId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "textValue")
    public JAXBElement<String> createTextValue(String value) {
        return new JAXBElement<String>(_TextValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "laneId")
    public JAXBElement<String> createLaneId(String value) {
        return new JAXBElement<String>(_LaneId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "port")
    public JAXBElement<String> createPort(String value) {
        return new JAXBElement<String>(_Port_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "incoming")
    public JAXBElement<String> createIncoming(String value) {
        return new JAXBElement<String>(_Incoming_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "triggerbyevent")
    public JAXBElement<Boolean> createTriggerbyevent(Boolean value) {
        return new JAXBElement<Boolean>(_Triggerbyevent_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isMultiple")
    public JAXBElement<Boolean> createIsMultiple(Boolean value) {
        return new JAXBElement<Boolean>(_IsMultiple_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sourceReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSourceReference(String value) {
        return new JAXBElement<String>(_SourceReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "processId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProcessId(String value) {
        return new JAXBElement<String>(_ProcessId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "behavior")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBehavior(String value) {
        return new JAXBElement<String>(_Behavior_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mapping")
    public JAXBElement<String> createMapping(String value) {
        return new JAXBElement<String>(_Mapping_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isDeployed")
    public JAXBElement<Boolean> createIsDeployed(Boolean value) {
        return new JAXBElement<Boolean>(_IsDeployed_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<BigInteger> createVersion(BigInteger value) {
        return new JAXBElement<BigInteger>(_Version_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "consume")
    public JAXBElement<Boolean> createConsume(Boolean value) {
        return new JAXBElement<Boolean>(_Consume_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uniqueId")
    public JAXBElement<BigInteger> createUniqueId(BigInteger value) {
        return new JAXBElement<BigInteger>(_UniqueId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resourcePath")
    public JAXBElement<String> createResourcePath(String value) {
        return new JAXBElement<String>(_ResourcePath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transport")
    public JAXBElement<String> createTransport(String value) {
        return new JAXBElement<String>(_Transport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "definitionId")
    public JAXBElement<String> createDefinitionId(String value) {
        return new JAXBElement<String>(_DefinitionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "soapAction")
    public JAXBElement<String> createSoapAction(String value) {
        return new JAXBElement<String>(_SoapAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "checkpoint")
    public JAXBElement<Boolean> createCheckpoint(Boolean value) {
        return new JAXBElement<Boolean>(_Checkpoint_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rules")
    public JAXBElement<String> createRules(String value) {
        return new JAXBElement<String>(_Rules_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creationDate")
    public JAXBElement<String> createCreationDate(String value) {
        return new JAXBElement<String>(_CreationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "service")
    public JAXBElement<String> createService(String value) {
        return new JAXBElement<String>(_Service_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "forkRuleFunction")
    public JAXBElement<String> createForkRuleFunction(String value) {
        return new JAXBElement<String>(_ForkRuleFunction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastModificationDate")
    public JAXBElement<String> createLastModificationDate(String value) {
        return new JAXBElement<String>(_LastModificationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y")
    public JAXBElement<Double> createY(Double value) {
        return new JAXBElement<Double>(_Y_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x")
    public JAXBElement<Double> createX(Double value) {
        return new JAXBElement<Double>(_X_QNAME, Double.class, null, value);
    }

}
