//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.23 at 09:43:06 PM IST 
//


package com.tibco.cep.webstudio.server.model.process;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}label"/>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}processType"/>
 *         &lt;element ref="{}laneset"/>
 *         &lt;element ref="{}properties"/>
 *         &lt;element ref="{}flowNodes"/>
 *         &lt;element ref="{}processId"/>
 *         &lt;element ref="{}sequenceFlows"/>
 *         &lt;element ref="{}creationDate"/>
 *         &lt;element ref="{}lastModificationDate"/>
 *         &lt;element ref="{}annotations"/>
 *         &lt;element ref="{}associations"/>
 *         &lt;element ref="{}author"/>
 *         &lt;element ref="{}documentation"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "label",
    "version",
    "processType",
    "laneset",
    "properties",
    "flowNodes",
    "processId",
    "sequenceFlows",
    "creationDate",
    "lastModificationDate",
    "annotations",
    "associations",
    "author",
    "documentation"
})
@XmlRootElement(name = "process")
public class Process {

    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected BigInteger version;
    @XmlElement(required = true)
    protected String processType;
    @XmlElement(required = true)
    protected Laneset laneset;
    @XmlElement(required = true)
    protected Properties properties;
    @XmlElement(required = true)
    protected FlowNodes flowNodes;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String processId;
    @XmlElement(required = true)
    protected SequenceFlows sequenceFlows;
    @XmlElement(required = true)
    protected String creationDate;
    @XmlElement(required = true)
    protected String lastModificationDate;
    @XmlElement(required = true)
    protected Annotations annotations;
    @XmlElement(required = true)
    protected Associations associations;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected Documentation documentation;
    @XmlAttribute(name = "Id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessType(String value) {
        this.processType = value;
    }

    /**
     * Gets the value of the laneset property.
     * 
     * @return
     *     possible object is
     *     {@link Laneset }
     *     
     */
    public Laneset getLaneset() {
        return laneset;
    }

    /**
     * Sets the value of the laneset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Laneset }
     *     
     */
    public void setLaneset(Laneset value) {
        this.laneset = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the flowNodes property.
     * 
     * @return
     *     possible object is
     *     {@link FlowNodes }
     *     
     */
    public FlowNodes getFlowNodes() {
        return flowNodes;
    }

    /**
     * Sets the value of the flowNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowNodes }
     *     
     */
    public void setFlowNodes(FlowNodes value) {
        this.flowNodes = value;
    }

    /**
     * Gets the value of the processId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessId(String value) {
        this.processId = value;
    }

    /**
     * Gets the value of the sequenceFlows property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceFlows }
     *     
     */
    public SequenceFlows getSequenceFlows() {
        return sequenceFlows;
    }

    /**
     * Sets the value of the sequenceFlows property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceFlows }
     *     
     */
    public void setSequenceFlows(SequenceFlows value) {
        this.sequenceFlows = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the lastModificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModificationDate() {
        return lastModificationDate;
    }

    /**
     * Sets the value of the lastModificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModificationDate(String value) {
        this.lastModificationDate = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link Documentation }
     *     
     */
    public Documentation getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentation }
     *     
     */
    public void setDocumentation(Documentation value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
