//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 03:51:51 PM IST 
//


package com.tibco.cep.webstudio.server.model.process;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for sequenceElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sequenceElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}elementId"/>
 *         &lt;element ref="{}elementType"/>
 *         &lt;element ref="{}elementName"/>
 *         &lt;element ref="{}lanes"/>
 *         &lt;element ref="{}uniqueId"/>
 *         &lt;element ref="{}isImmediate"/>
 *         &lt;element ref="{}targetReference"/>
 *         &lt;element ref="{}sourceReference"/>
 *         &lt;element ref="{}startPoint"/>
 *         &lt;element ref="{}endPoint"/>
 *         &lt;element ref="{}bendPointList"/>
 *         &lt;element ref="{}expression"/>
 *         &lt;element ref="{}documentation"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sequenceElement", propOrder = {
    "elementId",
    "elementType",
    "elementName",
    "lanes",
    "uniqueId",
    "isImmediate",
    "targetReference",
    "sourceReference",
    "startPoint",
    "endPoint",
    "bendPointList",
    "expression",
    "documentation"
})
@XmlSeeAlso({
    AssociationElement.class
})
public class SequenceElement {

    @XmlElement(required = true)
    protected String elementId;
    @XmlElement(required = true)
    protected String elementType;
    @XmlElement(required = true)
    protected String elementName;
    @XmlElement(required = true)
    protected Lanes lanes;
    @XmlElement(required = true)
    protected BigInteger uniqueId;
    protected boolean isImmediate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String targetReference;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sourceReference;
    @XmlElement(required = true)
    protected StartPoint startPoint;
    @XmlElement(required = true)
    protected EndPoint endPoint;
    @XmlElement(required = true)
    protected BendPointList bendPointList;
    @XmlElement(required = true)
    protected String expression;
    @XmlElement(required = true)
    protected Documentation documentation;
    @XmlAttribute(name = "Id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the elementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * Sets the value of the elementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementId(String value) {
        this.elementId = value;
    }

    /**
     * Gets the value of the elementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * Sets the value of the elementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementType(String value) {
        this.elementType = value;
    }

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementName(String value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the lanes property.
     * 
     * @return
     *     possible object is
     *     {@link Lanes }
     *     
     */
    public Lanes getLanes() {
        return lanes;
    }

    /**
     * Sets the value of the lanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lanes }
     *     
     */
    public void setLanes(Lanes value) {
        this.lanes = value;
    }

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUniqueId(BigInteger value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the isImmediate property.
     * 
     */
    public boolean isIsImmediate() {
        return isImmediate;
    }

    /**
     * Sets the value of the isImmediate property.
     * 
     */
    public void setIsImmediate(boolean value) {
        this.isImmediate = value;
    }

    /**
     * Gets the value of the targetReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetReference() {
        return targetReference;
    }

    /**
     * Sets the value of the targetReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetReference(String value) {
        this.targetReference = value;
    }

    /**
     * Gets the value of the sourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceReference() {
        return sourceReference;
    }

    /**
     * Sets the value of the sourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceReference(String value) {
        this.sourceReference = value;
    }

    /**
     * Gets the value of the startPoint property.
     * 
     * @return
     *     possible object is
     *     {@link StartPoint }
     *     
     */
    public StartPoint getStartPoint() {
        return startPoint;
    }

    /**
     * Sets the value of the startPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartPoint }
     *     
     */
    public void setStartPoint(StartPoint value) {
        this.startPoint = value;
    }

    /**
     * Gets the value of the endPoint property.
     * 
     * @return
     *     possible object is
     *     {@link EndPoint }
     *     
     */
    public EndPoint getEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPoint }
     *     
     */
    public void setEndPoint(EndPoint value) {
        this.endPoint = value;
    }

    /**
     * Gets the value of the bendPointList property.
     * 
     * @return
     *     possible object is
     *     {@link BendPointList }
     *     
     */
    public BendPointList getBendPointList() {
        return bendPointList;
    }

    /**
     * Sets the value of the bendPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BendPointList }
     *     
     */
    public void setBendPointList(BendPointList value) {
        this.bendPointList = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link Documentation }
     *     
     */
    public Documentation getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentation }
     *     
     */
    public void setDocumentation(Documentation value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
