//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 08:09:50 PM IST 
//


package com.tibco.cep.bemm.management.export.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element name="clustername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cddversion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}hosts" minOccurs="0"/>
 *         &lt;element name="defaultProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}profiles" minOccurs="0"/>
 *         &lt;element ref="{}hostTraConfigs" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "clustername",
    "cddversion",
    "author",
    "hosts",
    "defaultProfile",
    "profiles",
    "hostTraConfigs"
})
@XmlRootElement(name = "application")
public class Application {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String clustername;
    @XmlElement(required = true)
    protected String cddversion;
    @XmlElement(required = true)
    protected String author;
    protected Hosts hosts;
    protected String defaultProfile;
    protected Profiles profiles;
    protected HostTraConfigs hostTraConfigs;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clustername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClustername() {
        return clustername;
    }

    /**
     * Sets the value of the clustername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClustername(String value) {
        this.clustername = value;
    }

    /**
     * Gets the value of the cddversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCddversion() {
        return cddversion;
    }

    /**
     * Sets the value of the cddversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCddversion(String value) {
        this.cddversion = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the hosts property.
     * 
     * @return
     *     possible object is
     *     {@link Hosts }
     *     
     */
    public Hosts getHosts() {
        return hosts;
    }

    /**
     * Sets the value of the hosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hosts }
     *     
     */
    public void setHosts(Hosts value) {
        this.hosts = value;
    }

    /**
     * Gets the value of the defaultProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultProfile() {
        return defaultProfile;
    }

    /**
     * Sets the value of the defaultProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultProfile(String value) {
        this.defaultProfile = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link Profiles }
     *     
     */
    public Profiles getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profiles }
     *     
     */
    public void setProfiles(Profiles value) {
        this.profiles = value;
    }

    /**
     * Gets the value of the hostTraConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link HostTraConfigs }
     *     
     */
    public HostTraConfigs getHostTraConfigs() {
        return hostTraConfigs;
    }

    /**
     * Sets the value of the hostTraConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostTraConfigs }
     *     
     */
    public void setHostTraConfigs(HostTraConfigs value) {
        this.hostTraConfigs = value;
    }

}
