//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 10:54:37 AM IST 
//


package com.tibco.cep.bemm.management.export.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="behome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="betrapath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "behome",
    "betrapath",
    "version"
})
@XmlRootElement(name = "be")
public class Be {

    @XmlElement(required = true)
    protected String behome;
    @XmlElement(required = true)
    protected String betrapath;
    @XmlElement(required = true)
    protected String version;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the behome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehome() {
        return behome;
    }

    /**
     * Sets the value of the behome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehome(String value) {
        this.behome = value;
    }

    /**
     * Gets the value of the betrapath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBetrapath() {
        return betrapath;
    }

    /**
     * Sets the value of the betrapath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBetrapath(String value) {
        this.betrapath = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
