
  CREATE TABLE "CUSTOMER_ORDER"."CUSTOMERS" 
   (	"CUSTOMER_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_NAME" VARCHAR2(4000 BYTE), 
	"CUSTOMER_ADDRESS" VARCHAR2(4000 BYTE), 
	"CUSTOMER_CITY" VARCHAR2(4000 BYTE), 
	"CUSTOMER_STATE" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID"));
   
   CREATE TABLE "CUSTOMER_ORDER"."ORDERS" 
    (	"ORDER_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
 	"CUSTOMER_ID" VARCHAR2(4000 BYTE), 
 	"ORDER_DATE" VARCHAR2(4000 BYTE), 
 	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID"),   
 	 CONSTRAINT "ORDERS_CUSTOMERS_FK1" FOREIGN KEY ("CUSTOMER_ID")
 	  REFERENCES "CUSTOMER_ORDER"."CUSTOMERS" ("CUSTOMER_ID") ENABLE);
    
   CREATE TABLE "CUSTOMER_ORDER"."ITEMS"(	
   	"ITEM_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
    	"ITEM_DESCRIPTION" VARCHAR2(4000 BYTE), 
    	"ITEM_PRICE" LONG, 
    	 CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ITEM_ID"));
    	 
  CREATE TABLE "CUSTOMER_ORDER"."ORDER_ITEMS" 
    (	"ORDER_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
 	"ITEM_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
 	"ITEM_QTY" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
 	 CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ID", "ITEM_ID") DISABLE, 
 	 CONSTRAINT "ORDER_ITEMS_ORDERS_FK1" FOREIGN KEY ("ORDER_ID")
 	  REFERENCES "CUSTOMER_ORDER"."ORDERS" ("ORDER_ID") ENABLE, 
 	 CONSTRAINT "ORDER_ITEMS_ITEMS_FK1" FOREIGN KEY ("ITEM_ID")
 	  REFERENCES "CUSTOMER_ORDER"."ITEMS" ("ITEM_ID") ENABLE);