/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.rule.validation;


/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.rule.RuleFunctionSymbol}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleFunctionSymbolValidator {
	boolean validate();

	boolean validateDirection(String value);
	boolean validateResourceType(String value);
	boolean validateDomainOverridden(boolean value);
	boolean validateGraphicalPath(String value);
	boolean validatePrimitiveType(String value);
}
