/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.rule.validation;

import com.tibco.cep.designtime.core.model.SimpleProperty;

import com.tibco.cep.designtime.core.model.rule.ActionContext;
import com.tibco.cep.designtime.core.model.rule.Binding;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.rule.RuleTemplate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleTemplateValidator {
	boolean validate();

	boolean validateBindings(EList<Binding> value);
	boolean validateDisplayProperties(EList<SimpleProperty> value);
	boolean validateActionContext(ActionContext value);
	boolean validateViews(EList<String> value);
}
