/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.rule.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.rule.Rule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleValidator {
	boolean validate();

	boolean validatePriority(int value);
	boolean validateMaxRules(int value);
	boolean validateTestInterval(long value);
	boolean validateStartTime(long value);
	boolean validateRequeue(boolean value);
	boolean validateRequeueVars(EList<String> value);
	boolean validateBackwardChain(boolean value);
	boolean validateForwardChain(boolean value);
	boolean validateConditionFunction(boolean value);
	boolean validateFunction(boolean value);
	boolean validateAuthor(String value);
}
