/**
 *
 * $Id$
 */
package com.tibco.cep.designtime.core.model.rule.validation;

import com.tibco.cep.designtime.core.model.rule.Validity;

/**
 * A sample validator interface for {@link com.tibco.cep.designtime.core.model.rule.RuleFunction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleFunctionValidator {
	boolean validate();

	boolean validateValidity(Validity value);
	boolean validateVirtual(boolean value);
	boolean validateAlias(String value);
}
