package com.tibco.cep.runtime.model.event;


import com.tibco.cep.kernel.model.entity.Event;


/**
 *  An event generated by the engine for some specific activity.  e.g. reports an exception.
 *
 * @version 2.0.0
 * @.category public-api
 * @since 2.0.0
 */
//TODO description.
public interface AdvisoryEvent extends Event {

    public static final String CATEGORY_EXCEPTION  = "Exception"; 
    public static final String CATEGORY_DEPLOYMENT = "Deployment";
    public static final String CATEGORY_ENGINE     = "Engine";
    public static final String CATEGORY_BATCH      = "Batch";

    /**
     * Gets the broad category of advisory.
     *
     * @return a String.
     * @.category public-api
     * @see #getType()
     * @since 2.0.0
     */
    String getCategory();


    /**
     * Gets the type of advisory within a particular category.
     *
     * @return a String.
     * @.category public-api
     * @see #getCategory()
     * @since 2.0.0
     */
    String getType();


    /**
     * Gets the message delivering the advice of the advisory.
     *
     * @return a String.
     * @.category public-api
     * @since 2.0.0
     */
    String getMessage();
}
