<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="policy"
    nsURI="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema" nsPrefix="policy">
  <eAnnotations>
    <details key="appinfo" value="&#xD;&#xA;&#x9;    &lt;jxb:schemaBindings xmlns:jxb=&quot;http://java.sun.com/xml/ns/jaxb&quot;>&#xD;&#xA;&#x9;      &lt;jxb:package name=&quot;com.tibco.be.baas.security.authn.saml.metadata.policy.model&quot;>&#xD;&#xA;&#x9;&#x9; &lt;jxb:javadoc>&#xD;&#xA;&#x9;   &lt;![CDATA[&lt;body> Package level documentation for &#xD;&#xA;&#x9;generated package com.tibco.be.baas.security.authn.saml.metadata.policy.model&lt;/body>]]>&#xD;&#xA;&#x9;&#x9; &lt;/jxb:javadoc>&#xD;&#xA;&#x9;      &lt;/jxb:package>&#xD;&#xA;&#x9;    &lt;/jxb:schemaBindings>&#xD;&#xA;&#x9;  "/>
  </eAnnotations>
  <eAnnotations source="http://java.sun.com/xml/ns/jaxb">
    <details key="version" value="2.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigPropertyType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ConfigPropertyType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="targetNamespace" value="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema"/>
      <details key="name" value="configProperty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataTypeType" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="dataType"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//NameType1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;    &#x9;&#x9;&#x9;&#x9;Specify unique name inside a policyconfig&#xA;    &#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyValue" upperBound="-1"
        eType="#//ConfigPropertyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="dataType_._type"/>
    </eAnnotations>
    <eLiterals name="integer"/>
    <eLiterals name="boolean" value="1"/>
    <eLiterals name="double" value="2"/>
    <eLiterals name="float" value="3"/>
    <eLiterals name="datetime" value="4"/>
    <eLiterals name="string" value="5"/>
    <eLiterals name="long" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DataTypeTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="dataType_._type:Object"/>
      <details key="baseType" value="dataType_._type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xmlns:prefix"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xsi:schemaLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authnPolicy" upperBound="-2"
        eType="#//PolicyTemplateType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="AuthnPolicy"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authnPolicyTemplate" upperBound="-2"
        eType="#//PolicyTemplateType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="AuthnPolicyTemplate"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NameType" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="name_._type"/>
      <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#Name"/>
      <details key="whiteSpace" value="collapse"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NameType1" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="name_._1_._type"/>
      <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#Name"/>
      <details key="whiteSpace" value="collapse"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyConfigType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xA;    &#x9;&#x9;&#x9;Add all configuration for this policy in form of&#xA;    &#x9;&#x9;&#x9;attributes/properties to it.&#xA;    &#x9;&#x9;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PolicyConfigType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="targetNamespace" value="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema"/>
      <details key="name" value="policyConfig"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configProperty" upperBound="-1"
        eType="#//ConfigPropertyType" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="configProperty"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyTemplateType" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="All authentication policy templates should adhere to this schema."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PolicyTemplateType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AuthnPolicy"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AuthnPolicyTemplate"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="targetNamespace" value="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema"/>
      <details key="name" value="AuthnPolicy"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="targetNamespace" value="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema"/>
      <details key="name" value="AuthnPolicyTemplate"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyConfig" lowerBound="1"
        eType="#//PolicyConfigType" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="policyConfig"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;    &#x9;&#x9;&#x9;&#x9;Unique ID to identify the Template.&#xA;    &#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//NameType">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PolicyType"/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigPropertyValue">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="targetNamespace" value="http://www.tibco.com/be/baas/authn/PolicyTemplateSchema"/>
      <details key="name" value="propertyValue"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthnPolicy" eSuperTypes="#//PolicyTemplateType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthnPolicyTemplate" eSuperTypes="#//PolicyTemplateType"/>
</ecore:EPackage>
